// Code generated by "task generate" from goal source; DO NOT EDIT.

package fix

//line match.go:4
import (
	"goal/internal/ast"
	"goal/internal/sema"
	"goal/internal/textedit"
)

//line match.goal:15
func fixSwitchToMatch(src string, file *ast.File, info *sema.Info, changes *[]Change, reports *[]Report) []textedit.Replacement {
	ast.Walk(visitFn(func(n ast.Node) bool {
		sw, ok := n.(*ast.SwitchStmt)
		if !ok {
			return true
		}
		enumName := switchEnumQualifier(sw, info)
		if enumName == "" {
			return true
		}
		addReport(reports, Report{lineOf(src, sw.Switch.Offset), Suggest, "match", "`switch` over enum `" + enumName + "`; a `match` would be checked for exhaustiveness"})
		return true
	}), file)
	return nil
}

//line match.goal:36
func switchEnumQualifier(sw *ast.SwitchStmt, info *sema.Info) string {
	if sw.Body == nil {
		return ""
	}
	for _, st := range sw.Body.List {
		cc, ok := st.(*ast.CaseClause)
		if !ok || len(cc.List) == 0 {
			continue
		}
		sel, ok := cc.List[0].(*ast.SelectorExpr)
		if !ok {
			return ""
		}
		q := identName(sel.X)
		if q == "" {
			return ""
		}
		if info.Enums != nil && info.Enums[q] != nil {
			return q
		}
		return ""
	}
	return ""
}
