// Code generated by "task generate" from goal source; DO NOT EDIT.

package lsp

//line codeaction.go:4
import (
	"encoding/json"
	"goal/internal/fix"
	"goal/internal/token"
	"strings"
)

//line codeaction.goal:13
const fixAllKind = "source.fixAll.goal"

//line codeaction.goal:19
func (s *Server) codeActions(raw json.RawMessage) []CodeAction {
	/*line codeaction.goal:20*/ none := []CodeAction{}
	/*line codeaction.goal:21*/ var p CodeActionParams

	/*line codeaction.goal:22*/
	if !s.decode(raw, &p, "codeAction") {
		/*line codeaction.goal:23*/ return none
	}
	/*line codeaction.goal:25*/ if !wantsKind(p.Context.Only, fixAllKind) {
		/*line codeaction.goal:26*/ return none
	}
	/*line codeaction.goal:28*/ text, version, ok := s.buffer(p.TextDocument.URI)
	/*line codeaction.goal:29*/ if !ok {
		/*line codeaction.goal:30*/ return none
	}
	/*line codeaction.goal:34*/ out, _, _ := fix.File(text)
	/*line codeaction.goal:35*/ if out == text {
		/*line codeaction.goal:36*/ return none
	}
	/*line codeaction.goal:38*/ end := token.OffsetToPosition(text, len(text))
	/*line codeaction.goal:39*/ return []CodeAction{{Title: "Idiomatize file (goal fix)", Kind: fixAllKind, Edit: &WorkspaceEdit{DocumentChanges: []TextDocumentEdit{{TextDocument: versionedTextDocumentIdentifier{URI: p.TextDocument.URI, Version: version}, Edits: []TextEdit{{Range: Range{Start: Position{Line: 0, Character: 0}, End: Position{Line: end.Line - 1, Character: end.Col - 1}}, NewText: out}}}}}}}
}

//line codeaction.goal:58
func wantsKind(only []string, kind string) bool {
	/*line codeaction.goal:59*/ if len(only) == 0 {
		/*line codeaction.goal:60*/ return true
	}
	/*line codeaction.goal:62*/ for _, o := range only {
		/*line codeaction.goal:63*/ if o == kind || strings.HasPrefix(kind, o+".") {
			/*line codeaction.goal:64*/ return true
		}
	}
	/*line codeaction.goal:67*/ return false
}
