// Code generated by goal; DO NOT EDIT.
// generator: goal vdev

package lsp

//line diagnostics.go:4
import (
	"fmt"
	"goal/internal/lexer"
	"goal/internal/project"
	"goal/internal/sema"
	"goal/internal/token"
	"goal/internal/typecheck"
	"path/filepath"
	"sort"
	"strings"
)

//line diagnostics.goal:21
func (s *Server) compile(uri, text string, version int) {
	/*line diagnostics.goal:22*/ path, ok := uriToPath(uri)
	/*line diagnostics.goal:23*/ if !ok {
		/*line diagnostics.goal:24*/ s.compileSingle(uri, text, version)
		/*line diagnostics.goal:25*/ return
	}
	/*line diagnostics.goal:27*/ dir := filepath.Dir(path)
	/*line diagnostics.goal:32*/ s.analysisMu.Lock()
	/*line diagnostics.goal:33*/ defer s.analysisMu.Unlock()
	/*line diagnostics.goal:35*/ disk, err := s.files(dir)
	/*line diagnostics.goal:36*/ if err != nil {
		/*line diagnostics.goal:37*/ s.logf("read dir %s: %v", dir, err)
		/*line diagnostics.goal:38*/ s.compileSingle(uri, text, version)
		/*line diagnostics.goal:39*/ return
	}
	/*line diagnostics.goal:44*/ open := s.openFilesInDir(dir)
	/*line diagnostics.goal:45*/ open[uri] = openFile{uri: uri, path: path, text: text, version: version}
	/*line diagnostics.goal:47*/ views := mergePackageView(disk, open)
	/*line diagnostics.goal:48*/ srcs := make([]string, len(views))
	/*line diagnostics.goal:49*/ for i := range views {
		/*line diagnostics.goal:50*/ srcs[i] = views[i].src
	}
	/*line diagnostics.goal:53*/ if conflictingPackageNames(srcs) {
		/*line diagnostics.goal:54*/ s.logf("package name conflict in %s: single-file fallback", dir)
		/*line diagnostics.goal:55*/ s.compileSingle(uri, text, version)
		/*line diagnostics.goal:56*/ return
	}
	/*line diagnostics.goal:59*/ perFile, ferrs, err := sema.AnalyzePackageInDirWith(srcs, dir, sema.DirResolver(s.resolve))
	/*line diagnostics.goal:60*/ if err != nil {
		/*line diagnostics.goal:62*/ s.logf("analyze package %s: %v", dir, err)
		/*line diagnostics.goal:63*/ return
	}
	/*line diagnostics.goal:65*/ for _, fe := range ferrs {
		/*line diagnostics.goal:66*/ s.logf("foreign resolve %s: %v", dir, fe)
	}
	/*line diagnostics.goal:76*/ depth := s.depthDiags(dir, views)
	/*line diagnostics.goal:77*/ depthByBase := map[string][]typecheck.Diagnostic{}
	/*line diagnostics.goal:78*/ suppress := map[string]bool{}
	/*line diagnostics.goal:79*/ for _, d := range depth {
		/*line diagnostics.goal:80*/ base := filepath.Base(d.Pos.Filename)
		/*line diagnostics.goal:81*/ depthByBase[base] = append(depthByBase[base], d)
		/*line diagnostics.goal:82*/ suppress[dedupKey(base, d.Pos.Line, d.Feature)] = true
	}
	/*line diagnostics.goal:87*/ for i := range views {
		/*line diagnostics.goal:88*/ if o1 := views[i].open; o1 != nil {
			of := *o1
			/*line diagnostics.goal:93*/ if s.superseded(of.uri, of.version) {
				/*line diagnostics.goal:94*/ continue
			}
			/*line diagnostics.goal:96*/ base := filepath.Base(of.path)
			/*line diagnostics.goal:97*/ tokEnd := tokenEnds(of.text)
			/*line diagnostics.goal:98*/ out := make([]Diagnostic, 0, len(perFile[i]))
			/*line diagnostics.goal:99*/ for _, d := range perFile[i] {
				/*line diagnostics.goal:100*/ if suppress[dedupKey(base, d.Pos.Line, d.Feature)] {
					/*line diagnostics.goal:101*/ continue
				}
				/*line diagnostics.goal:103*/ out = append(out, toLSP(of.text, tokEnd, d))
			}
			/*line diagnostics.goal:105*/ for _, d := range depthByBase[base] {
				/*line diagnostics.goal:106*/ out = append(out, depthToLSP(of.text, d))
			}
			/*line diagnostics.goal:108*/ s.publish(of.uri, of.version, out)

		} else {
			/*line diagnostics.goal:90*/ continue

		}
	}
}

//line diagnostics.goal:119
func (s *Server) depthDiags(dir string, views []packageEntry) []typecheck.Diagnostic {
	/*line diagnostics.goal:120*/ name := ""
	/*line diagnostics.goal:121*/ files := make([]project.File, 0, len(views))
	/*line diagnostics.goal:122*/ for i := range views {
		/*line diagnostics.goal:123*/ v := views[i]
		/*line diagnostics.goal:124*/ if clause := project.PackageClause(v.src); clause != "" && name == "" {
			/*line diagnostics.goal:125*/ name = clause
		}
		/*line diagnostics.goal:127*/ files = append(files, project.File{Path: v.path, Name: filepath.Base(v.path), Src: v.src})
	}
	/*line diagnostics.goal:129*/ if name == "" {
		/*line diagnostics.goal:130*/ return nil
	}
	/*line diagnostics.goal:132*/ pkg := &project.Package{Dir: dir, Name: name, Files: files}
	/*line diagnostics.goal:133*/ var tc typecheck.TypeChecker = typecheck.GoTypesChecker{}

	/*line diagnostics.goal:136*/
	ds, cerr := tc.Check(pkg)
	/*line diagnostics.goal:137*/ if cerr != nil {
		/*line diagnostics.goal:138*/ s.logf("depth stage %s: %v", dir, cerr)
		/*line diagnostics.goal:139*/ return nil
	}
	/*line diagnostics.goal:141*/ return ds
}

//line diagnostics.goal:147
func (s *Server) compileSingle(uri, text string, version int) {
	/*line diagnostics.goal:148*/ diags, err := sema.Analyze(text)
	/*line diagnostics.goal:149*/ if err != nil {
		/*line diagnostics.goal:150*/ s.logf("analyze %s: %v", uri, err)
		/*line diagnostics.goal:151*/ return
	}
	/*line diagnostics.goal:153*/ tokEnd := tokenEnds(text)
	/*line diagnostics.goal:154*/ out := make([]Diagnostic, 0, len(diags))
	/*line diagnostics.goal:155*/ for _, d := range diags {
		/*line diagnostics.goal:156*/ out = append(out, toLSP(text, tokEnd, d))
	}
	/*line diagnostics.goal:158*/ if s.superseded(uri, version) {
		/*line diagnostics.goal:159*/ return
	}
	/*line diagnostics.goal:161*/ s.publish(uri, version, out)
}

//line diagnostics.goal:165
type openFile struct {
	uri     string
	path    string
	text    string
	version int
}

//line diagnostics.goal:173
func (s *Server) openFilesInDir(dir string) map[string]openFile {
	/*line diagnostics.goal:174*/ s.mu.Lock()
	/*line diagnostics.goal:175*/ defer s.mu.Unlock()
	/*line diagnostics.goal:176*/ out := map[string]openFile{}
	/*line diagnostics.goal:177*/ for uri, d := range s.docs {
		/*line diagnostics.goal:178*/ p, ok := uriToPath(uri)
		/*line diagnostics.goal:179*/ if !ok || filepath.Dir(p) != dir {
			/*line diagnostics.goal:180*/ continue
		}
		/*line diagnostics.goal:182*/ out[uri] = openFile{uri: uri, path: p, text: d.text, version: d.version}
	}
	/*line diagnostics.goal:184*/ return out
}

//line diagnostics.goal:191
type packageEntry struct {
	path string
	src  string
	open *openFile
}

//line diagnostics.goal:200
func mergePackageView(disk []fileSrc, open map[string]openFile) []packageEntry {
	/*line diagnostics.goal:201*/ byPath := map[string]*packageEntry{}
	/*line diagnostics.goal:202*/ paths := make([]string, 0, len(disk)+len(open))
	/*line diagnostics.goal:203*/ for _, f := range disk {
		/*line diagnostics.goal:204*/ byPath[f.path] = &packageEntry{path: f.path, src: f.src}
		/*line diagnostics.goal:205*/ paths = append(paths, f.path)
	}
	/*line diagnostics.goal:207*/ for _, of := range open {
		/*line diagnostics.goal:208*/ o := of
		/*line diagnostics.goal:209*/ if e, found := byPath[o.path]; found {
			/*line diagnostics.goal:210*/ e.src = o.text
			/*line diagnostics.goal:211*/ e.open = goalSome(o)
			/*line diagnostics.goal:212*/ continue
		}
		/*line diagnostics.goal:214*/ byPath[o.path] = &packageEntry{path: o.path, src: o.text, open: goalSome(o)}
		/*line diagnostics.goal:215*/ paths = append(paths, o.path)
	}
	/*line diagnostics.goal:217*/ sort.Strings(paths)
	/*line diagnostics.goal:218*/ views := make([]packageEntry, len(paths))
	/*line diagnostics.goal:219*/ for i, p := range paths {
		/*line diagnostics.goal:220*/ views[i] = *byPath[p]
	}
	/*line diagnostics.goal:222*/ return views
}

//line diagnostics.goal:228
func conflictingPackageNames(srcs []string) bool {
	/*line diagnostics.goal:229*/ name := ""
	/*line diagnostics.goal:230*/ for _, src := range srcs {
		/*line diagnostics.goal:231*/ got := project.PackageClause(src)
		/*line diagnostics.goal:232*/ if got == "" {
			/*line diagnostics.goal:233*/ continue
		}
		/*line diagnostics.goal:235*/ if name == "" {
			/*line diagnostics.goal:236*/ name = got
			/*line diagnostics.goal:237*/ continue
		}
		/*line diagnostics.goal:239*/ if got != name {
			/*line diagnostics.goal:240*/ return true
		}
	}
	/*line diagnostics.goal:243*/ return false
}

//line diagnostics.goal:248
func (s *Server) superseded(uri string, version int) bool {
	/*line diagnostics.goal:249*/ s.mu.Lock()
	/*line diagnostics.goal:250*/ defer s.mu.Unlock()
	/*line diagnostics.goal:251*/ cur := s.docs[uri]
	/*line diagnostics.goal:252*/ return cur != nil && cur.version > version
}

//line diagnostics.goal:255
func (s *Server) publish(uri string, version int, diags []Diagnostic) {
	/*line diagnostics.goal:256*/ s.notify("textDocument/publishDiagnostics", PublishDiagnosticsParams{URI: uri, Version: version, Diagnostics: diags})
}

//line diagnostics.goal:267
func toLSP(text string, tokEnd map[int]int, d sema.Diagnostic) Diagnostic {
	/*line diagnostics.goal:268*/ start := d.Pos
	/*line diagnostics.goal:269*/ rng := Range{Start: Position{Line: start.Line - 1, Character: utf16Char(text, start.Offset)}, End: Position{Line: start.Line - 1, Character: lineLength(text, start.Line)}}
	/*line diagnostics.goal:273*/ if end, ok := tokEnd[d.Pos.Offset]; ok && end > d.Pos.Offset {
		/*line diagnostics.goal:274*/ e := token.OffsetToPosition(text, end)
		/*line diagnostics.goal:275*/ rng.End = Position{Line: e.Line - 1, Character: utf16Char(text, end)}
	}
	/*line diagnostics.goal:277*/ if rng.End.Line == rng.Start.Line && rng.End.Character <= rng.Start.Character {
		/*line diagnostics.goal:278*/ rng.End.Character = rng.Start.Character + 1
	}
	/*line diagnostics.goal:281*/ severity := 1
	/*line diagnostics.goal:282*/ if _, ok := d.Severity.(sema.Severity_Warning); ok {
		/*line diagnostics.goal:283*/ severity = 2
	}
	/*line diagnostics.goal:285*/ return Diagnostic{Range: rng, Severity: severity, Code: d.Code, Source: "goal", Message: d.Message}
}

//line diagnostics.goal:298
func dedupKey(file string, line int, feature string) string {
	/*line diagnostics.goal:299*/ return fmt.Sprintf("%s:%d:%s", filepath.Base(file), line, feature)
}

//line diagnostics.goal:306
func depthToLSP(text string, d typecheck.Diagnostic) Diagnostic {
	/*line diagnostics.goal:307*/ line := d.Pos.Line
	/*line diagnostics.goal:308*/ if line < 1 {
		/*line diagnostics.goal:309*/ line = 1
	}
	/*line diagnostics.goal:311*/ col := d.Pos.Column
	/*line diagnostics.goal:312*/ if col < 1 {
		/*line diagnostics.goal:313*/ col = 1
	}
	/*line diagnostics.goal:315*/ rng := Range{Start: Position{Line: line - 1, Character: col - 1}, End: Position{Line: line - 1, Character: lineLength(text, line)}}
	/*line diagnostics.goal:319*/ if rng.End.Character <= rng.Start.Character {
		/*line diagnostics.goal:320*/ rng.End.Character = rng.Start.Character + 1
	}
	/*line diagnostics.goal:323*/ severity := 1
	/*line diagnostics.goal:324*/ if _, ok := d.Severity.(sema.Severity_Warning); ok {
		/*line diagnostics.goal:325*/ severity = 2
	}
	/*line diagnostics.goal:327*/ return Diagnostic{Range: rng, Severity: severity, Code: d.Code, Source: "goal", Message: d.Message}
}

//line diagnostics.goal:339
func tokenEnds(text string) map[int]int {
	/*line diagnostics.goal:340*/ toks := lexer.Tokens(text)
	/*line diagnostics.goal:341*/ m := make(map[int]int, len(toks))
	/*line diagnostics.goal:342*/ for _, t := range toks {
		/*line diagnostics.goal:343*/ m[t.Pos.Offset] = t.Pos.Offset + len(t.Lit)
	}
	/*line diagnostics.goal:345*/ return m
}

//line diagnostics.goal:350
func lineLength(src string, line1 int) int {
	/*line diagnostics.goal:351*/ idx := line1 - 1
	/*line diagnostics.goal:352*/ if idx < 0 {
		/*line diagnostics.goal:353*/ return 0
	}
	/*line diagnostics.goal:355*/ lines := strings.Split(src, "\n")
	/*line diagnostics.goal:356*/ if idx >= len(lines) {
		/*line diagnostics.goal:357*/ return 0
	}
	/*line diagnostics.goal:359*/ return utf16Len(strings.TrimRight(lines[idx], "\r"))
}

//line diagnostics.goal:367
func utf16Char(text string, off int) int {
	/*line diagnostics.goal:368*/ if off > len(text) {
		/*line diagnostics.goal:369*/ off = len(text)
	}
	/*line diagnostics.goal:371*/ lineStart := 0
	/*line diagnostics.goal:372*/ for i := 0; i < off; i++ {
		/*line diagnostics.goal:373*/ if text[i] == '\n' {
			/*line diagnostics.goal:374*/ lineStart = i + 1
		}
	}
	/*line diagnostics.goal:377*/ return utf16Len(text[lineStart:off])
}

//line diagnostics.goal:381
func utf16Len(s string) int {
	/*line diagnostics.goal:382*/ n := 0
	/*line diagnostics.goal:383*/ for _, r := range s {
		/*line diagnostics.goal:384*/ if r >= 0x10000 {
			/*line diagnostics.goal:385*/ n += 2
		} else {
			/*line diagnostics.goal:387*/ n++
		}
	}
	/*line diagnostics.goal:390*/ return n
}
