// Code generated by goal; DO NOT EDIT.
// generator: goal vdev

package textedit

//line textedit.go:4
import (
	"sort"
	"strings"
	"unicode"
)

//line textedit.goal:18
type Replacement struct {
	Start, End int
	Text       string
}

//line textedit.goal:29
func Splice(src string, lo, hi int, reps []Replacement) (out string, dropped []Replacement) {
	/*line textedit.goal:30*/ sort.SliceStable(reps, func(a, b int) bool {
		/*line textedit.goal:31*/ if reps[a].Start != reps[b].Start {
			/*line textedit.goal:32*/ return reps[a].Start < reps[b].Start
		}
		/*line textedit.goal:34*/ return reps[a].End < reps[b].End
	})
	/*line textedit.goal:36*/ var b strings.Builder

	/*line textedit.goal:37*/
	prev := lo
	/*line textedit.goal:38*/ for _, r := range reps {
		/*line textedit.goal:39*/ if r.Start < prev {
			/*line textedit.goal:40*/ dropped = append(dropped, r)
			/*line textedit.goal:41*/ continue
		}
		/*line textedit.goal:43*/ b.WriteString(src[prev:r.Start])
		/*line textedit.goal:44*/ b.WriteString(r.Text)
		/*line textedit.goal:45*/ prev = r.End
	}
	/*line textedit.goal:47*/ b.WriteString(src[prev:hi])
	/*line textedit.goal:48*/ return b.String(), dropped
}

//line textedit.goal:54
func IsLineStart(src string, p int) bool {
	/*line textedit.goal:55*/ for k := p - 1; k >= 0; k-- {
		/*line textedit.goal:56*/ switch src[k] {
		case '\n':
			return true
		case ' ', '\t':
			continue
		default:
			return false
		}
	}
	/*line textedit.goal:65*/ return true
}

//line textedit.goal:69
func NextNewline(src string, p int) int {
	/*line textedit.goal:70*/ if nl := strings.IndexByte(src[p:], '\n'); nl >= 0 {
		/*line textedit.goal:71*/ return p + nl
	}
	/*line textedit.goal:73*/ return len(src)
}

//line textedit.goal:78
func LeadIdent(s string) string {
	/*line textedit.goal:79*/ end := 0
	/*line textedit.goal:80*/ for end < len(s) {
		/*line textedit.goal:81*/ r := rune(s[end])
		/*line textedit.goal:82*/ if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' {
			/*line textedit.goal:83*/ end++
			/*line textedit.goal:84*/ continue
		}
		/*line textedit.goal:86*/ break
	}
	/*line textedit.goal:88*/ return s[:end]
}

//line textedit.goal:92
func IsIdent(s string) bool {
	/*line textedit.goal:93*/ if s == "" {
		/*line textedit.goal:94*/ return false
	}
	/*line textedit.goal:96*/ r := []rune(s)[0]
	/*line textedit.goal:97*/ return unicode.IsLetter(r) || r == '_'
}

//line textedit.goal:102
func SplitAssign(s string) (name, rhs string, ok bool) {
	/*line textedit.goal:103*/ if lhs, after, found := strings.Cut(s, ":="); found {
		/*line textedit.goal:104*/ return strings.TrimSpace(lhs), strings.TrimSpace(after), true
	}
	/*line textedit.goal:106*/ return "", strings.TrimSpace(s), false
}

//line textedit.goal:111
func IsStmtKeyword(s string) bool {
	/*line textedit.goal:112*/ switch s {
	case "return", "go", "defer", "if", "else", "for", "switch", "select", "case", "default", "var", "const", "type", "func", "range", "break", "continue", "goto", "fallthrough", "match", "assert", "enum", "import", "package":
		return true
	}
	/*line textedit.goal:118*/ return false
}
