// Code generated by "task generate" from goal source; DO NOT EDIT.

package textedit

//line types.go:4
import "strings"

//line types.goal:7
func BaseType(t string) string {
	t = strings.TrimSpace(strings.TrimPrefix(strings.TrimSpace(t), "*"))
	if i := strings.LastIndexByte(t, '.'); i >= 0 {
		t = t[i+1:]
	}
	return t
}

//line types.goal:21
func ZeroLit(typ string, decls map[string]string, depth int) string {
	typ = strings.TrimSpace(typ)
	switch {
	case strings.HasPrefix(typ, "*"), strings.HasPrefix(typ, "[]"), strings.HasPrefix(typ, "map["), strings.HasPrefix(typ, "chan"), strings.HasPrefix(typ, "func"), strings.HasPrefix(typ, "interface"), typ == "any", typ == "error":
		return "nil"
	case strings.HasPrefix(typ, "["):
		return typ + "{}"
	}
	switch typ {
	case "string":
		return `""`
	case "bool":
		return "false"
	case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "uintptr", "byte", "rune", "float32", "float64", "complex64", "complex128":
		return "0"
	}
	if depth < 8 {
		if under, ok := decls[BaseType(typ)]; ok {
			switch under {
			case "struct":
				return typ + "{}"
			case "interface":
				return "nil"
			default:
				return ZeroLit(under, decls, depth+1)
			}
		}
	}
	return typ + "{}"
}
