// Code generated by "task generate" from goal source; DO NOT EDIT.

package pipeline

//line pipeline.goal:13
type Output struct {
	Go       string
	Test     string
	Warnings []Warning
}

//line pipeline.goal:29
type Warning struct {
	File          string
	Line, Col     int
	Code, Message string
}

//line pipeline.goal:38
type GoFile struct {
	Name string
	Go   string
}

//line pipeline.goal:47
type PackageOutput struct {
	Files    []GoFile
	Tests    []GoFile
	Warnings []Warning
}
