// Code generated by goal; DO NOT EDIT.
// generator: goal vdev

package sema

//line fields.go:4
import (
	"fmt"
	"goal/internal/ast"
)

//line fields.goal:37
func CheckFields(file *ast.File, info *Info) []Diagnostic {
	/*line fields.goal:38*/ decls := buildDeclKinds(file)
	/*line fields.goal:39*/ var diags []Diagnostic

	/*line fields.goal:40*/
	ast.Walk(visitorFunc(func(n ast.Node) bool {
		/*line fields.goal:41*/ switch v1 := n.(type) {
		case *ast.CompositeLit:
			{
				/*line fields.goal:43*/ diags = append(diags, checkStructLit(v1, info, decls)...)
			}
		case *ast.VariantLit:
			{
				/*line fields.goal:46*/ diags = append(diags, checkVariantLit(v1, info, decls)...)
			}
		default:
			{
			}
		}
		/*line fields.goal:50*/ return true
	}), file)
	/*line fields.goal:52*/ return diags
}

//line fields.goal:63
func checkStructLit(lit *ast.CompositeLit, info *Info, decls map[string]string) []Diagnostic {
	/*line fields.goal:64*/ name, ok := identName(lit.Type)
	/*line fields.goal:65*/ if !ok {
		/*line fields.goal:66*/ return nil
	}
	/*line fields.goal:68*/ if litHasSpread(lit) {
		/*line fields.goal:69*/ return nil
	}
	/*line fields.goal:71*/ present := litKeys(lit)
	/*line fields.goal:72*/ fields, known := info.Structs[name]
	/*line fields.goal:73*/ if !known {
		/*line fields.goal:77*/ if len(present) == 0 {
			/*line fields.goal:78*/ return nil
		}
		/*line fields.goal:80*/ return []Diagnostic{{Pos: lit.Pos(), Severity: Severity(Severity_Warning{}), Feature: "08-no-zero-value", Code: "unresolved-literal-type", Message: fmt.Sprintf("cannot verify field completeness of `%s{…}`: type `%s` is not declared in this file — field-completeness deferred", name, name)}}
	}
	/*line fields.goal:94*/ var diags []Diagnostic

	/*line fields.goal:95*/
	for _, f := range fields {
		/*line fields.goal:96*/ if present[f.Name] {
			/*line fields.goal:97*/ continue
		}
		/*line fields.goal:99*/ reason := ZeroSafety(f.Type, decls, info, 0)
		/*line fields.goal:100*/ if reason == "" {
			/*line fields.goal:101*/ continue
		}
		/*line fields.goal:103*/ diags = append(diags, Diagnostic{Pos: lit.Pos(), Severity: Severity(Severity_Error{}), Feature: "08-no-zero-value", Code: "unsafe-zero", Message: fmt.Sprintf("struct literal `%s{…}` omits field `%s` of type `%s`: %s", name, f.Name, f.Type, reason)})
	}
	/*line fields.goal:112*/ return diags
}

//line fields.goal:120
func checkVariantLit(lit *ast.VariantLit, info *Info, decls map[string]string) []Diagnostic {
	/*line fields.goal:121*/ enumName := exprName(lit.Enum)
	/*line fields.goal:122*/ enumDecl := info.Enums[enumName]
	/*line fields.goal:123*/ if enumDecl == nil || lit.Variant == nil {
		/*line fields.goal:124*/ return nil
	}
	/*line fields.goal:126*/ declared, ok := variantFields(enumDecl, lit.Variant.Name)
	/*line fields.goal:127*/ if !ok || len(declared) == 0 {
		/*line fields.goal:128*/ return nil
	}
	/*line fields.goal:130*/ present := labeledArgNames(lit.Args)
	/*line fields.goal:134*/ var diags []Diagnostic

	/*line fields.goal:135*/
	for _, f := range declared {
		/*line fields.goal:136*/ if present[f.Name] {
			/*line fields.goal:137*/ continue
		}
		/*line fields.goal:139*/ reason := ZeroSafety(f.Type, decls, info, 0)
		/*line fields.goal:140*/ if reason == "" {
			/*line fields.goal:141*/ continue
		}
		/*line fields.goal:143*/ diags = append(diags, Diagnostic{Pos: lit.Pos(), Severity: Severity(Severity_Error{}), Feature: "08-no-zero-value", Code: "unsafe-zero", Message: fmt.Sprintf("variant construction `%s.%s(…)` omits field `%s` of type `%s`: %s", enumDecl.Name, lit.Variant.Name, f.Name, f.Type, reason)})
	}
	/*line fields.goal:152*/ return diags
}

//line fields.goal:167
func CheckUnsafeDefaults(file *ast.File, info *Info) []Diagnostic {
	/*line fields.goal:168*/ decls := buildDeclKinds(file)
	/*line fields.goal:169*/ var diags []Diagnostic

	/*line fields.goal:170*/
	ast.Walk(visitorFunc(func(n ast.Node) bool {
		/*line fields.goal:171*/ if lit, ok := n.(*ast.CompositeLit); ok {
			/*line fields.goal:172*/ diags = append(diags, checkUnsafeDefaults(lit, info, decls)...)
		}
		/*line fields.goal:174*/ return true
	}), file)
	/*line fields.goal:176*/ return diags
}

//line fields.goal:185
func checkUnsafeDefaults(lit *ast.CompositeLit, info *Info, decls map[string]string) []Diagnostic {
	/*line fields.goal:186*/ name, ok := identName(lit.Type)
	/*line fields.goal:187*/ if !ok {
		/*line fields.goal:188*/ return nil
	}
	/*line fields.goal:190*/ spread, ok := defaultsSpread(lit)
	/*line fields.goal:191*/ if !ok {
		/*line fields.goal:192*/ return nil
	}
	/*line fields.goal:194*/ fields, known := info.Structs[name]
	/*line fields.goal:195*/ if !known {
		/*line fields.goal:196*/ return nil
	}
	/*line fields.goal:198*/ present := litKeys(lit)
	/*line fields.goal:199*/ var diags []Diagnostic

	/*line fields.goal:200*/
	for _, f := range fields {
		/*line fields.goal:201*/ if present[f.Name] {
			/*line fields.goal:202*/ continue
		}
		/*line fields.goal:204*/ reason := ZeroSafety(f.Type, decls, info, 0)
		/*line fields.goal:205*/ if reason == "" {
			/*line fields.goal:206*/ continue
		}
		/*line fields.goal:208*/ diags = append(diags, Diagnostic{Pos: spread.Pos(), Severity: Severity(Severity_Error{}), Feature: "08-no-zero-value", Code: "unsafe-default", Message: fmt.Sprintf("`...defaults` cannot default field `%s` of type `%s`: %s", f.Name, f.Type, reason)})
	}
	/*line fields.goal:217*/ return diags
}

//line fields.goal:223
func defaultsSpread(lit *ast.CompositeLit) (*ast.SpreadElement, bool) {
	/*line fields.goal:224*/ for _, elt := range lit.Elts {
		/*line fields.goal:225*/ sp, ok := elt.(*ast.SpreadElement)
		/*line fields.goal:226*/ if !ok {
			/*line fields.goal:227*/ continue
		}
		/*line fields.goal:229*/ if id, ok := sp.X.(*ast.Ident); ok && id.Name == "defaults" {
			/*line fields.goal:230*/ return sp, true
		}
	}
	/*line fields.goal:233*/ return nil, false
}

//line fields.goal:241
func buildDeclKinds(file *ast.File) map[string]string {
	/*line fields.goal:242*/ m := map[string]string{}
	/*line fields.goal:243*/ if file == nil {
		/*line fields.goal:244*/ return m
	}
	/*line fields.goal:246*/ for _, d := range file.Decls {
		/*line fields.goal:247*/ gd, ok := d.(*ast.GenDecl)
		/*line fields.goal:248*/ if !ok || gd.Tok.String() != "type" {
			/*line fields.goal:249*/ continue
		}
		/*line fields.goal:251*/ for _, s := range gd.Specs {
			/*line fields.goal:252*/ ts, ok := s.(*ast.TypeSpec)
			/*line fields.goal:253*/ if !ok || ts.Name == nil {
				/*line fields.goal:254*/ continue
			}
			/*line fields.goal:256*/ switch ts.Type.(type) {
			case *ast.StructType:
				{
					/*line fields.goal:258*/ m[ts.Name.Name] = "struct"
				}
			case *ast.InterfaceType:
				{
					/*line fields.goal:261*/ m[ts.Name.Name] = "interface"
				}
			default:
				{
					/*line fields.goal:264*/ m[ts.Name.Name] = typeString(ts.Type)
				}
			}
		}
	}
	/*line fields.goal:269*/ return m
}

//line fields.goal:275
func identName(e ast.Expr) (string, bool) {
	/*line fields.goal:276*/ if id, ok := e.(*ast.Ident); ok {
		/*line fields.goal:277*/ return id.Name, true
	}
	/*line fields.goal:279*/ return "", false
}

//line fields.goal:284
func litKeys(lit *ast.CompositeLit) map[string]bool {
	/*line fields.goal:285*/ present := map[string]bool{}
	/*line fields.goal:286*/ for _, elt := range lit.Elts {
		/*line fields.goal:287*/ kv, ok := elt.(*ast.KeyValueExpr)
		/*line fields.goal:288*/ if !ok {
			/*line fields.goal:289*/ continue
		}
		/*line fields.goal:291*/ if id, ok := kv.Key.(*ast.Ident); ok {
			/*line fields.goal:292*/ present[id.Name] = true
		}
	}
	/*line fields.goal:295*/ return present
}

//line fields.goal:300
func litHasSpread(lit *ast.CompositeLit) bool {
	/*line fields.goal:301*/ for _, elt := range lit.Elts {
		/*line fields.goal:302*/ if _, ok := elt.(*ast.SpreadElement); ok {
			/*line fields.goal:303*/ return true
		}
	}
	/*line fields.goal:306*/ return false
}

//line fields.goal:311
func labeledArgNames(args []ast.Expr) map[string]bool {
	/*line fields.goal:312*/ present := map[string]bool{}
	/*line fields.goal:313*/ for _, a := range args {
		/*line fields.goal:314*/ if la, ok := a.(*ast.LabeledArg); ok && la.Label != nil {
			/*line fields.goal:315*/ present[la.Label.Name] = true
		}
	}
	/*line fields.goal:318*/ return present
}

//line fields.goal:323
func variantFields(enumDecl *Enum, variant string) ([]Field, bool) {
	/*line fields.goal:324*/ for _, v := range enumDecl.Variants {
		/*line fields.goal:325*/ if v.Name == variant {
			/*line fields.goal:326*/ return v.Fields, true
		}
	}
	/*line fields.goal:329*/ return nil, false
}
