// Code generated by "task generate" from goal source; DO NOT EDIT.

package sema

//line zerosafety.go:4
import "strings"

//line zerosafety.goal:20
func ZeroSafety(typ string, decls map[string]string, info *Info, depth int) string {
	typ = strings.TrimSpace(typ)
	switch {
	case strings.HasPrefix(typ, "*"):
		return "a nil pointer has no safe zero — set it explicitly, or use Option[T] for an optional value"
	case strings.HasPrefix(typ, "map["):
		return "a nil map panics on write — set it explicitly (e.g. `" + typ + "{}`)"
	case strings.HasPrefix(typ, "chan"):
		return "a nil channel blocks forever — set it explicitly"
	case strings.HasPrefix(typ, "func"):
		return "a nil func panics when called — set it explicitly"
	case strings.HasPrefix(typ, "interface"):
		if strings.TrimSpace(typ[len("interface"):]) == "{}" {
			return ""
		}
		return "a nil interface has no safe zero — set it explicitly"
	case typ == "any", typ == "error":
		return ""
	case strings.HasPrefix(typ, "[]"):
		return ""
	case strings.HasPrefix(typ, "["):
		return ""
	}
	switch typ {
	case "string", "bool", "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "uintptr", "byte", "rune", "float32", "float64", "complex64", "complex128":
		return ""
	}
	base := zeroBaseType(typ)
	if info != nil && (info.Enums[base] != nil || info.Sealed[base]) {
		return "a sum type has no valid zero variant — set it explicitly"
	}
	if depth < 8 {
		if under, ok := decls[base]; ok {
			switch under {
			case "struct":
				return ""
			case "interface":
				return "a nil interface has no safe zero — set it explicitly"
			default:
				return ZeroSafety(under, decls, info, depth+1)
			}
		}
	}
	return ""
}

//line zerosafety.goal:74
func zeroBaseType(t string) string {
	t = strings.TrimSpace(strings.TrimPrefix(strings.TrimSpace(t), "*"))
	if i := strings.LastIndexByte(t, '.'); i >= 0 {
		t = t[i+1:]
	}
	return t
}
