// Code generated by "task generate" from goal source; DO NOT EDIT.

package lexer

//line lexer.go:4
import (
	"goal/internal/token"
	"unicode"
	"unicode/utf8"
)

//line lexer.goal:26
const eof = -1

//line lexer.goal:30
type Lexer struct {
	src       string
	ch        rune
	offset    int
	rdOffset  int
	line      int
	lineStart int
	errs      []Error
}

//line lexer.goal:44
type Error struct {
	Pos  token.Pos
	Code string
	Msg  string
}

//line lexer.goal:51
func (l *Lexer) errorf(pos token.Pos, code, msg string) {
	l.errs = append(l.errs, Error{Pos: pos, Code: code, Msg: msg})
}

//line lexer.goal:56
func New(src string) *Lexer {
	l := &Lexer{src: src, line: 1}
	l.next()
	return l
}

//line lexer.goal:66
func (l *Lexer) next() {
	if l.ch == '\n' {
		l.line++
		l.lineStart = l.rdOffset
	}
	if l.rdOffset >= len(l.src) {
		l.offset = len(l.src)
		l.ch = eof
		return
	}
	l.offset = l.rdOffset
	r, w := utf8.DecodeRuneInString(l.src[l.rdOffset:])
	l.rdOffset += w
	l.ch = r
}

//line lexer.goal:83
func (l *Lexer) peek() rune {
	if l.rdOffset >= len(l.src) {
		return eof
	}
	r, _ := utf8.DecodeRuneInString(l.src[l.rdOffset:])
	return r
}

//line lexer.goal:94
func (l *Lexer) peek2() rune {
	if l.rdOffset >= len(l.src) {
		return eof
	}
	_, w := utf8.DecodeRuneInString(l.src[l.rdOffset:])
	next := l.rdOffset + w
	if next >= len(l.src) {
		return eof
	}
	r, _ := utf8.DecodeRuneInString(l.src[next:])
	return r
}

//line lexer.goal:108
func (l *Lexer) pos() token.Pos {
	return token.Pos{Offset: l.offset, Line: l.line, Col: l.offset - l.lineStart + 1}
}

//line lexer.goal:114
func Tokens(src string) []token.Token {
	l := New(src)
	var toks []token.Token

	for {
		t := l.Next()
		toks = append(toks, t)
		if t.Kind == token.EOF {
			return toks
		}
	}
}

//line lexer.goal:131
func Scan(src string) ([]token.Token, []Error) {
	l := New(src)
	var toks []token.Token

	for {
		t := l.Next()
		toks = append(toks, t)
		if t.Kind == token.EOF {
			return toks, l.errs
		}
	}
}

//line lexer.goal:145
func (l *Lexer) Next() token.Token {
	l.skipWhitespace()
	pos := l.pos()
	switch ch := l.ch; {
	case ch == eof:
		return token.Token{Kind: token.EOF, Pos: pos}
	case isLetter(ch):
		return l.scanIdentifier(pos)
	case isDigit(ch) || (ch == '.' && isDigit(l.peek())):
		return l.scanNumber(pos)
	case ch == '"':
		return l.scanString(pos)
	case ch == '`':
		return l.scanRawString(pos)
	case ch == '\'':
		return l.scanRune(pos)
	default:
		return l.scanOperator(pos)
	}
}

//line lexer.goal:169
func (l *Lexer) skipWhitespace() {
	for l.ch == ' ' || l.ch == '\t' || l.ch == '\r' || l.ch == '\n' {
		l.next()
	}
}

//line lexer.goal:178
func (l *Lexer) scanIdentifier(pos token.Pos) token.Token {
	start := l.offset
	for isLetter(l.ch) || isDigit(l.ch) {
		l.next()
	}
	lit := l.src[start:l.offset]
	if k, ok := token.Lookup(lit); ok && k.IsKeyword() {
		return token.Token{Kind: k, Lit: lit, Pos: pos}
	}
	return token.Token{Kind: token.IDENT, Lit: lit, Pos: pos}
}

//line lexer.goal:194
func (l *Lexer) scanNumber(pos token.Pos) token.Token {
	start := l.offset
	kind := token.INT
	if l.ch == '0' && (l.peek() == 'x' || l.peek() == 'X') {
		l.next()
		l.next()
		digitStart := l.offset
		l.scanDigits(isHexDigit)
		if l.ch == '.' {
			kind = token.FLOAT
			l.next()
			l.scanDigits(isHexDigit)
		}
		if l.ch == 'p' || l.ch == 'P' {
			kind = token.FLOAT
			l.scanExponent()
		}
		if kind == token.INT && l.offset == digitStart {
			l.errorf(pos, "invalid-number-literal", "hexadecimal literal has no digits")
		}
	} else if l.ch == '0' && (l.peek() == 'o' || l.peek() == 'O' || l.peek() == 'b' || l.peek() == 'B') {
		isBin := l.peek() == 'b' || l.peek() == 'B'
		l.next()
		l.next()
		digitStart := l.offset
		if isBin {
			l.scanDigits(isBinaryDigit)
		} else {
			l.scanDigits(isOctalDigit)
		}
		if l.offset == digitStart || isDigit(l.ch) {
			if isBin {
				l.errorf(pos, "invalid-number-literal", "invalid digit in binary literal")
			} else {
				l.errorf(pos, "invalid-number-literal", "invalid digit in octal literal")
			}
			l.scanDigits(isDigit)
		}
	} else {
		l.scanDigits(isDigit)
		if l.ch == '.' {
			kind = token.FLOAT
			l.next()
			l.scanDigits(isDigit)
		}
		if l.ch == 'e' || l.ch == 'E' {
			kind = token.FLOAT
			l.scanExponent()
		}
	}
	if l.ch == 'i' {
		kind = token.IMAG
		l.next()
	}
	return token.Token{Kind: kind, Lit: l.src[start:l.offset], Pos: pos}
}

//line lexer.goal:259
func (l *Lexer) scanDigits(pred func(rune) bool) {
	for pred(l.ch) || l.ch == '_' {
		l.next()
	}
}

//line lexer.goal:267
func (l *Lexer) scanExponent() {
	l.next()
	if l.ch == '+' || l.ch == '-' {
		l.next()
	}
	l.scanDigits(isDigit)
}

//line lexer.goal:280
func (l *Lexer) scanString(pos token.Pos) token.Token {
	start := l.offset
	l.next()
	terminated := false
	for l.ch != eof && l.ch != '\n' {
		if l.ch == '\\' {
			l.next()
			if l.ch == eof || l.ch == '\n' {
				break
			}
			l.next()
			continue
		}
		if l.ch == '"' {
			l.next()
			terminated = true
			break
		}
		l.next()
	}
	if !terminated {
		l.errorf(pos, "unterminated-string", "unterminated string literal")
	}
	return token.Token{Kind: token.STRING, Lit: l.src[start:l.offset], Pos: pos}
}

//line lexer.goal:311
func (l *Lexer) scanRawString(pos token.Pos) token.Token {
	start := l.offset
	l.next()
	terminated := false
	for l.ch != eof {
		if l.ch == '`' {
			l.next()
			terminated = true
			break
		}
		l.next()
	}
	if !terminated {
		l.errorf(pos, "unterminated-raw-string", "unterminated raw string literal")
	}
	return token.Token{Kind: token.STRING, Lit: l.src[start:l.offset], Pos: pos}
}

//line lexer.goal:333
func (l *Lexer) scanRune(pos token.Pos) token.Token {
	start := l.offset
	l.next()
	terminated := false
	for l.ch != eof && l.ch != '\n' {
		if l.ch == '\\' {
			l.next()
			if l.ch == eof || l.ch == '\n' {
				break
			}
			l.next()
			continue
		}
		if l.ch == '\'' {
			l.next()
			terminated = true
			break
		}
		l.next()
	}
	if !terminated {
		l.errorf(pos, "unterminated-rune", "unterminated rune literal")
	}
	return token.Token{Kind: token.CHAR, Lit: l.src[start:l.offset], Pos: pos}
}

//line lexer.goal:364
func (l *Lexer) scanOperator(pos token.Pos) token.Token {
	ch := l.ch
	switch ch {
	case '/':
		if l.peek() == '/' {
			if l.peek2() == '/' {
				return l.scanDocComment(pos)
			}
			return l.scanLineComment(pos)
		}
		if l.peek() == '*' {
			return l.scanBlockComment(pos)
		}
		return l.op2(pos, token.QUO, '=', token.QUO_ASSIGN)
	case '+':
		l.next()
		switch l.ch {
		case '=':
			l.next()
			return tok(token.ADD_ASSIGN, pos)
		case '+':
			l.next()
			return tok(token.INC, pos)
		}
		return tok(token.ADD, pos)
	case '-':
		l.next()
		switch l.ch {
		case '=':
			l.next()
			return tok(token.SUB_ASSIGN, pos)
		case '-':
			l.next()
			return tok(token.DEC, pos)
		}
		return tok(token.SUB, pos)
	case '*':
		return l.op2(pos, token.MUL, '=', token.MUL_ASSIGN)
	case '%':
		return l.op2(pos, token.REM, '=', token.REM_ASSIGN)
	case '^':
		return l.op2(pos, token.XOR, '=', token.XOR_ASSIGN)
	case '&':
		l.next()
		switch l.ch {
		case '=':
			l.next()
			return tok(token.AND_ASSIGN, pos)
		case '&':
			l.next()
			return tok(token.LAND, pos)
		case '^':
			l.next()
			if l.ch == '=' {
				l.next()
				return tok(token.AND_NOT_ASSIGN, pos)
			}
			return tok(token.AND_NOT, pos)
		}
		return tok(token.AND, pos)
	case '|':
		l.next()
		switch l.ch {
		case '=':
			l.next()
			return tok(token.OR_ASSIGN, pos)
		case '|':
			l.next()
			return tok(token.LOR, pos)
		}
		return tok(token.OR, pos)
	case '<':
		l.next()
		switch l.ch {
		case '=':
			l.next()
			return tok(token.LEQ, pos)
		case '-':
			l.next()
			return tok(token.ARROW, pos)
		case '<':
			l.next()
			if l.ch == '=' {
				l.next()
				return tok(token.SHL_ASSIGN, pos)
			}
			return tok(token.SHL, pos)
		}
		return tok(token.LSS, pos)
	case '>':
		l.next()
		switch l.ch {
		case '=':
			l.next()
			return tok(token.GEQ, pos)
		case '>':
			l.next()
			if l.ch == '=' {
				l.next()
				return tok(token.SHR_ASSIGN, pos)
			}
			return tok(token.SHR, pos)
		}
		return tok(token.GTR, pos)
	case '=':
		l.next()
		switch l.ch {
		case '>':
			l.next()
			return tok(token.FAT_ARROW, pos)
		case '=':
			l.next()
			return tok(token.EQL, pos)
		}
		return tok(token.ASSIGN, pos)
	case '?':
		l.next()
		return tok(token.QUESTION, pos)
	case '!':
		return l.op2(pos, token.NOT, '=', token.NEQ)
	case ':':
		return l.op2(pos, token.COLON, '=', token.DEFINE)
	case '(':
		l.next()
		return tok(token.LPAREN, pos)
	case ')':
		l.next()
		return tok(token.RPAREN, pos)
	case '[':
		l.next()
		return tok(token.LBRACK, pos)
	case ']':
		l.next()
		return tok(token.RBRACK, pos)
	case '{':
		l.next()
		return tok(token.LBRACE, pos)
	case '}':
		l.next()
		return tok(token.RBRACE, pos)
	case ',':
		l.next()
		return tok(token.COMMA, pos)
	case ';':
		l.next()
		return tok(token.SEMICOLON, pos)
	case '.':
		if l.peek() == '.' && l.peek2() == '.' {
			l.next()
			l.next()
			l.next()
			return tok(token.ELLIPSIS, pos)
		}
		l.next()
		return tok(token.PERIOD, pos)
	}
	lit := string(l.ch)
	l.next()
	return token.Token{Kind: token.ILLEGAL, Lit: lit, Pos: pos}
}

//line lexer.goal:538
func (l *Lexer) op2(pos token.Pos, single token.Kind, next2 rune, double token.Kind) token.Token {
	l.next()
	if l.ch == next2 {
		l.next()
		return tok(double, pos)
	}
	return tok(single, pos)
}

//line lexer.goal:548
func (l *Lexer) scanLineComment(pos token.Pos) token.Token {
	start := l.offset
	for l.ch != eof && l.ch != '\n' {
		l.next()
	}
	return token.Token{Kind: token.COMMENT, Lit: l.src[start:l.offset], Pos: pos}
}

//line lexer.goal:559
func (l *Lexer) scanDocComment(pos token.Pos) token.Token {
	start := l.offset
	for l.ch != eof && l.ch != '\n' {
		l.next()
	}
	return token.Token{Kind: token.DOC_COMMENT, Lit: l.src[start:l.offset], Pos: pos}
}

//line lexer.goal:568
func (l *Lexer) scanBlockComment(pos token.Pos) token.Token {
	start := l.offset
	l.next()
	l.next()
	for l.ch != eof {
		if l.ch == '*' && l.peek() == '/' {
			l.next()
			l.next()
			break
		}
		l.next()
	}
	return token.Token{Kind: token.COMMENT, Lit: l.src[start:l.offset], Pos: pos}
}

//line lexer.goal:584
func tok(k token.Kind, pos token.Pos) token.Token {
	return token.Token{Kind: k, Pos: pos}
}

//line lexer.goal:588
func isLetter(ch rune) bool {
	return ch == '_' || unicode.IsLetter(ch)
}

//line lexer.goal:592
func isDigit(ch rune) bool {
	return '0' <= ch && ch <= '9'
}

//line lexer.goal:596
func isHexDigit(ch rune) bool {
	return isDigit(ch) || ('a' <= ch && ch <= 'f') || ('A' <= ch && ch <= 'F')
}

//line lexer.goal:600
func isOctalDigit(ch rune) bool {
	return '0' <= ch && ch <= '7'
}

//line lexer.goal:604
func isBinaryDigit(ch rune) bool {
	return ch == '0' || ch == '1'
}
