// Code generated by "task generate" from goal source; DO NOT EDIT.

package parser

//line goal_decl.go:4
import (
	"goal/internal/ast"
	"goal/internal/token"
)

//line goal_decl.goal:25
func (p *parser) isContextual(word string) bool {
	return p.at(token.IDENT) && p.cur().Lit == word
}

//line goal_decl.goal:31
func (p *parser) parseEnumDecl() *ast.EnumDecl {
	kw := p.expect(token.ENUM)
	d := &ast.EnumDecl{Enum: kw.Pos, Name: p.ident()}
	lb := p.expect(token.LBRACE)
	d.Lbrace = lb.Pos
	for !p.at(token.RBRACE) && !p.at(token.EOF) {
		d.Variants = append(d.Variants, p.parseVariant())
	}
	rb := p.expect(token.RBRACE)
	d.Rbrace = rb.Pos
	return d
}

//line goal_decl.goal:47
func (p *parser) parseVariant() *ast.Variant {
	v := &ast.Variant{Name: p.ident()}
	if p.at(token.LBRACE) {
		lb := p.advance()
		v.Lbrace = lb.Pos
		for !p.at(token.RBRACE) && !p.at(token.EOF) {
			v.Payload = append(v.Payload, p.parsePayloadField())
			if p.at(token.COMMA) {
				p.advance()
			} else {
				break
			}
		}
		rb := p.expect(token.RBRACE)
		v.Rbrace = rb.Pos
	}
	return v
}

//line goal_decl.goal:69
func (p *parser) parsePayloadField() *ast.PayloadField {
	f := &ast.PayloadField{Name: p.ident()}
	if p.at(token.COLON) {
		p.advance()
	}
	f.Type = p.parseType()
	return f
}

//line goal_decl.goal:82
func (p *parser) parseSealedInterfaceDecl() *ast.SealedInterfaceDecl {
	sealed := p.advance()
	d := &ast.SealedInterfaceDecl{Sealed: sealed.Pos}
	d.Interface = p.expect(token.INTERFACE).Pos
	d.Name = p.ident()
	d.Methods = p.parseInterfaceBody()
	return d
}

//line goal_decl.goal:95
func (p *parser) parseImplementsClause() *ast.ImplementsClause {
	if !p.isContextual("implements") {
		return nil
	}
	kw := p.advance()
	return &ast.ImplementsClause{Implements: kw.Pos, Type: p.parseTypeName()}
}
