// Code generated by "task generate" from goal source; DO NOT EDIT.

package backend

//line package.go:4
import (
	"fmt"
	"goal/internal/compiler/ast"
	"goal/internal/compiler/parser"
	"goal/internal/compiler/pipeline"
	"goal/internal/compiler/project"
	"goal/internal/compiler/sema"
	"strings"
)

//line package.goal:36
func TranspilePackage(pkg *project.Package) (pipeline.PackageOutput, error) {
	files := make([]*ast.File, len(pkg.Files))
	for i, f := range pkg.Files {
		parsed, err := parser.ParseFile(f.Src)
		if err != nil {
			return pipeline.PackageOutput{}, fmt.Errorf("%s: parse: %w", f.Name, err)
		}
		files[i] = parsed
	}
	info := sema.ResolvePackage(files)
	enrichForeign(info, files, pkg.Dir)
	var out pipeline.PackageOutput

	var usedOption bool

	for i, f := range pkg.Files {
		goSrc, fileUsedOption, err := emitFileWith(files[i], info, true)
		if err != nil {
			return pipeline.PackageOutput{}, fmt.Errorf("%s: %w", f.Name, err)
		}
		usedOption = usedOption || fileUsedOption
		formatted, err := GoFormatter{}.Format([]byte(goSrc))
		if err != nil {
			return pipeline.PackageOutput{}, fmt.Errorf("%s: generated Go did not parse: %w\n--- generated ---\n%s", f.Name, err, goSrc)
		}
		gen := goName(f.Name)
		mapped := pipeline.AddLineDirectives(f.Src, string(formatted), f.Name, gen)
		out.Files = append(out.Files, pipeline.GoFile{Name: gen, Go: mapped})
		testSrc, testUsedOption, err := emitDoctests(files[i], info, true)
		if err != nil {
			return pipeline.PackageOutput{}, fmt.Errorf("%s: doctests: %w", f.Name, err)
		}
		usedOption = usedOption || testUsedOption
		if testSrc != "" {
			ft, err := GoFormatter{}.Format([]byte(testSrc))
			if err != nil {
				return pipeline.PackageOutput{}, fmt.Errorf("%s: generated test did not parse: %w\n--- generated ---\n%s", f.Name, err, testSrc)
			}
			out.Tests = append(out.Tests, pipeline.GoFile{Name: testName(f.Name), Go: string(ft)})
		}
	}
	if needsResultPrelude(info) {
		preludeGo, err := GoFormatter{}.Format([]byte("package " + pkg.Name + "\n\n" + resultPrelude + "\n"))
		if err != nil {
			return pipeline.PackageOutput{}, fmt.Errorf("prelude: %w", err)
		}
		out.Files = append(out.Files, pipeline.GoFile{Name: "goal_prelude.go", Go: string(preludeGo)})
	}
	if usedOption {
		optionGo, err := GoFormatter{}.Format([]byte("package " + pkg.Name + "\n\n" + optionPrelude + "\n"))
		if err != nil {
			return pipeline.PackageOutput{}, fmt.Errorf("option prelude: %w", err)
		}
		out.Files = append(out.Files, pipeline.GoFile{Name: "goal_options.go", Go: string(optionGo)})
	}
	return out, nil
}

//line package.goal:111
func enrichForeign(info *sema.Info, files []*ast.File, dir string) {
	var imports []*ast.ImportSpec

	for _, f := range files {
		imports = append(imports, f.Imports...)
	}
	sema.EnrichForeign(info, imports, dir, nil)
}

//line package.goal:120
func goName(goalName string) string {
	return strings.TrimSuffix(goalName, project.Ext) + ".go"
}

//line package.goal:125
func testName(goalName string) string {
	return strings.TrimSuffix(goalName, project.Ext) + "_test.go"
}
