// Code generated by "task generate" from goal source; DO NOT EDIT.

package parser

//line parser.go:4
import (
	"errors"
	"fmt"
	"goal/internal/compiler/ast"
	"goal/internal/compiler/lexer"
	"goal/internal/compiler/token"
)

//line parser.goal:42
type parser struct {
	toks    []token.Token
	pos     int
	errs    []error
	exprLev int
	armBody bool
}

//line parser.goal:54
func ParseFile(src string) (*ast.File, error) {
	p := newParser(src)
	file := p.parseFile()
	if len(p.errs) > 0 {
		return file, errors.Join(p.errs...)
	}
	return file, nil
}

//line parser.goal:66
func newParser(src string) *parser {
	all := lexer.Tokens(src)
	toks := make([]token.Token, 0, len(all))
	for _, t := range all {
		if t.Kind == token.COMMENT {
			continue
		}
		toks = append(toks, t)
	}
	if len(toks) == 0 {
		toks = append(toks, token.Token{Kind: token.EOF})
	}
	return &parser{toks: toks}
}

//line parser.goal:85
func (p *parser) cur() token.Token {
	return p.toks[p.pos]
}

//line parser.goal:88
func (p *parser) kind() token.Kind {
	return p.toks[p.pos].Kind
}

//line parser.goal:91
func (p *parser) at(k token.Kind) bool {
	return p.toks[p.pos].Kind == k
}

//line parser.goal:94
func (p *parser) peekKind() token.Kind {
	if p.pos+1 < len(p.toks) {
		return p.toks[p.pos+1].Kind
	}
	return token.EOF
}

//line parser.goal:103
func (p *parser) kindAt(n int) token.Kind {
	if p.pos+n < len(p.toks) {
		return p.toks[p.pos+n].Kind
	}
	return token.EOF
}

//line parser.goal:114
func (p *parser) onNewLine() bool {
	if p.pos == 0 {
		return false
	}
	return p.cur().Pos.Line > p.toks[p.pos-1].Pos.Line
}

//line parser.goal:123
func (p *parser) advance() token.Token {
	t := p.toks[p.pos]
	if p.pos < len(p.toks)-1 {
		p.pos++
	}
	return t
}

//line parser.goal:133
func (p *parser) expect(k token.Kind) token.Token {
	t := p.cur()
	if t.Kind != k {
		p.errorf(t.Pos, "expected %s, found %s", k.String(), describe(t))
	}
	return p.advance()
}

//line parser.goal:142
func (p *parser) errorf(pos token.Pos, format string, args ...any) {
	p.errs = append(p.errs, fmt.Errorf("%s: %s", pos.String(), fmt.Sprintf(format, args...)))
}

//line parser.goal:147
func describe(t token.Token) string {
	switch {
	case t.Kind == token.EOF:
		return "EOF"
	case t.Lit != "":
		return fmt.Sprintf("%q", t.Lit)
	default:
		return t.Kind.String()
	}
}

//line parser.goal:159
func (p *parser) ident() *ast.Ident {
	t := p.expect(token.IDENT)
	return &ast.Ident{NamePos: t.Pos, Name: t.Lit}
}

//line parser.goal:169
func (p *parser) parseFile() *ast.File {
	file := &ast.File{}
	pkg := p.expect(token.PACKAGE)
	file.Package = pkg.Pos
	name := p.expect(token.IDENT)
	file.Name = &ast.Ident{NamePos: name.Pos, Name: name.Lit}
	for !p.at(token.EOF) {
		doc := p.collectDoc()
		if p.at(token.EOF) {
			break
		}
		d := p.parseDecl()
		if d == nil {
			p.errorf(p.cur().Pos, "expected declaration, found %s", describe(p.cur()))
			p.advance()
			continue
		}
		if fd, ok := d.(*ast.FuncDecl); ok && doc != nil {
			fd.Doc = doc
		}
		file.Decls = append(file.Decls, d)
		if gd, ok := d.(*ast.GenDecl); ok && gd.Tok == token.IMPORT {
			for _, s := range gd.Specs {
				if is, ok := s.(*ast.ImportSpec); ok {
					file.Imports = append(file.Imports, is)
				}
			}
		}
	}
	return file
}

//line parser.goal:209
func (p *parser) parseDecl() ast.Decl {
	switch p.kind() {
	case token.IMPORT, token.CONST, token.VAR, token.TYPE:
		return p.parseGenDecl(p.kind())
	case token.FUNC:
		return p.parseFuncDecl()
	case token.ENUM:
		return p.parseEnumDecl()
	default:
		if p.isContextual("sealed") {
			return p.parseSealedInterfaceDecl()
		}
		if p.isContextual("from") && p.peekKind() == token.FUNC {
			return p.parseModFuncDecl(ast.FuncMod(ast.FuncMod_FuncFrom{}))
		}
		if p.isContextual("derive") && p.peekKind() == token.FUNC {
			return p.parseModFuncDecl(ast.FuncMod(ast.FuncMod_FuncDerive{}))
		}
		return nil
	}
}

//line parser.goal:238
func (p *parser) parseGenDecl(tok token.Kind) *ast.GenDecl {
	keyword := p.expect(tok)
	d := &ast.GenDecl{TokPos: keyword.Pos, Tok: tok}
	if p.at(token.LPAREN) {
		p.advance()
		for !p.at(token.RPAREN) && !p.at(token.EOF) {
			d.Specs = append(d.Specs, p.parseSpec(tok))
		}
		p.expect(token.RPAREN)
	} else {
		d.Specs = append(d.Specs, p.parseSpec(tok))
	}
	return d
}

//line parser.goal:255
func (p *parser) parseSpec(tok token.Kind) ast.Spec {
	switch tok {
	case token.IMPORT:
		return p.parseImportSpec()
	case token.TYPE:
		return p.parseTypeSpec()
	default:
		return p.parseValueSpec()
	}
}

//line parser.goal:268
func (p *parser) parseImportSpec() *ast.ImportSpec {
	spec := &ast.ImportSpec{}
	switch p.kind() {
	case token.PERIOD:
		t := p.advance()
		spec.Name = &ast.Ident{NamePos: t.Pos, Name: "."}
	case token.IDENT:
		t := p.advance()
		spec.Name = &ast.Ident{NamePos: t.Pos, Name: t.Lit}
	}
	if p.at(token.STRING) {
		t := p.advance()
		spec.Path = &ast.BasicLit{ValuePos: t.Pos, Kind: token.STRING, Value: t.Lit}
	} else {
		p.errorf(p.cur().Pos, "expected import path, found %s", describe(p.cur()))
		p.advance()
	}
	return spec
}

//line parser.goal:291
func (p *parser) parseTypeSpec() *ast.TypeSpec {
	spec := &ast.TypeSpec{Name: p.ident()}
	if p.atTypeParams() {
		spec.TypeParams = p.parseTypeParams()
	}
	if p.at(token.ASSIGN) {
		spec.Assign = p.advance().Pos
	}
	spec.Type = p.parseType()
	return spec
}

//line parser.goal:308
func (p *parser) atTypeParams() bool {
	if !p.at(token.LBRACK) || p.peekKind() != token.IDENT {
		return false
	}
	k2 := p.kindAt(2)
	return k2 == token.COMMA || startsTypeKind(k2)
}

//line parser.goal:319
func (p *parser) parseTypeParams() *ast.FieldList {
	fl := &ast.FieldList{}
	lb := p.expect(token.LBRACK)
	fl.Opening = lb.Pos
	for !p.at(token.RBRACK) && !p.at(token.EOF) {
		f := &ast.Field{Names: []*ast.Ident{p.ident()}}
		for p.at(token.COMMA) && p.peekKind() == token.IDENT {
			p.advance()
			f.Names = append(f.Names, p.ident())
		}
		f.Type = p.parseType()
		fl.List = append(fl.List, f)
		if p.at(token.COMMA) {
			p.advance()
		} else {
			break
		}
	}
	rb := p.expect(token.RBRACK)
	fl.Closing = rb.Pos
	return fl
}

//line parser.goal:344
func (p *parser) parseValueSpec() *ast.ValueSpec {
	spec := &ast.ValueSpec{Names: p.parseIdentList()}
	if !p.at(token.ASSIGN) && p.startsType() && !p.onNewLine() {
		spec.Type = p.parseType()
	}
	if p.at(token.ASSIGN) {
		p.advance()
		spec.Values = p.parseExprList()
	}
	return spec
}

//line parser.goal:364
func (p *parser) parseFuncDecl() *ast.FuncDecl {
	keyword := p.expect(token.FUNC)
	fd := &ast.FuncDecl{Mod: ast.FuncMod(ast.FuncMod_FuncPlain{})}
	ft := &ast.FuncType{Func: keyword.Pos}
	if p.at(token.LPAREN) {
		fd.Recv = p.parseParamList()
	}
	fd.Name = p.ident()
	if fd.Recv == nil && p.atTypeParams() {
		ft.TypeParams = p.parseTypeParams()
	}
	ft.Params = p.parseParamList()
	ft.Results = p.parseResults(ft.Params.Closing)
	fd.Type = ft
	if p.at(token.LBRACE) {
		fd.Body = p.parseBlock()
	}
	return fd
}

//line parser.goal:395
func (p *parser) parseIdentList() []*ast.Ident {
	list := []*ast.Ident{p.ident()}
	for p.at(token.COMMA) {
		p.advance()
		list = append(list, p.ident())
	}
	return list
}

//line parser.goal:405
func (p *parser) parseExprList() []ast.Expr {
	list := []ast.Expr{p.parseExpr()}
	for p.at(token.COMMA) {
		p.advance()
		list = append(list, p.parseExpr())
	}
	return list
}

//line parser.goal:418
func (p *parser) startsType() bool {
	return startsTypeKind(p.kind())
}

//line parser.goal:420
func startsTypeKind(k token.Kind) bool {
	switch k {
	case token.IDENT, token.MUL, token.LBRACK, token.MAP, token.STRUCT, token.INTERFACE, token.FUNC, token.CHAN, token.ARROW, token.LPAREN, token.ELLIPSIS:
		return true
	}
	return false
}

//line parser.goal:431
func (p *parser) parseType() ast.Expr {
	switch p.kind() {
	case token.IDENT:
		return p.parseTypeName()
	case token.MUL:
		star := p.advance()
		return &ast.StarExpr{Star: star.Pos, X: p.parseType()}
	case token.LBRACK:
		return p.parseArrayOrSliceType()
	case token.MAP:
		return p.parseMapType()
	case token.STRUCT:
		return p.parseStructType()
	case token.INTERFACE:
		return p.parseInterfaceType()
	case token.FUNC:
		kw := p.advance()
		ft := p.parseSignature()
		ft.Func = kw.Pos
		return ft
	case token.CHAN, token.ARROW:
		return p.parseChanType()
	case token.LPAREN:
		p.advance()
		t := p.parseType()
		p.expect(token.RPAREN)
		return t
	case token.ELLIPSIS:
		e := p.advance()
		return &ast.Ellipsis{Ellipsis: e.Pos, Elt: p.parseType()}
	default:
		p.errorf(p.cur().Pos, "expected type, found %s", describe(p.cur()))
		t := p.advance()
		return &ast.Ident{NamePos: t.Pos, Name: t.Lit}
	}
}

//line parser.goal:470
func (p *parser) parseTypeName() ast.Expr {
	return p.typeNameFrom(p.ident())
}

//line parser.goal:476
func (p *parser) typeNameFrom(id *ast.Ident) ast.Expr {
	var x ast.Expr = id

	if p.at(token.PERIOD) {
		p.advance()
		x = &ast.SelectorExpr{X: id, Sel: p.ident()}
	}
	if p.at(token.LBRACK) {
		x = p.parseIndexSuffix(x)
	}
	return x
}

//line parser.goal:489
func (p *parser) parseArrayOrSliceType() ast.Expr {
	lb := p.expect(token.LBRACK)
	arr := &ast.ArrayType{Lbrack: lb.Pos}
	if p.at(token.ELLIPSIS) {
		e := p.advance()
		arr.Len = &ast.Ellipsis{Ellipsis: e.Pos}
	} else if !p.at(token.RBRACK) {
		arr.Len = p.parseExpr()
	}
	p.expect(token.RBRACK)
	arr.Elt = p.parseType()
	return arr
}

//line parser.goal:504
func (p *parser) parseMapType() ast.Expr {
	m := p.expect(token.MAP)
	p.expect(token.LBRACK)
	key := p.parseType()
	p.expect(token.RBRACK)
	return &ast.MapType{Map: m.Pos, Key: key, Value: p.parseType()}
}

//line parser.goal:513
func (p *parser) parseChanType() ast.Expr {
	c := &ast.ChanType{Begin: p.cur().Pos, Dir: ast.ChanDir(ast.ChanDir_SendRecv{})}
	if p.at(token.ARROW) {
		p.advance()
		p.expect(token.CHAN)
		c.Dir = ast.ChanDir(ast.ChanDir_RecvOnly{})
	} else {
		p.expect(token.CHAN)
		if p.at(token.ARROW) {
			p.advance()
			c.Dir = ast.ChanDir(ast.ChanDir_SendOnly{})
		}
	}
	c.Value = p.parseType()
	return c
}

//line parser.goal:533
func (p *parser) parseStructType() ast.Expr {
	kw := p.expect(token.STRUCT)
	st := &ast.StructType{Struct: kw.Pos}
	st.Implements = p.parseImplementsClause()
	fl := &ast.FieldList{}
	lb := p.expect(token.LBRACE)
	fl.Opening = lb.Pos
	for !p.at(token.RBRACE) && !p.at(token.EOF) {
		fl.List = append(fl.List, p.parseField())
	}
	rb := p.expect(token.RBRACE)
	fl.Closing = rb.Pos
	st.Fields = fl
	return st
}

//line parser.goal:551
func (p *parser) parseField() *ast.Field {
	f := &ast.Field{}
	if p.at(token.IDENT) {
		names := []*ast.Ident{p.ident()}
		for p.at(token.COMMA) {
			p.advance()
			names = append(names, p.ident())
		}
		if p.startsType() {
			f.Names = names
			f.Type = p.parseType()
		} else if len(names) == 1 {
			f.Type = p.typeNameFrom(names[0])
		} else {
			f.Names = names
			p.errorf(p.cur().Pos, "expected field type, found %s", describe(p.cur()))
		}
	} else {
		f.Type = p.parseType()
	}
	if p.at(token.STRING) {
		t := p.advance()
		f.Tag = &ast.BasicLit{ValuePos: t.Pos, Kind: token.STRING, Value: t.Lit}
	}
	return f
}

//line parser.goal:580
func (p *parser) parseInterfaceType() ast.Expr {
	kw := p.expect(token.INTERFACE)
	return &ast.InterfaceType{Interface: kw.Pos, Methods: p.parseInterfaceBody()}
}

//line parser.goal:588
func (p *parser) parseInterfaceBody() *ast.FieldList {
	ml := &ast.FieldList{}
	lb := p.expect(token.LBRACE)
	ml.Opening = lb.Pos
	for !p.at(token.RBRACE) && !p.at(token.EOF) {
		ml.List = append(ml.List, p.parseMethodSpec())
	}
	rb := p.expect(token.RBRACE)
	ml.Closing = rb.Pos
	return ml
}

//line parser.goal:602
func (p *parser) parseMethodSpec() *ast.Field {
	f := &ast.Field{}
	name := p.ident()
	if p.at(token.LPAREN) {
		f.Names = []*ast.Ident{name}
		f.Type = p.parseSignature()
	} else {
		f.Type = p.typeNameFrom(name)
	}
	return f
}

//line parser.goal:616
func (p *parser) parseSignature() *ast.FuncType {
	ft := &ast.FuncType{}
	ft.Params = p.parseParamList()
	ft.Results = p.parseResults(ft.Params.Closing)
	return ft
}

//line parser.goal:625
func (p *parser) parseParamList() *ast.FieldList {
	fl := &ast.FieldList{}
	lp := p.expect(token.LPAREN)
	fl.Opening = lp.Pos
	for !p.at(token.RPAREN) && !p.at(token.EOF) {
		fl.List = append(fl.List, p.parseParam())
		if p.at(token.COMMA) {
			p.advance()
		} else {
			break
		}
	}
	rp := p.expect(token.RPAREN)
	fl.Closing = rp.Pos
	return fl
}

//line parser.goal:645
func (p *parser) parseParam() *ast.Field {
	f := &ast.Field{}
	if p.nameThenType() {
		f.Names = []*ast.Ident{p.ident()}
		f.Type = p.parseTypeOrVariadic()
	} else {
		f.Type = p.parseTypeOrVariadic()
	}
	return f
}

//line parser.goal:658
func (p *parser) nameThenType() bool {
	if !p.at(token.IDENT) {
		return false
	}
	switch p.peekKind() {
	case token.COMMA, token.RPAREN, token.PERIOD:
		return false
	}
	return startsTypeKind(p.peekKind())
}

//line parser.goal:670
func (p *parser) parseTypeOrVariadic() ast.Expr {
	if p.at(token.ELLIPSIS) {
		e := p.advance()
		return &ast.Ellipsis{Ellipsis: e.Pos, Elt: p.parseType()}
	}
	return p.parseType()
}

//line parser.goal:685
func (p *parser) parseResults(paramsEnd token.Pos) *ast.FieldList {
	if p.cur().Pos.Line != paramsEnd.Line {
		return nil
	}
	if p.at(token.LPAREN) {
		return p.parseParamList()
	}
	if p.startsType() {
		return &ast.FieldList{List: []*ast.Field{{Type: p.parseType()}}}
	}
	return nil
}

//line parser.goal:708
func (p *parser) parseBlock() *ast.BlockStmt {
	lb := p.expect(token.LBRACE)
	b := &ast.BlockStmt{Lbrace: lb.Pos}
	for !p.at(token.RBRACE) && !p.at(token.EOF) {
		if p.at(token.DOC_COMMENT) {
			p.advance()
			continue
		}
		b.List = append(b.List, p.parseStmt())
	}
	rb := p.expect(token.RBRACE)
	b.Rbrace = rb.Pos
	return b
}

//line parser.goal:726
func (p *parser) parseStmt() ast.Stmt {
	if p.at(token.IDENT) && p.peekKind() == token.COLON {
		return p.parseLabeledStmt()
	}
	switch p.kind() {
	case token.LBRACE:
		return p.parseBlock()
	case token.IF:
		return p.parseIfStmt()
	case token.FOR:
		return p.parseForStmt()
	case token.SWITCH:
		return p.parseSwitchStmt()
	case token.SELECT:
		return p.parseSelectStmt()
	case token.RETURN:
		return p.parseReturnStmt()
	case token.DEFER:
		return p.parseCallStmt(token.DEFER)
	case token.GO:
		return p.parseCallStmt(token.GO)
	case token.BREAK, token.CONTINUE, token.GOTO, token.FALLTHROUGH:
		return p.parseBranchStmt()
	case token.CONST, token.VAR, token.TYPE:
		return &ast.DeclStmt{Decl: p.parseGenDecl(p.kind())}
	case token.SEMICOLON:
		t := p.advance()
		return &ast.EmptyStmt{Semicolon: t.Pos}
	case token.MATCH:
		return &ast.ExprStmt{X: p.parseMatchExpr()}
	case token.ASSERT:
		return p.parseAssertStmt()
	default:
		return p.parseSimpleStmt(false)
	}
}

//line parser.goal:771
func (p *parser) parseSimpleStmt(allowRange bool) ast.Stmt {
	lhs := p.parseExprList()
	switch p.kind() {
	case token.ASSIGN, token.DEFINE, token.ADD_ASSIGN, token.SUB_ASSIGN, token.MUL_ASSIGN, token.QUO_ASSIGN, token.REM_ASSIGN, token.AND_ASSIGN, token.OR_ASSIGN, token.XOR_ASSIGN, token.SHL_ASSIGN, token.SHR_ASSIGN, token.AND_NOT_ASSIGN:
		tok := p.advance()
		if allowRange && p.at(token.RANGE) && (tok.Kind == token.ASSIGN || tok.Kind == token.DEFINE) {
			return p.parseRangeRest(lhs, tok)
		}
		rhs := p.parseExprList()
		return &ast.AssignStmt{Lhs: lhs, TokPos: tok.Pos, Tok: tok.Kind, Rhs: rhs}
	case token.ARROW:
		arrow := p.advance()
		return &ast.SendStmt{Chan: lhs[0], Arrow: arrow.Pos, Value: p.parseExpr()}
	case token.INC, token.DEC:
		tok := p.advance()
		return &ast.IncDecStmt{X: lhs[0], TokPos: tok.Pos, Tok: tok.Kind}
	default:
		if len(lhs) > 1 {
			p.errorf(p.cur().Pos, "expected := or = (multiple expressions in statement), found %s", describe(p.cur()))
		}
		return &ast.ExprStmt{X: lhs[0]}
	}
}

//line parser.goal:800
func (p *parser) parseRangeRest(lhs []ast.Expr, tok token.Token) *ast.RangeStmt {
	p.expect(token.RANGE)
	rs := &ast.RangeStmt{TokPos: tok.Pos, Tok: tok.Kind, X: p.parseExpr()}
	if len(lhs) > 0 {
		rs.Key = lhs[0]
	}
	if len(lhs) > 1 {
		rs.Value = lhs[1]
	}
	return rs
}

//line parser.goal:814
func (p *parser) parseIfStmt() ast.Stmt {
	ifPos := p.expect(token.IF).Pos
	s := &ast.IfStmt{If: ifPos}
	prev := p.exprLev
	p.exprLev = -1
	s1 := p.parseSimpleStmt(false)
	if p.at(token.SEMICOLON) {
		p.advance()
		s.Init = s1
		s.Cond = p.parseExpr()
	} else {
		s.Cond = stmtExpr(s1)
	}
	p.exprLev = prev
	s.Body = p.parseBlock()
	if p.at(token.ELSE) {
		p.advance()
		if p.at(token.IF) {
			s.Else = p.parseIfStmt()
		} else {
			s.Else = p.parseBlock()
		}
	}
	return s
}

//line parser.goal:844
func (p *parser) parseForStmt() ast.Stmt {
	forPos := p.expect(token.FOR).Pos
	if p.at(token.LBRACE) {
		return &ast.ForStmt{For: forPos, Body: p.parseBlock()}
	}
	prev := p.exprLev
	p.exprLev = -1
	if p.at(token.RANGE) {
		p.advance()
		x := p.parseExpr()
		p.exprLev = prev
		return &ast.RangeStmt{For: forPos, X: x, Body: p.parseBlock()}
	}
	var s1 ast.Stmt

	if !p.at(token.SEMICOLON) {
		s1 = p.parseSimpleStmt(true)
		if rs, ok := s1.(*ast.RangeStmt); ok {
			rs.For = forPos
			p.exprLev = prev
			rs.Body = p.parseBlock()
			return rs
		}
	}
	if p.at(token.SEMICOLON) {
		p.advance()
		s := &ast.ForStmt{For: forPos, Init: s1}
		if !p.at(token.SEMICOLON) {
			s.Cond = p.parseExpr()
		}
		p.expect(token.SEMICOLON)
		if !p.at(token.LBRACE) {
			s.Post = p.parseSimpleStmt(false)
		}
		p.exprLev = prev
		s.Body = p.parseBlock()
		return s
	}
	s := &ast.ForStmt{For: forPos, Cond: stmtExpr(s1)}
	p.exprLev = prev
	s.Body = p.parseBlock()
	return s
}

//line parser.goal:898
func (p *parser) parseSwitchStmt() ast.Stmt {
	swPos := p.expect(token.SWITCH).Pos
	prev := p.exprLev
	p.exprLev = -1
	var init, guard ast.Stmt

	if !p.at(token.LBRACE) && !p.at(token.SEMICOLON) {
		guard = p.parseSimpleStmt(false)
	}
	if p.at(token.SEMICOLON) {
		p.advance()
		init = guard
		guard = nil
		if !p.at(token.LBRACE) {
			guard = p.parseSimpleStmt(false)
		}
	}
	p.exprLev = prev
	if isTypeSwitchGuard(guard) {
		ts := &ast.TypeSwitchStmt{Switch: swPos, Init: init, Assign: guard}
		ts.Body = p.parseCaseBody()
		return ts
	}
	return &ast.SwitchStmt{Switch: swPos, Init: init, Tag: stmtExpr(guard), Body: p.parseCaseBody()}
}

//line parser.goal:931
func isTypeSwitchGuard(s ast.Stmt) bool {
	switch v := s.(type) {
	case *ast.ExprStmt:
		{
			ta, ok := v.X.(*ast.TypeAssertExpr)
			return ok && ta.Type == nil
		}
	case *ast.AssignStmt:
		{
			if v.Tok != token.DEFINE || len(v.Rhs) != 1 {
				return false
			}
			ta, ok := v.Rhs[0].(*ast.TypeAssertExpr)
			return ok && ta.Type == nil
		}
	default:
		{
			return false
		}
	}
}

//line parser.goal:952
func (p *parser) parseCaseBody() *ast.BlockStmt {
	lb := p.expect(token.LBRACE)
	body := &ast.BlockStmt{Lbrace: lb.Pos}
	for p.at(token.CASE) || p.at(token.DEFAULT) {
		body.List = append(body.List, p.parseCaseClause())
	}
	body.Rbrace = p.expect(token.RBRACE).Pos
	return body
}

//line parser.goal:964
func (p *parser) parseSelectStmt() ast.Stmt {
	pos := p.expect(token.SELECT).Pos
	lb := p.expect(token.LBRACE)
	body := &ast.BlockStmt{Lbrace: lb.Pos}
	for p.at(token.CASE) || p.at(token.DEFAULT) {
		body.List = append(body.List, p.parseCommClause())
	}
	body.Rbrace = p.expect(token.RBRACE).Pos
	return &ast.SelectStmt{Select: pos, Body: body}
}

//line parser.goal:977
func (p *parser) parseCommClause() ast.Stmt {
	cc := &ast.CommClause{Case: p.cur().Pos}
	if p.at(token.CASE) {
		p.advance()
		cc.Comm = p.parseSimpleStmt(false)
	} else {
		p.expect(token.DEFAULT)
	}
	cc.Colon = p.expect(token.COLON).Pos
	for !p.at(token.CASE) && !p.at(token.DEFAULT) && !p.at(token.RBRACE) && !p.at(token.EOF) {
		if p.at(token.SEMICOLON) {
			p.advance()
			continue
		}
		cc.Body = append(cc.Body, p.parseStmt())
	}
	return cc
}

//line parser.goal:999
func (p *parser) parseLabeledStmt() ast.Stmt {
	label := p.ident()
	colon := p.expect(token.COLON)
	ls := &ast.LabeledStmt{Label: label, Colon: colon.Pos}
	if p.at(token.RBRACE) || p.at(token.EOF) {
		ls.Stmt = &ast.EmptyStmt{Semicolon: colon.Pos}
	} else {
		ls.Stmt = p.parseStmt()
	}
	return ls
}

//line parser.goal:1012
func (p *parser) parseCaseClause() ast.Stmt {
	cc := &ast.CaseClause{Case: p.cur().Pos}
	if p.at(token.CASE) {
		p.advance()
		cc.List = p.parseExprList()
	} else {
		p.expect(token.DEFAULT)
	}
	cc.Colon = p.expect(token.COLON).Pos
	for !p.at(token.CASE) && !p.at(token.DEFAULT) && !p.at(token.RBRACE) && !p.at(token.EOF) {
		if p.at(token.SEMICOLON) {
			p.advance()
			continue
		}
		cc.Body = append(cc.Body, p.parseStmt())
	}
	return cc
}

//line parser.goal:1032
func (p *parser) parseReturnStmt() ast.Stmt {
	pos := p.expect(token.RETURN).Pos
	r := &ast.ReturnStmt{Return: pos}
	if startsExpr(p.kind()) {
		r.Results = p.parseExprList()
	}
	return r
}

//line parser.goal:1042
func (p *parser) parseCallStmt(tok token.Kind) ast.Stmt {
	pos := p.expect(tok).Pos
	x := p.parseExpr()
	call, ok := x.(*ast.CallExpr)
	if !ok {
		p.errorf(pos, "expected function call after %s", tok.String())
	}
	if tok == token.DEFER {
		return &ast.DeferStmt{Defer: pos, Call: call}
	}
	return &ast.GoStmt{Go: pos, Call: call}
}

//line parser.goal:1056
func (p *parser) parseBranchStmt() ast.Stmt {
	t := p.advance()
	b := &ast.BranchStmt{TokPos: t.Pos, Tok: t.Kind}
	if t.Kind != token.FALLTHROUGH && p.at(token.IDENT) {
		b.Label = p.ident()
	}
	return b
}

//line parser.goal:1067
func stmtExpr(s ast.Stmt) ast.Expr {
	if es, ok := s.(*ast.ExprStmt); ok {
		return es.X
	}
	return nil
}

//line parser.goal:1076
func startsExpr(k token.Kind) bool {
	switch k {
	case token.IDENT, token.INT, token.FLOAT, token.IMAG, token.CHAR, token.STRING, token.LPAREN, token.ADD, token.SUB, token.NOT, token.XOR, token.AND, token.ARROW, token.MUL, token.MATCH, token.LBRACK, token.MAP, token.STRUCT, token.CHAN, token.INTERFACE, token.FUNC:
		return true
	}
	return false
}

//line parser.goal:1102
const lowestBinaryPrec = 1

//line parser.goal:1107
func precedence(k token.Kind) int {
	switch k {
	case token.LOR:
		return 1
	case token.LAND:
		return 2
	case token.EQL, token.NEQ, token.LSS, token.LEQ, token.GTR, token.GEQ:
		return 3
	case token.ADD, token.SUB, token.OR, token.XOR:
		return 4
	case token.MUL, token.QUO, token.REM, token.SHL, token.SHR, token.AND, token.AND_NOT:
		return 5
	}
	return 0
}

//line parser.goal:1125
func (p *parser) parseExpr() ast.Expr {
	return p.parseBinary(lowestBinaryPrec)
}

//line parser.goal:1133
func (p *parser) parseBinary(minPrec int) ast.Expr {
	x := p.parseUnary()
	for {
		opPrec := precedence(p.kind())
		if opPrec < minPrec {
			return x
		}
		if p.armBody && p.onNewLine() {
			return x
		}
		op := p.advance()
		y := p.parseBinary(opPrec + 1)
		x = &ast.BinaryExpr{X: x, OpPos: op.Pos, Op: op.Kind, Y: y}
	}
}

//line parser.goal:1156
func (p *parser) parseUnary() ast.Expr {
	switch p.kind() {
	case token.ADD, token.SUB, token.NOT, token.XOR, token.AND, token.ARROW:
		op := p.advance()
		return &ast.UnaryExpr{OpPos: op.Pos, Op: op.Kind, X: p.parseUnary()}
	case token.MUL:
		star := p.advance()
		return &ast.StarExpr{Star: star.Pos, X: p.parseUnary()}
	default:
		return p.parsePostfix(p.parseOperand())
	}
}

//line parser.goal:1171
func (p *parser) parseOperand() ast.Expr {
	t := p.cur()
	switch t.Kind {
	case token.MATCH:
		return p.parseMatchExpr()
	case token.IDENT:
		p.advance()
		return &ast.Ident{NamePos: t.Pos, Name: t.Lit}
	case token.INT, token.FLOAT, token.IMAG, token.CHAR, token.STRING:
		p.advance()
		return &ast.BasicLit{ValuePos: t.Pos, Kind: t.Kind, Value: t.Lit}
	case token.LPAREN:
		p.advance()
		prev := p.exprLev
		p.exprLev++
		inner := p.parseExpr()
		p.exprLev = prev
		rp := p.expect(token.RPAREN)
		return &ast.ParenExpr{Lparen: t.Pos, X: inner, Rparen: rp.Pos}
	case token.LBRACK, token.MAP, token.STRUCT, token.CHAN, token.INTERFACE:
		return p.parseType()
	case token.FUNC:
		return p.parseFuncOperand()
	default:
		p.errorf(t.Pos, "expected expression, found %s", describe(t))
		p.advance()
		return &ast.Ident{NamePos: t.Pos, Name: t.Lit}
	}
}

//line parser.goal:1214
func (p *parser) parseFuncOperand() ast.Expr {
	kw := p.expect(token.FUNC)
	ft := p.parseSignature()
	ft.Func = kw.Pos
	if !p.at(token.LBRACE) {
		return ft
	}
	prev := p.exprLev
	p.exprLev = 0
	body := p.parseBlock()
	p.exprLev = prev
	return &ast.FuncLit{Type: ft, Body: body}
}

//line parser.goal:1231
func (p *parser) parseTypeAssert(x ast.Expr) ast.Expr {
	lp := p.expect(token.LPAREN)
	ta := &ast.TypeAssertExpr{X: x, Lparen: lp.Pos}
	if p.at(token.TYPE) {
		p.advance()
	} else {
		ta.Type = p.parseType()
	}
	ta.Rparen = p.expect(token.RPAREN).Pos
	return ta
}

//line parser.goal:1245
func (p *parser) parsePostfix(x ast.Expr) ast.Expr {
	for {
		switch p.kind() {
		case token.PERIOD:
			p.advance()
			if p.at(token.LPAREN) {
				x = p.parseTypeAssert(x)
			} else {
				x = &ast.SelectorExpr{X: x, Sel: p.ident()}
			}
		case token.LPAREN:
			x = p.parseCallSuffix(x)
		case token.LBRACK:
			x = p.parseIndexSuffix(x)
		case token.QUESTION:
			q := p.advance()
			x = &ast.UnwrapExpr{X: x, Question: q.Pos}
		case token.LBRACE:
			if p.exprLev < 0 || !compositeOK(x) {
				return x
			}
			x = p.parseCompositeLit(x)
		default:
			return x
		}
	}
}

//line parser.goal:1277
func compositeOK(x ast.Expr) bool {
	switch x.(type) {
	case *ast.Ident:
		{
			return true
		}
	case *ast.SelectorExpr:
		{
			return true
		}
	case *ast.IndexExpr:
		{
			return true
		}
	case *ast.IndexListExpr:
		{
			return true
		}
	case *ast.ArrayType:
		{
			return true
		}
	case *ast.MapType:
		{
			return true
		}
	case *ast.StructType:
		{
			return true
		}
	default:
		{
			return false
		}
	}
}

//line parser.goal:1296
func (p *parser) parseCallSuffix(fun ast.Expr) ast.Expr {
	lp := p.expect(token.LPAREN)
	prev := p.exprLev
	p.exprLev++
	var args []ast.Expr

	var ellipsis token.Pos

	labeled := false
	for !p.at(token.RPAREN) && !p.at(token.EOF) {
		arg := p.parseCallArg()
		if _, ok := arg.(*ast.LabeledArg); ok {
			labeled = true
		}
		args = append(args, arg)
		if p.at(token.ELLIPSIS) {
			ellipsis = p.advance().Pos
			if p.at(token.COMMA) {
				p.advance()
			}
			break
		}
		if p.at(token.COMMA) {
			p.advance()
		} else {
			break
		}
	}
	p.exprLev = prev
	rp := p.expect(token.RPAREN)
	if labeled {
		return p.makeVariantLit(fun, lp.Pos, args, rp.Pos)
	}
	return &ast.CallExpr{Fun: fun, Lparen: lp.Pos, Args: args, Ellipsis: ellipsis, Rparen: rp.Pos}
}

//line parser.goal:1338
func (p *parser) parseIndexSuffix(x ast.Expr) ast.Expr {
	lb := p.expect(token.LBRACK)
	prev := p.exprLev
	p.exprLev++
	if p.at(token.COLON) {
		return p.finishSlice(x, lb.Pos, prev, nil)
	}
	first := p.parseExpr()
	if p.at(token.COLON) {
		return p.finishSlice(x, lb.Pos, prev, first)
	}
	indices := []ast.Expr{first}
	for p.at(token.COMMA) {
		p.advance()
		if p.at(token.RBRACK) {
			break
		}
		indices = append(indices, p.parseExpr())
	}
	p.exprLev = prev
	rb := p.expect(token.RBRACK)
	if len(indices) == 1 {
		return &ast.IndexExpr{X: x, Lbrack: lb.Pos, Index: indices[0], Rbrack: rb.Pos}
	}
	return &ast.IndexListExpr{X: x, Lbrack: lb.Pos, Indices: indices, Rbrack: rb.Pos}
}

//line parser.goal:1373
func (p *parser) finishSlice(x ast.Expr, lbrack token.Pos, prevLev int, low ast.Expr) ast.Expr {
	s := &ast.SliceExpr{X: x, Lbrack: lbrack, Low: low}
	p.expect(token.COLON)
	if !p.at(token.RBRACK) && !p.at(token.COLON) {
		s.High = p.parseExpr()
	}
	if p.at(token.COLON) {
		p.advance()
		if !p.at(token.RBRACK) {
			s.Max = p.parseExpr()
		}
	}
	p.exprLev = prevLev
	rb := p.expect(token.RBRACK)
	s.Rbrack = rb.Pos
	return s
}

//line parser.goal:1393
func (p *parser) parseCompositeLit(typ ast.Expr) ast.Expr {
	lb := p.expect(token.LBRACE)
	cl := &ast.CompositeLit{Type: typ, Lbrace: lb.Pos}
	prev := p.exprLev
	p.exprLev++
	for !p.at(token.RBRACE) && !p.at(token.EOF) {
		cl.Elts = append(cl.Elts, p.parseElement())
		if p.at(token.COMMA) {
			p.advance()
		} else {
			break
		}
	}
	p.exprLev = prev
	rb := p.expect(token.RBRACE)
	cl.Rbrace = rb.Pos
	return cl
}

//line parser.goal:1414
func (p *parser) parseElement() ast.Expr {
	if p.at(token.ELLIPSIS) {
		return p.parseSpreadElement()
	}
	x := p.parseElementValue()
	if p.at(token.COLON) {
		colon := p.advance()
		return &ast.KeyValueExpr{Key: x, Colon: colon.Pos, Value: p.parseElementValue()}
	}
	return x
}

//line parser.goal:1428
func (p *parser) parseElementValue() ast.Expr {
	if p.at(token.LBRACE) {
		return p.parseCompositeLit(nil)
	}
	return p.parseExpr()
}
