// Code generated by "task generate" from goal source; DO NOT EDIT.

package backend

//line emit.go:4
import (
	"fmt"
	"goal/internal/ast"
	"goal/internal/pipeline"
	"goal/internal/sema"
	"goal/internal/token"
	"strconv"
	"strings"
)

//line emit.goal:26
type emitter struct {
	b                strings.Builder
	err              error
	info             *sema.Info
	pointerRecv      map[string]bool
	fnKind           roKind
	renames          map[string]string
	armBinding       string
	armFields        map[string]bool
	fileIdents       map[string]bool
	taken            map[string]bool
	okName, errName  string
	closedT, closedE string
	typeDecls        map[string]string
	suppressPrelude  bool
	arity            *arityResolver
	usedOptionHelper bool
	recvTypes        map[string]string
	curParams        map[string]string
	srcFile          string
	warns            []pipeline.Warning
}

//line emit.goal:116
func emitFileWith(f *ast.File, info *sema.Info, suppressPrelude bool, srcFile string) (src string, usedOption bool, warns []pipeline.Warning, err error) {
	/*line emit.goal:117*/ e := emitter{info: info, pointerRecv: pointerReceiverSet(f), fileIdents: fileIdentSet(f), suppressPrelude: suppressPrelude, srcFile: srcFile}
	/*line emit.goal:118*/ e.arity = newArityResolver(f)
	/*line emit.goal:119*/ e.typeDecls = e.buildTypeDecls(f)
	/*line emit.goal:120*/ e.file(f)
	/*line emit.goal:121*/ if e.err != nil {
		/*line emit.goal:122*/ return "", false, nil, e.err
	}
	/*line emit.goal:124*/ return e.b.String(), e.usedOptionHelper, e.warns, nil
}

//line emit.goal:132
func (e *emitter) gensym(want string) string {
	/*line emit.goal:133*/ if e.taken == nil {
		/*line emit.goal:134*/ e.taken = map[string]bool{}
	}
	/*line emit.goal:136*/ name := want
	/*line emit.goal:137*/ for i := 1; e.taken[name]; i++ {
		/*line emit.goal:138*/ name = want + strconv.Itoa(i)
	}
	/*line emit.goal:140*/ e.taken[name] = true
	/*line emit.goal:141*/ return name
}

//line emit.goal:147
func (e *emitter) newScope() map[string]bool {
	/*line emit.goal:148*/ s := make(map[string]bool, len(e.fileIdents))
	/*line emit.goal:149*/ for k := range e.fileIdents {
		/*line emit.goal:150*/ s[k] = true
	}
	/*line emit.goal:152*/ return s
}

//line emit.goal:156
func (e *emitter) fail(format string, args ...any) {
	/*line emit.goal:157*/ if e.err == nil {
		/*line emit.goal:158*/ e.err = fmt.Errorf("backend: "+format, args...)
	}
}

//line emit.goal:162
func (e *emitter) p(s string) {
	/*line emit.goal:163*/ if e.err == nil {
		/*line emit.goal:164*/ e.b.WriteString(s)
	}
}

//line emit.goal:168
func (e *emitter) file(f *ast.File) {
	/*line emit.goal:169*/ if f == nil || f.Name == nil {
		/*line emit.goal:170*/ e.fail("file has no package name")
		/*line emit.goal:171*/ return
	}
	/*line emit.goal:173*/ e.p("package ")
	/*line emit.goal:174*/ e.p(f.Name.Name)
	/*line emit.goal:175*/ e.p("\n\n")
	/*line emit.goal:179*/ if needsFmtImport(f) && !importsPkg(f, "fmt") {
		/*line emit.goal:180*/ e.p("import \"fmt\"\n\n")
	}
	/*line emit.goal:186*/ preludeDone := e.suppressPrelude || !needsResultPrelude(e.info)
	/*line emit.goal:187*/ for _, d := range f.Decls {
		/*line emit.goal:188*/ if !preludeDone && !isImportDecl(d) {
			/*line emit.goal:189*/ e.p(resultPrelude)
			/*line emit.goal:190*/ e.p("\n\n")
			/*line emit.goal:191*/ preludeDone = true
		}
		/*line emit.goal:193*/ e.decl(d)
		/*line emit.goal:194*/ e.p("\n\n")
	}
	/*line emit.goal:196*/ if !preludeDone {
		/*line emit.goal:198*/ e.p(resultPrelude)
		/*line emit.goal:199*/ e.p("\n\n")
	}
	/*line emit.goal:204*/ if !e.suppressPrelude && e.usedOptionHelper {
		/*line emit.goal:205*/ e.p(optionPrelude)
		/*line emit.goal:206*/ e.p("\n\n")
	}
}

//line emit.goal:212
func isImportDecl(d ast.Decl) bool {
	/*line emit.goal:213*/ gd, ok := d.(*ast.GenDecl)
	/*line emit.goal:214*/ return ok && gd.Tok.String() == "import"
}

//line emit.goal:217
func (e *emitter) decl(d ast.Decl) {
	/*line emit.goal:218*/ switch v1 := d.(type) {
	case *ast.GenDecl:
		{
			/*line emit.goal:220*/ e.genDecl(v1)
			/*line emit.goal:224*/ e.implementsMarkers(v1)
		}
	case *ast.FuncDecl:
		{
			/*line emit.goal:227*/ e.funcDecl(v1)
		}
	case *ast.EnumDecl:
		{
			/*line emit.goal:230*/ e.enumDecl(v1)
		}
	case *ast.SealedInterfaceDecl:
		{
			/*line emit.goal:233*/ e.sealedInterfaceDecl(v1)
		}
	default:
		{
			/*line emit.goal:236*/ e.fail("unsupported declaration %T", d)
		}
	}
}

//line emit.goal:245
func (e *emitter) enumDecl(d *ast.EnumDecl) {
	/*line emit.goal:246*/ if d.Name == nil {
		/*line emit.goal:247*/ e.fail("enum declaration has no name")
		/*line emit.goal:248*/ return
	}
	/*line emit.goal:250*/ en := enumOf(e.info, d.Name.Name)
	/*line emit.goal:251*/ if en == nil {
		/*line emit.goal:252*/ e.fail("enum %s not resolved", d.Name.Name)
		/*line emit.goal:253*/ return
	}
	/*line emit.goal:255*/ e.p(genEnum(en))
}

//line emit.goal:263
func (e *emitter) sealedInterfaceDecl(d *ast.SealedInterfaceDecl) {
	/*line emit.goal:264*/ if d.Name == nil {
		/*line emit.goal:265*/ e.fail("sealed interface declaration has no name")
		/*line emit.goal:266*/ return
	}
	/*line emit.goal:268*/ if d.Methods == nil || len(d.Methods.List) == 0 {
		/*line emit.goal:269*/ e.p(genSealedInterface(d.Name.Name))
		/*line emit.goal:270*/ return
	}
	/*line emit.goal:272*/ e.p("type " + d.Name.Name + " interface {\n")
	/*line emit.goal:273*/ for _, m := range d.Methods.List {
		/*line emit.goal:274*/ e.interfaceMethod(m)
		/*line emit.goal:275*/ e.p("\n")
	}
	/*line emit.goal:277*/ e.p("is" + d.Name.Name + "()\n}")
}

//line emit.goal:284
func (e *emitter) implementsMarkers(d *ast.GenDecl) {
	/*line emit.goal:285*/ for _, s := range d.Specs {
		/*line emit.goal:286*/ ts, ok := s.(*ast.TypeSpec)
		/*line emit.goal:287*/ if !ok || ts.Name == nil {
			/*line emit.goal:288*/ continue
		}
		/*line emit.goal:290*/ st, ok := ts.Type.(*ast.StructType)
		/*line emit.goal:291*/ if !ok || st.Implements == nil {
			/*line emit.goal:292*/ continue
		}
		/*line emit.goal:294*/ e.p("\n\n")
		/*line emit.goal:295*/ e.implementsMarker(ts.Name.Name, st.Implements)
	}
}

//line emit.goal:299
func (e *emitter) implementsMarker(typeName string, clause *ast.ImplementsClause) {
	/*line emit.goal:300*/ iface := typeExprName(clause.Type)
	/*line emit.goal:301*/ if iface == "" {
		/*line emit.goal:302*/ e.fail("implements clause on %s has an unsupported interface type %T", typeName, clause.Type)
		/*line emit.goal:303*/ return
	}
	/*line emit.goal:305*/ switch {
	case isSealed(e.info, iface):
		e.p(genMarkerMethod(typeName, iface))
		for _, emb := range sealedEmbeds(e.info, iface) {
			/*line emit.goal:312*/ e.p("\n\n")
			/*line emit.goal:313*/ e.p(genMarkerMethod(typeName, emb))
		}
	case e.pointerRecv[typeName]:
		e.p(fmt.Sprintf("var _ %s = (*%s)(nil)", iface, typeName))
	default:
		e.p(fmt.Sprintf("var _ %s = %s{}", iface, typeName))
	}
}

//line emit.goal:325
func typeExprName(x ast.Expr) string {
	/*line emit.goal:326*/ switch v1 := x.(type) {
	case *ast.Ident:
		{
			/*line emit.goal:328*/ return v1.Name
		}
	case *ast.SelectorExpr:
		{
			/*line emit.goal:331*/ base := typeExprName(v1.X)
			/*line emit.goal:332*/ if base == "" || v1.Sel == nil {
				/*line emit.goal:333*/ return ""
			}
			/*line emit.goal:335*/ return base + "." + v1.Sel.Name
		}
	case *ast.StarExpr:
		{
			/*line emit.goal:338*/ inner := typeExprName(v1.X)
			/*line emit.goal:339*/ if inner == "" {
				/*line emit.goal:340*/ return ""
			}
			/*line emit.goal:342*/ return "*" + inner
		}
	default:
		{
			/*line emit.goal:345*/ return ""
		}
	}
}

//line emit.goal:350
func (e *emitter) genDecl(d *ast.GenDecl) {
	/*line emit.goal:351*/ e.p(d.Tok.String())
	/*line emit.goal:352*/ e.p(" ")
	/*line emit.goal:353*/ multi := len(d.Specs) > 1
	/*line emit.goal:354*/ if multi {
		/*line emit.goal:355*/ e.p("(\n")
	}
	/*line emit.goal:357*/ for _, s := range d.Specs {
		/*line emit.goal:358*/ e.spec(s)
		/*line emit.goal:359*/ e.p("\n")
	}
	/*line emit.goal:361*/ if multi {
		/*line emit.goal:362*/ e.p(")")
	}
}

//line emit.goal:366
func (e *emitter) spec(s ast.Spec) {
	/*line emit.goal:367*/ switch v1 := s.(type) {
	case *ast.ImportSpec:
		{
			/*line emit.goal:369*/ if v1.Name != nil {
				/*line emit.goal:370*/ e.p(v1.Name.Name)
				/*line emit.goal:371*/ e.p(" ")
			}
			/*line emit.goal:373*/ if v1.Path != nil {
				/*line emit.goal:374*/ e.p(v1.Path.Value)
			}
		}
	case *ast.ValueSpec:
		{
			/*line emit.goal:378*/ e.identList(v1.Names)
			/*line emit.goal:379*/ if v1.Type != nil {
				/*line emit.goal:380*/ e.p(" ")
				/*line emit.goal:381*/ e.expr(v1.Type)
			}
			/*line emit.goal:383*/ if len(v1.Values) > 0 {
				/*line emit.goal:384*/ e.p(" = ")
				/*line emit.goal:385*/ e.exprList(v1.Values)
			}
		}
	case *ast.TypeSpec:
		{
			/*line emit.goal:389*/ if v1.Name != nil {
				/*line emit.goal:390*/ e.p(v1.Name.Name)
			}
			/*line emit.goal:392*/ if v1.TypeParams != nil {
				/*line emit.goal:393*/ e.fieldList(v1.TypeParams, "[", "]")
			}
			/*line emit.goal:395*/ e.p(" ")
			/*line emit.goal:396*/ if v1.Assign != (token.Pos{}) {
				/*line emit.goal:397*/ e.p("= ")
			}
			/*line emit.goal:399*/ e.expr(v1.Type)
		}
	default:
		{
			/*line emit.goal:402*/ e.fail("unsupported spec %T", s)
		}
	}
}

//line emit.goal:407
func (e *emitter) funcDecl(d *ast.FuncDecl) {
	/*line emit.goal:414*/ var isDerive bool
	switch d.Mod.(type) {
	case ast.FuncMod_FuncPlain:
		isDerive = false
	case ast.FuncMod_FuncFrom:
		isDerive = false
	case ast.FuncMod_FuncDerive:
		isDerive = true
	default:
		panic("unreachable: non-exhaustive ast.FuncMod (compiler invariant violated)")
	}
	/*line emit.goal:419*/ if isDerive {
		/*line emit.goal:420*/ e.deriveDecl(d)
		/*line emit.goal:421*/ return
	}
	/*line emit.goal:430*/ kind, _ := resultOptionKind(d.Type)
	/*line emit.goal:431*/ var closedT, closedE string

	/*line emit.goal:432*/
	if t, eType, ok := e.closedResultTE(d); ok {
		/*line emit.goal:433*/ kind, closedT, closedE = roResultClosed, t, eType
	}
	/*line emit.goal:435*/ prevKind, prevOk, prevErr, prevTaken := e.fnKind, e.okName, e.errName, e.taken
	/*line emit.goal:436*/ prevClosedT, prevClosedE := e.closedT, e.closedE
	/*line emit.goal:437*/ prevRecvTypes := e.recvTypes
	/*line emit.goal:438*/ prevCurParams := e.curParams
	/*line emit.goal:439*/ e.fnKind, e.taken, e.okName, e.errName = kind, e.newScope(), "", ""
	/*line emit.goal:440*/ e.closedT, e.closedE = closedT, closedE
	/*line emit.goal:441*/ e.recvTypes = e.buildRecvTypes(d)
	/*line emit.goal:442*/ e.curParams = buildCurParams(d)
	/*line emit.goal:443*/ if kind == roResultOpen {
		/*line emit.goal:444*/ e.okName = e.gensym("ok")
		/*line emit.goal:445*/ e.errName = e.gensym("err")
	}
	/*line emit.goal:447*/ defer func() {
		/*line emit.goal:448*/ e.fnKind, e.okName, e.errName, e.taken = prevKind, prevOk, prevErr, prevTaken
		/*line emit.goal:449*/ e.closedT, e.closedE = prevClosedT, prevClosedE
		/*line emit.goal:450*/ e.recvTypes = prevRecvTypes
		/*line emit.goal:451*/ e.curParams = prevCurParams
	}()
	/*line emit.goal:454*/ e.p("func ")
	/*line emit.goal:455*/ if d.Recv != nil {
		/*line emit.goal:456*/ e.fieldList(d.Recv, "(", ")")
		/*line emit.goal:457*/ e.p(" ")
	}
	/*line emit.goal:459*/ if d.Name != nil {
		/*line emit.goal:460*/ e.p(d.Name.Name)
	}
	/*line emit.goal:462*/ e.funcSig(d.Type)
	/*line emit.goal:463*/ if d.Body != nil {
		/*line emit.goal:464*/ e.p(" ")
		/*line emit.goal:465*/ e.block(d.Body)
	}
}

//line emit.goal:474
func (e *emitter) closedResultTE(d *ast.FuncDecl) (t, eType string, ok bool) {
	/*line emit.goal:475*/ if d.Name != nil && e.info != nil && e.info.FuncSignatures != nil {
		/*line emit.goal:476*/ if sig, found := e.info.FuncSignatures[d.Name.Name]; found {
			/*line emit.goal:477*/ var isClosed bool
			switch sig.Mode.(type) {
			case sema.Mode_ModeResultClosed:
				isClosed = true
			case sema.Mode_ModeResult:
				isClosed = false
			case sema.Mode_ModeOption:
				isClosed = false
			case sema.Mode_ModeNone:
				isClosed = false
			default:
				panic("unreachable: non-exhaustive sema.Mode (compiler invariant violated)")
			}
			/*line emit.goal:483*/ if isClosed {
				/*line emit.goal:484*/ return sig.T, sig.E, true
			}
		}
	}
	/*line emit.goal:488*/ il, isList := closedResultType(d.Type)
	/*line emit.goal:489*/ if !isList {
		/*line emit.goal:490*/ return "", "", false
	}
	/*line emit.goal:492*/ return e.exprText(il.Indices[0]), e.exprText(il.Indices[1]), true
}

//line emit.goal:496
func (e *emitter) funcSig(t *ast.FuncType) {
	/*line emit.goal:497*/ if t == nil {
		/*line emit.goal:498*/ e.fail("function has no signature")
		/*line emit.goal:499*/ return
	}
	/*line emit.goal:504*/ if t.TypeParams != nil {
		/*line emit.goal:505*/ e.fieldList(t.TypeParams, "[", "]")
	}
	/*line emit.goal:507*/ e.fieldList(t.Params, "(", ")")
	/*line emit.goal:508*/ if t.Results != nil && len(t.Results.List) > 0 {
		/*line emit.goal:509*/ e.p(" ")
		/*line emit.goal:515*/ if kind, success := resultOptionKind(t); kind == roResultOpen {
			/*line emit.goal:519*/ ok, errn := e.okName, e.errName
			/*line emit.goal:520*/ if ok == "" {
				/*line emit.goal:521*/ ok = "ok"
			}
			/*line emit.goal:523*/ if errn == "" {
				/*line emit.goal:524*/ errn = "err"
			}
			/*line emit.goal:526*/ e.p("(" + ok + " ")
			/*line emit.goal:527*/ e.expr(success)
			/*line emit.goal:528*/ e.p(", " + errn + " error)")
			/*line emit.goal:529*/ return
		}
		/*line emit.goal:534*/ if len(t.Results.List) > 1 || len(t.Results.List[0].Names) > 0 {
			/*line emit.goal:535*/ e.fieldList(t.Results, "(", ")")
		} else {
			/*line emit.goal:537*/ e.expr(t.Results.List[0].Type)
		}
	}
}

//line emit.goal:546
func (e *emitter) fieldList(fl *ast.FieldList, open, close string) {
	/*line emit.goal:547*/ e.p(open)
	/*line emit.goal:548*/ if fl != nil {
		/*line emit.goal:549*/ for i, f := range fl.List {
			/*line emit.goal:550*/ if i > 0 {
				/*line emit.goal:551*/ e.p(", ")
			}
			/*line emit.goal:553*/ e.field(f)
		}
	}
	/*line emit.goal:556*/ e.p(close)
}

//line emit.goal:564
func (e *emitter) structType(x *ast.StructType) {
	/*line emit.goal:565*/ e.p("struct {\n")
	/*line emit.goal:566*/ if x.Fields != nil {
		/*line emit.goal:567*/ for _, f := range x.Fields.List {
			/*line emit.goal:568*/ e.field(f)
			/*line emit.goal:569*/ e.p("\n")
		}
	}
	/*line emit.goal:572*/ e.p("}")
}

//line emit.goal:578
func (e *emitter) interfaceType(x *ast.InterfaceType) {
	/*line emit.goal:579*/ e.p("interface {\n")
	/*line emit.goal:580*/ if x.Methods != nil {
		/*line emit.goal:581*/ for _, m := range x.Methods.List {
			/*line emit.goal:582*/ e.interfaceMethod(m)
			/*line emit.goal:583*/ e.p("\n")
		}
	}
	/*line emit.goal:586*/ e.p("}")
}

//line emit.goal:592
func (e *emitter) interfaceMethod(m *ast.Field) {
	/*line emit.goal:593*/ if len(m.Names) > 0 {
		/*line emit.goal:594*/ e.identList(m.Names)
		/*line emit.goal:595*/ if ft, ok := m.Type.(*ast.FuncType); ok {
			/*line emit.goal:596*/ e.funcSig(ft)
		} else if m.Type != nil {
			/*line emit.goal:598*/ e.p(" ")
			/*line emit.goal:599*/ e.expr(m.Type)
		}
	} else if m.Type != nil {
		/*line emit.goal:602*/ e.expr(m.Type)
	}
}

//line emit.goal:606
func (e *emitter) field(f *ast.Field) {
	/*line emit.goal:607*/ if len(f.Names) > 0 {
		/*line emit.goal:608*/ e.identList(f.Names)
		/*line emit.goal:609*/ e.p(" ")
	}
	/*line emit.goal:611*/ if f.Type != nil {
		/*line emit.goal:612*/ e.expr(f.Type)
	}
	/*line emit.goal:614*/ if f.Tag != nil {
		/*line emit.goal:615*/ e.p(" ")
		/*line emit.goal:616*/ e.p(f.Tag.Value)
	}
}

//line emit.goal:620
func (e *emitter) block(b *ast.BlockStmt) {
	/*line emit.goal:621*/ e.p("{\n")
	/*line emit.goal:622*/ for _, s := range b.List {
		/*line emit.goal:631*/ if e.srcFile != "" && s.Pos().IsValid() {
			/*line emit.goal:632*/ e.p(fmt.Sprintf("/*line %s:%d*/", e.srcFile, s.Pos().Line))
		}
		/*line emit.goal:634*/ e.stmt(s)
		/*line emit.goal:635*/ e.p("\n")
	}
	/*line emit.goal:637*/ e.p("}")
}

//line emit.goal:640
func (e *emitter) stmt(s ast.Stmt) {
	/*line emit.goal:641*/ switch v1 := s.(type) {
	case *ast.BlockStmt:
		{
			/*line emit.goal:643*/ e.block(v1)
		}
	case *ast.ExprStmt:
		{
			/*line emit.goal:649*/ switch v2 := v1.X.(type) {
			case *ast.MatchExpr:
				{
					/*line emit.goal:651*/ e.matchStmt(v2)
				}
			case *ast.UnwrapExpr:
				{
					/*line emit.goal:654*/ e.unwrap("_", v2, true, ":=")
				}
			default:
				{
					/*line emit.goal:657*/ e.expr(v1.X)
				}
			}
		}
	case *ast.AssignStmt:
		{
			/*line emit.goal:666*/ if e.tryAssignMatch(v1) {
				/*line emit.goal:667*/ return
			}
			/*line emit.goal:671*/ if len(v1.Rhs) == 1 {
				/*line emit.goal:672*/ if u, ok := v1.Rhs[0].(*ast.UnwrapExpr); ok {
					/*line emit.goal:679*/ if len(v1.Lhs) != 1 {
						/*line emit.goal:680*/ e.fail("`?` at assignment position binds a single value; a multi-value left-hand side is not supported — assign to one variable")
						/*line emit.goal:681*/ return
					}
					/*line emit.goal:683*/ id, ok := v1.Lhs[0].(*ast.Ident)
					/*line emit.goal:684*/ if !ok {
						/*line emit.goal:685*/ e.fail("`?` can only assign to a simple variable or `_`; assigning through this left-hand side is not supported")
						/*line emit.goal:686*/ return
					}
					/*line emit.goal:688*/ e.unwrap(id.Name, u, id.Name == "_", v1.Tok.String())
					/*line emit.goal:689*/ return
				}
			}
			/*line emit.goal:692*/ e.exprList(v1.Lhs)
			/*line emit.goal:693*/ e.p(" ")
			/*line emit.goal:694*/ e.p(v1.Tok.String())
			/*line emit.goal:695*/ e.p(" ")
			/*line emit.goal:696*/ e.exprList(v1.Rhs)
		}
	case *ast.IncDecStmt:
		{
			/*line emit.goal:699*/ e.expr(v1.X)
			/*line emit.goal:700*/ e.p(v1.Tok.String())
		}
	case *ast.ReturnStmt:
		{
			/*line emit.goal:703*/ e.returnStmt(v1)
		}
	case *ast.IfStmt:
		{
			/*line emit.goal:706*/ e.ifStmt(v1)
		}
	case *ast.ForStmt:
		{
			/*line emit.goal:709*/ e.forStmt(v1)
		}
	case *ast.RangeStmt:
		{
			/*line emit.goal:712*/ e.rangeStmt(v1)
		}
	case *ast.SwitchStmt:
		{
			/*line emit.goal:715*/ e.switchStmt(v1)
		}
	case *ast.TypeSwitchStmt:
		{
			/*line emit.goal:718*/ e.typeSwitchStmt(v1)
		}
	case *ast.SelectStmt:
		{
			/*line emit.goal:721*/ e.selectStmt(v1)
		}
	case *ast.SendStmt:
		{
			/*line emit.goal:724*/ e.expr(v1.Chan)
			/*line emit.goal:725*/ e.p(" <- ")
			/*line emit.goal:726*/ e.expr(v1.Value)
		}
	case *ast.LabeledStmt:
		{
			/*line emit.goal:729*/ e.p(v1.Label.Name)
			/*line emit.goal:730*/ e.p(":\n")
			/*line emit.goal:731*/ e.stmt(v1.Stmt)
		}
	case *ast.DeclStmt:
		{
			/*line emit.goal:736*/ if e.tryVarMatch(v1.Decl) {
				/*line emit.goal:737*/ return
			}
			/*line emit.goal:739*/ e.decl(v1.Decl)
		}
	case *ast.DeferStmt:
		{
			/*line emit.goal:742*/ e.p("defer ")
			/*line emit.goal:743*/ e.expr(v1.Call)
		}
	case *ast.GoStmt:
		{
			/*line emit.goal:746*/ e.p("go ")
			/*line emit.goal:747*/ e.expr(v1.Call)
		}
	case *ast.BranchStmt:
		{
			/*line emit.goal:750*/ e.p(v1.Tok.String())
			/*line emit.goal:751*/ if v1.Label != nil {
				/*line emit.goal:752*/ e.p(" ")
				/*line emit.goal:753*/ e.p(v1.Label.Name)
			}
		}
	case *ast.AssertStmt:
		{
			/*line emit.goal:757*/ e.assertStmt(v1)
		}
	case *ast.EmptyStmt:
		{
		}
	default:
		{
			/*line emit.goal:763*/ e.fail("unsupported statement %T", s)
		}
	}
}

//line emit.goal:774
func (e *emitter) assertStmt(s *ast.AssertStmt) {
	/*line emit.goal:775*/ if s.Cond == nil {
		/*line emit.goal:776*/ e.fail("assert statement has no condition")
		/*line emit.goal:777*/ return
	}
	/*line emit.goal:779*/ condText := e.exprText(s.Cond)
	/*line emit.goal:780*/ e.p("if !(")
	/*line emit.goal:781*/ e.expr(s.Cond)
	/*line emit.goal:782*/ e.p(") { panic(")
	/*line emit.goal:783*/ if s.Msg == nil {
		/*line emit.goal:784*/ e.p(strconv.Quote("assertion failed: " + condText))
	} else {
		/*line emit.goal:786*/ e.p(strconv.Quote("assertion failed: " + condText + ": "))
		/*line emit.goal:787*/ e.p(" + fmt.Sprintf(")
		/*line emit.goal:788*/ e.expr(s.Msg)
		/*line emit.goal:789*/ for _, a := range s.Args {
			/*line emit.goal:790*/ e.p(", ")
			/*line emit.goal:791*/ e.expr(a)
		}
		/*line emit.goal:793*/ e.p(")")
	}
	/*line emit.goal:795*/ e.p(") }")
}

//line emit.goal:798
func (e *emitter) ifStmt(s *ast.IfStmt) {
	/*line emit.goal:799*/ e.p("if ")
	/*line emit.goal:800*/ if s.Init != nil {
		/*line emit.goal:801*/ e.stmt(s.Init)
		/*line emit.goal:802*/ e.p("; ")
	}
	/*line emit.goal:804*/ e.expr(s.Cond)
	/*line emit.goal:805*/ e.p(" ")
	/*line emit.goal:806*/ e.block(s.Body)
	/*line emit.goal:807*/ if s.Else != nil {
		/*line emit.goal:808*/ e.p(" else ")
		/*line emit.goal:809*/ e.stmt(s.Else)
	}
}

//line emit.goal:813
func (e *emitter) forStmt(s *ast.ForStmt) {
	/*line emit.goal:814*/ e.p("for ")
	/*line emit.goal:815*/ if s.Init != nil || s.Post != nil {
		/*line emit.goal:816*/ if s.Init != nil {
			/*line emit.goal:817*/ e.stmt(s.Init)
		}
		/*line emit.goal:819*/ e.p("; ")
		/*line emit.goal:820*/ if s.Cond != nil {
			/*line emit.goal:821*/ e.expr(s.Cond)
		}
		/*line emit.goal:823*/ e.p("; ")
		/*line emit.goal:824*/ if s.Post != nil {
			/*line emit.goal:825*/ e.stmt(s.Post)
		}
		/*line emit.goal:827*/ e.p(" ")
	} else if s.Cond != nil {
		/*line emit.goal:829*/ e.expr(s.Cond)
		/*line emit.goal:830*/ e.p(" ")
	}
	/*line emit.goal:832*/ e.block(s.Body)
}

//line emit.goal:839
func (e *emitter) switchStmt(s *ast.SwitchStmt) {
	/*line emit.goal:840*/ e.p("switch ")
	/*line emit.goal:841*/ if s.Init != nil {
		/*line emit.goal:842*/ e.stmt(s.Init)
		/*line emit.goal:843*/ e.p("; ")
	}
	/*line emit.goal:845*/ if s.Tag != nil {
		/*line emit.goal:846*/ e.expr(s.Tag)
		/*line emit.goal:847*/ e.p(" ")
	}
	/*line emit.goal:849*/ e.p("{\n")
	/*line emit.goal:850*/ if s.Body != nil {
		/*line emit.goal:851*/ for _, c := range s.Body.List {
			/*line emit.goal:852*/ cc, ok := c.(*ast.CaseClause)
			/*line emit.goal:853*/ if !ok {
				/*line emit.goal:854*/ e.fail("unsupported switch body element %T (expected case clause)", c)
				/*line emit.goal:855*/ return
			}
			/*line emit.goal:857*/ e.caseClause(cc)
		}
	}
	/*line emit.goal:860*/ e.p("}")
}

//line emit.goal:866
func (e *emitter) caseClause(c *ast.CaseClause) {
	/*line emit.goal:867*/ if len(c.List) > 0 {
		/*line emit.goal:868*/ e.p("case ")
		/*line emit.goal:869*/ e.exprList(c.List)
		/*line emit.goal:870*/ e.p(":\n")
	} else {
		/*line emit.goal:872*/ e.p("default:\n")
	}
	/*line emit.goal:874*/ for _, s := range c.Body {
		/*line emit.goal:875*/ e.stmt(s)
		/*line emit.goal:876*/ e.p("\n")
	}
}

//line emit.goal:884
func (e *emitter) typeSwitchStmt(s *ast.TypeSwitchStmt) {
	/*line emit.goal:885*/ e.p("switch ")
	/*line emit.goal:886*/ if s.Init != nil {
		/*line emit.goal:887*/ e.stmt(s.Init)
		/*line emit.goal:888*/ e.p("; ")
	}
	/*line emit.goal:890*/ e.stmt(s.Assign)
	/*line emit.goal:891*/ e.p(" {\n")
	/*line emit.goal:892*/ if s.Body != nil {
		/*line emit.goal:893*/ for _, c := range s.Body.List {
			/*line emit.goal:894*/ cc, ok := c.(*ast.CaseClause)
			/*line emit.goal:895*/ if !ok {
				/*line emit.goal:896*/ e.fail("unsupported type-switch body element %T (expected case clause)", c)
				/*line emit.goal:897*/ return
			}
			/*line emit.goal:899*/ e.caseClause(cc)
		}
	}
	/*line emit.goal:902*/ e.p("}")
}

//line emit.goal:906
func (e *emitter) selectStmt(s *ast.SelectStmt) {
	/*line emit.goal:907*/ e.p("select {\n")
	/*line emit.goal:908*/ if s.Body != nil {
		/*line emit.goal:909*/ for _, c := range s.Body.List {
			/*line emit.goal:910*/ cc, ok := c.(*ast.CommClause)
			/*line emit.goal:911*/ if !ok {
				/*line emit.goal:912*/ e.fail("unsupported select body element %T (expected comm clause)", c)
				/*line emit.goal:913*/ return
			}
			/*line emit.goal:915*/ e.commClause(cc)
		}
	}
	/*line emit.goal:918*/ e.p("}")
}

//line emit.goal:923
func (e *emitter) commClause(c *ast.CommClause) {
	/*line emit.goal:924*/ if c.Comm != nil {
		/*line emit.goal:925*/ e.p("case ")
		/*line emit.goal:926*/ e.stmt(c.Comm)
		/*line emit.goal:927*/ e.p(":\n")
	} else {
		/*line emit.goal:929*/ e.p("default:\n")
	}
	/*line emit.goal:931*/ for _, s := range c.Body {
		/*line emit.goal:932*/ e.stmt(s)
		/*line emit.goal:933*/ e.p("\n")
	}
}

//line emit.goal:937
func (e *emitter) rangeStmt(s *ast.RangeStmt) {
	/*line emit.goal:938*/ e.p("for ")
	/*line emit.goal:939*/ if s.Key != nil {
		/*line emit.goal:940*/ e.expr(s.Key)
		/*line emit.goal:941*/ if s.Value != nil {
			/*line emit.goal:942*/ e.p(", ")
			/*line emit.goal:943*/ e.expr(s.Value)
		}
		/*line emit.goal:945*/ e.p(" ")
		/*line emit.goal:946*/ e.p(s.Tok.String())
		/*line emit.goal:947*/ e.p(" ")
	}
	/*line emit.goal:949*/ e.p("range ")
	/*line emit.goal:950*/ e.expr(s.X)
	/*line emit.goal:951*/ e.p(" ")
	/*line emit.goal:952*/ e.block(s.Body)
}

//line emit.goal:955
func (e *emitter) expr(x ast.Expr) {
	/*line emit.goal:960*/ if e.tryOptionValue(x) {
		/*line emit.goal:961*/ return
	}
	/*line emit.goal:963*/ switch v1 := x.(type) {
	case *ast.Ident:
		{
			/*line emit.goal:967*/ if r, ok := e.renames[v1.Name]; ok {
				/*line emit.goal:968*/ e.p(r)
			} else {
				/*line emit.goal:970*/ e.p(v1.Name)
			}
		}
	case *ast.BasicLit:
		{
			/*line emit.goal:974*/ e.p(v1.Value)
		}
	case *ast.ParenExpr:
		{
			/*line emit.goal:977*/ e.p("(")
			/*line emit.goal:978*/ e.expr(v1.X)
			/*line emit.goal:979*/ e.p(")")
		}
	case *ast.UnaryExpr:
		{
			/*line emit.goal:982*/ e.p(v1.Op.String())
			/*line emit.goal:983*/ e.expr(v1.X)
		}
	case *ast.BinaryExpr:
		{
			/*line emit.goal:986*/ e.expr(v1.X)
			/*line emit.goal:987*/ e.p(" ")
			/*line emit.goal:988*/ e.p(v1.Op.String())
			/*line emit.goal:989*/ e.p(" ")
			/*line emit.goal:990*/ e.expr(v1.Y)
		}
	case *ast.SelectorExpr:
		{
			/*line emit.goal:993*/ e.selectorExpr(v1)
		}
	case *ast.VariantLit:
		{
			/*line emit.goal:996*/ e.variantLit(v1)
		}
	case *ast.StarExpr:
		{
			/*line emit.goal:999*/ e.p("*")
			/*line emit.goal:1000*/ e.expr(v1.X)
		}
	case *ast.IndexExpr:
		{
			/*line emit.goal:1003*/ e.indexExpr(v1)
		}
	case *ast.IndexListExpr:
		{
			/*line emit.goal:1006*/ e.expr(v1.X)
			/*line emit.goal:1007*/ e.p("[")
			/*line emit.goal:1008*/ e.exprList(v1.Indices)
			/*line emit.goal:1009*/ e.p("]")
		}
	case *ast.SliceExpr:
		{
			/*line emit.goal:1012*/ e.sliceExpr(v1)
		}
	case *ast.CallExpr:
		{
			/*line emit.goal:1015*/ e.expr(v1.Fun)
			/*line emit.goal:1016*/ e.p("(")
			/*line emit.goal:1017*/ e.exprList(v1.Args)
			/*line emit.goal:1018*/ if v1.Ellipsis.IsValid() {
				/*line emit.goal:1019*/ e.p("...")
			}
			/*line emit.goal:1021*/ e.p(")")
		}
	case *ast.TypeAssertExpr:
		{
			/*line emit.goal:1024*/ e.expr(v1.X)
			/*line emit.goal:1025*/ e.p(".(")
			/*line emit.goal:1026*/ if v1.Type == nil {
				/*line emit.goal:1027*/ e.p("type")
			} else {
				/*line emit.goal:1029*/ e.expr(v1.Type)
			}
			/*line emit.goal:1031*/ e.p(")")
		}
	case *ast.KeyValueExpr:
		{
			/*line emit.goal:1034*/ e.expr(v1.Key)
			/*line emit.goal:1035*/ e.p(": ")
			/*line emit.goal:1036*/ e.expr(v1.Value)
		}
	case *ast.CompositeLit:
		{
			/*line emit.goal:1039*/ e.compositeLit(v1)
		}
	case *ast.FuncLit:
		{
			/*line emit.goal:1050*/ litKind, _ := resultOptionKind(v1.Type)
			/*line emit.goal:1051*/ var litClosedT, litClosedE string

			/*line emit.goal:1052*/
			if il, isList := closedResultType(v1.Type); isList {
				/*line emit.goal:1053*/ litKind, litClosedT, litClosedE = roResultClosed, e.exprText(il.Indices[0]), e.exprText(il.Indices[1])
			}
			/*line emit.goal:1055*/ prevKind, prevOk, prevErr, prevTaken := e.fnKind, e.okName, e.errName, e.taken
			/*line emit.goal:1056*/ prevClosedT, prevClosedE := e.closedT, e.closedE
			/*line emit.goal:1057*/ e.fnKind, e.taken, e.okName, e.errName = litKind, e.newScope(), "", ""
			/*line emit.goal:1058*/ e.closedT, e.closedE = litClosedT, litClosedE
			/*line emit.goal:1059*/ if litKind == roResultOpen {
				/*line emit.goal:1060*/ e.okName = e.gensym("ok")
				/*line emit.goal:1061*/ e.errName = e.gensym("err")
			}
			/*line emit.goal:1063*/ e.p("func")
			/*line emit.goal:1064*/ e.funcSig(v1.Type)
			/*line emit.goal:1065*/ e.p(" ")
			/*line emit.goal:1066*/ e.block(v1.Body)
			/*line emit.goal:1067*/ e.fnKind, e.okName, e.errName, e.taken = prevKind, prevOk, prevErr, prevTaken
			/*line emit.goal:1068*/ e.closedT, e.closedE = prevClosedT, prevClosedE
		}
	case *ast.ArrayType:
		{
			/*line emit.goal:1072*/ e.p("[")
			/*line emit.goal:1073*/ if v1.Len != nil {
				/*line emit.goal:1074*/ e.expr(v1.Len)
			}
			/*line emit.goal:1076*/ e.p("]")
			/*line emit.goal:1077*/ e.expr(v1.Elt)
		}
	case *ast.MapType:
		{
			/*line emit.goal:1080*/ e.p("map[")
			/*line emit.goal:1081*/ e.expr(v1.Key)
			/*line emit.goal:1082*/ e.p("]")
			/*line emit.goal:1083*/ e.expr(v1.Value)
		}
	case *ast.StructType:
		{
			/*line emit.goal:1086*/ e.structType(v1)
		}
	case *ast.InterfaceType:
		{
			/*line emit.goal:1089*/ e.interfaceType(v1)
		}
	case *ast.FuncType:
		{
			/*line emit.goal:1092*/ e.p("func")
			/*line emit.goal:1093*/ e.funcSig(v1)
		}
	case *ast.ChanType:
		{
			/*line emit.goal:1096*/ e.chanType(v1)
		}
	case *ast.Ellipsis:
		{
			/*line emit.goal:1099*/ e.p("...")
			/*line emit.goal:1100*/ if v1.Elt != nil {
				/*line emit.goal:1101*/ e.expr(v1.Elt)
			}
		}
	default:
		{
			/*line emit.goal:1105*/ e.fail("unsupported expression %T", x)
		}
	}
}

//line emit.goal:1115
func (e *emitter) selectorExpr(x *ast.SelectorExpr) {
	/*line emit.goal:1116*/ if key, ok := enumRef(x.X); ok && x.Sel != nil {
		/*line emit.goal:1119*/ if en := enumOf(e.info, key); en != nil && en.VSet[x.Sel.Name] {
			/*line emit.goal:1120*/ e.p(fmt.Sprintf("%s(%s_%s{})", key, key, x.Sel.Name))
			/*line emit.goal:1121*/ return
		}
	}
	/*line emit.goal:1124*/ e.expr(x.X)
	/*line emit.goal:1125*/ e.p(".")
	/*line emit.goal:1126*/ if x.Sel != nil {
		/*line emit.goal:1130*/ if id, ok := x.X.(*ast.Ident); ok && id.Name == e.armBinding && e.armFields[x.Sel.Name] {
			/*line emit.goal:1131*/ e.p(exported(x.Sel.Name))
			/*line emit.goal:1132*/ return
		}
		/*line emit.goal:1134*/ e.p(x.Sel.Name)
	}
}

//line emit.goal:1141
func (e *emitter) variantLit(x *ast.VariantLit) {
	/*line emit.goal:1142*/ key, ok := enumRef(x.Enum)
	/*line emit.goal:1143*/ if !ok || enumOf(e.info, key) == nil {
		/*line emit.goal:1144*/ e.fail("unsupported variant construction (enum not resolved): %T", x.Enum)
		/*line emit.goal:1145*/ return
	}
	/*line emit.goal:1147*/ if x.Variant == nil {
		/*line emit.goal:1148*/ e.fail("variant construction has no variant tag")
		/*line emit.goal:1149*/ return
	}
	/*line emit.goal:1151*/ e.p(fmt.Sprintf("%s(%s_%s{", key, key, x.Variant.Name))
	/*line emit.goal:1152*/ for i, a := range x.Args {
		/*line emit.goal:1153*/ if i > 0 {
			/*line emit.goal:1154*/ e.p(", ")
		}
		/*line emit.goal:1156*/ la, ok := a.(*ast.LabeledArg)
		/*line emit.goal:1157*/ if !ok {
			/*line emit.goal:1158*/ e.fail("unsupported non-labeled variant argument %T", a)
			/*line emit.goal:1159*/ return
		}
		/*line emit.goal:1161*/ if la.Label != nil {
			/*line emit.goal:1162*/ e.p(exported(la.Label.Name))
			/*line emit.goal:1163*/ e.p(": ")
		}
		/*line emit.goal:1165*/ e.expr(la.Value)
	}
	/*line emit.goal:1167*/ e.p("})")
}

//line emit.goal:1175
func (e *emitter) exprText(x ast.Expr) string {
	/*line emit.goal:1176*/ sub := &emitter{info: e.info, pointerRecv: e.pointerRecv, renames: e.renames, armBinding: e.armBinding, armFields: e.armFields, fileIdents: e.fileIdents, typeDecls: e.typeDecls, taken: e.taken}
	/*line emit.goal:1190*/ sub.expr(x)
	/*line emit.goal:1195*/ e.usedOptionHelper = e.usedOptionHelper || sub.usedOptionHelper
	/*line emit.goal:1196*/ if e.err == nil {
		/*line emit.goal:1197*/ e.err = sub.err
	}
	/*line emit.goal:1199*/ return sub.b.String()
}

//line emit.goal:1206
func (e *emitter) buildTypeDecls(f *ast.File) map[string]string {
	/*line emit.goal:1207*/ m := map[string]string{}
	/*line emit.goal:1208*/ if f == nil {
		/*line emit.goal:1209*/ return m
	}
	/*line emit.goal:1211*/ for _, d := range f.Decls {
		/*line emit.goal:1212*/ gd, ok := d.(*ast.GenDecl)
		/*line emit.goal:1213*/ if !ok || gd.Tok.String() != "type" {
			/*line emit.goal:1214*/ continue
		}
		/*line emit.goal:1216*/ for _, s := range gd.Specs {
			/*line emit.goal:1217*/ ts, ok := s.(*ast.TypeSpec)
			/*line emit.goal:1218*/ if !ok || ts.Name == nil {
				/*line emit.goal:1219*/ continue
			}
			/*line emit.goal:1221*/ switch ts.Type.(type) {
			case *ast.StructType:
				{
					/*line emit.goal:1223*/ m[ts.Name.Name] = "struct"
				}
			case *ast.InterfaceType:
				{
					/*line emit.goal:1226*/ m[ts.Name.Name] = "interface"
				}
			default:
				{
					/*line emit.goal:1229*/ m[ts.Name.Name] = e.exprText(ts.Type)
				}
			}
		}
	}
	/*line emit.goal:1234*/ return m
}

//line emit.goal:1242
func (e *emitter) compositeLit(x *ast.CompositeLit) {
	/*line emit.goal:1243*/ if x.Type != nil {
		/*line emit.goal:1244*/ e.expr(x.Type)
	}
	/*line emit.goal:1246*/ e.p("{")
	/*line emit.goal:1247*/ first := true
	/*line emit.goal:1248*/ sep := func() {
		/*line emit.goal:1249*/ if !first {
			/*line emit.goal:1250*/ e.p(", ")
		}
		/*line emit.goal:1252*/ first = false
	}
	/*line emit.goal:1254*/ for _, el := range x.Elts {
		/*line emit.goal:1255*/ if sp, ok := el.(*ast.SpreadElement); ok {
			/*line emit.goal:1256*/ id, ok := sp.X.(*ast.Ident)
			/*line emit.goal:1257*/ if !ok || id.Name != "defaults" {
				/*line emit.goal:1258*/ if isDeriveSpread(sp) {
					/*line emit.goal:1259*/ e.fail("`...derive` at %s is only supported in a return; use a `derive func`", sp.Pos())
				} else {
					/*line emit.goal:1261*/ e.fail("`...defaults` at %s: unsupported spread element (only `...defaults` and a return-position `...derive(src)` are lowered)", sp.Pos())
				}
				/*line emit.goal:1263*/ return
			}
			/*line emit.goal:1265*/ for _, entry := range e.defaultEntries(x, sp.Pos()) {
				/*line emit.goal:1266*/ sep()
				/*line emit.goal:1267*/ e.p(entry)
			}
			/*line emit.goal:1269*/ continue
		}
		/*line emit.goal:1271*/ sep()
		/*line emit.goal:1272*/ e.expr(el)
	}
	/*line emit.goal:1274*/ e.p("}")
}

//line emit.goal:1282
func (e *emitter) defaultEntries(x *ast.CompositeLit, pos token.Pos) []string {
	/*line emit.goal:1283*/ id, ok := x.Type.(*ast.Ident)
	/*line emit.goal:1284*/ if !ok {
		/*line emit.goal:1285*/ e.fail("`...defaults` is not inside a named struct literal")
		/*line emit.goal:1286*/ return nil
	}
	/*line emit.goal:1288*/ fields, ok := structFieldsOf(e.info, id.Name)
	/*line emit.goal:1289*/ if !ok {
		/*line emit.goal:1290*/ e.fail("`...defaults` for unknown struct type %q (no `type %s struct{…}` in this file)", id.Name, id.Name)
		/*line emit.goal:1291*/ return nil
	}
	/*line emit.goal:1293*/ present := presentFieldNames(x.Elts)
	/*line emit.goal:1294*/ var entries []string

	/*line emit.goal:1295*/
	for _, f := range fields {
		/*line emit.goal:1296*/ if present[f.Name] {
			/*line emit.goal:1297*/ continue
		}
		/*line emit.goal:1299*/ if reason := sema.ZeroSafety(f.Type, e.typeDecls, e.info, 0); reason != "" {
			/*line emit.goal:1300*/ e.fail("`...defaults` at %s cannot default field `%s` of type `%s`: %s", pos, f.Name, f.Type, reason)
			/*line emit.goal:1301*/ return nil
		}
		/*line emit.goal:1303*/ entries = append(entries, fmt.Sprintf("%s: %s", f.Name, zeroLit(f.Type, e.typeDecls, 0)))
	}
	/*line emit.goal:1305*/ return entries
}

//line emit.goal:1311
type deriveOverride struct {
	Name  string
	Skip  bool
	Value ast.Expr
}

//line emit.goal:1324
func (e *emitter) deriveDecl(d *ast.FuncDecl) {
	/*line emit.goal:1325*/ if d.Name == nil || d.Type == nil {
		/*line emit.goal:1326*/ e.fail("derive func has no name or signature")
		/*line emit.goal:1327*/ return
	}
	/*line emit.goal:1329*/ if d.Type.Params == nil || len(d.Type.Params.List) == 0 || len(d.Type.Params.List[0].Names) == 0 {
		/*line emit.goal:1331*/ e.fail("derive %s: needs a single named source parameter", d.Name.Name)
		/*line emit.goal:1332*/ return
	}
	/*line emit.goal:1334*/ srcName := d.Type.Params.List[0].Names[0].Name
	/*line emit.goal:1335*/ srcType := typeExprString(d.Type.Params.List[0].Type)
	/*line emit.goal:1336*/ tgtType, fallible, ok := deriveTarget(d.Type.Results)
	/*line emit.goal:1337*/ if !ok {
		/*line emit.goal:1338*/ e.fail("derive %s: cannot determine target type from result list", d.Name.Name)
		/*line emit.goal:1339*/ return
	}
	/*line emit.goal:1341*/ overrides := e.deriveOverrides(d.Body)
	/*line emit.goal:1347*/ prevTaken := e.taken
	/*line emit.goal:1348*/ e.taken = e.newScope()
	/*line emit.goal:1349*/ defer func() {
		/*line emit.goal:1349*/ e.taken = prevTaken
	}()
	/*line emit.goal:1350*/ e.genConversion(d.Name.Name, srcName, srcType, tgtType, fallible, overrides)
}

//line emit.goal:1356
func (e *emitter) deriveOverrides(body *ast.BlockStmt) []deriveOverride {
	/*line emit.goal:1357*/ if body == nil {
		/*line emit.goal:1358*/ return nil
	}
	/*line emit.goal:1360*/ for _, s := range body.List {
		/*line emit.goal:1361*/ ret, ok := s.(*ast.ReturnStmt)
		/*line emit.goal:1362*/ if !ok || len(ret.Results) != 1 {
			/*line emit.goal:1363*/ continue
		}
		/*line emit.goal:1365*/ cl, ok := ret.Results[0].(*ast.CompositeLit)
		/*line emit.goal:1366*/ if !ok {
			/*line emit.goal:1367*/ continue
		}
		/*line emit.goal:1369*/ return overridesFromLit(cl)
	}
	/*line emit.goal:1371*/ return nil
}

//line emit.goal:1378
func overridesFromLit(cl *ast.CompositeLit) []deriveOverride {
	/*line emit.goal:1379*/ var out []deriveOverride

	/*line emit.goal:1380*/
	for _, el := range cl.Elts {
		/*line emit.goal:1381*/ kv, ok := el.(*ast.KeyValueExpr)
		/*line emit.goal:1382*/ if !ok {
			/*line emit.goal:1383*/ continue
		}
		/*line emit.goal:1385*/ key, ok := kv.Key.(*ast.Ident)
		/*line emit.goal:1386*/ if !ok {
			/*line emit.goal:1387*/ continue
		}
		/*line emit.goal:1389*/ if id, ok := kv.Value.(*ast.Ident); ok && id.Name == "_" {
			/*line emit.goal:1390*/ out = append(out, deriveOverride{Name: key.Name, Skip: true})
			/*line emit.goal:1391*/ continue
		}
		/*line emit.goal:1393*/ out = append(out, deriveOverride{Name: key.Name, Value: kv.Value})
	}
	/*line emit.goal:1395*/ return out
}

//line emit.goal:1405
func (e *emitter) genConversion(name, srcName, srcType, tgtType string, fallible bool, overrides []deriveOverride) {
	/*line emit.goal:1406*/ tgtVal := derefType(tgtType)
	/*line emit.goal:1407*/ if _, ok := structFieldsOf(e.info, tgtVal); !ok {
		/*line emit.goal:1408*/ e.fail("derive %s: unknown target struct %q (no `type %s struct{…}` in this file)", name, tgtType, tgtVal)
		/*line emit.goal:1409*/ return
	}
	/*line emit.goal:1413*/ e.p("func " + name + "(" + srcName + " " + srcType + ") ")
	/*line emit.goal:1414*/ if fallible {
		/*line emit.goal:1415*/ e.p("(" + tgtType + ", error)")
	} else {
		/*line emit.goal:1417*/ e.p(tgtType)
	}
	/*line emit.goal:1419*/ e.p(" {\n")
	/*line emit.goal:1420*/ e.emitConversionBody(name, srcName, srcType, tgtType, fallible, overrides, token.Pos{})
	/*line emit.goal:1421*/ e.p("}")
}

//line emit.goal:1431
func (e *emitter) emitConversionBody(name, srcName, srcType, tgtType string, fallible bool, overrides []deriveOverride, pos token.Pos) {
	/*line emit.goal:1432*/ tgtVal := derefType(tgtType)
	/*line emit.goal:1433*/ tgtFields, _ := structFieldsOf(e.info, tgtVal)
	/*line emit.goal:1434*/ srcFields, _ := structFieldsOf(e.info, derefType(srcType))
	/*line emit.goal:1436*/ overridden := map[string]bool{}
	/*line emit.goal:1437*/ for _, o := range overrides {
		/*line emit.goal:1438*/ overridden[o.Name] = true
	}
	/*line emit.goal:1446*/ outVar := e.gensym("out")
	/*line emit.goal:1447*/ retVar := outVar
	/*line emit.goal:1448*/ if strings.HasPrefix(strings.TrimSpace(tgtType), "*") {
		/*line emit.goal:1449*/ retVar = "&" + outVar
	}
	/*line emit.goal:1451*/ returnStmt := "return " + retVar
	/*line emit.goal:1452*/ if fallible {
		/*line emit.goal:1453*/ returnStmt = "return " + retVar + ", nil"
	}
	/*line emit.goal:1456*/ e.p("var " + outVar + " " + tgtVal + "\n")
	/*line emit.goal:1460*/ if strings.HasPrefix(strings.TrimSpace(srcType), "*") {
		/*line emit.goal:1461*/ e.p("if " + srcName + " == nil {\n" + returnStmt + "\n}\n")
	}
	/*line emit.goal:1467*/ errName := ""
	/*line emit.goal:1468*/ if fallible {
		/*line emit.goal:1469*/ errName = e.gensym("err")
	}
	/*line emit.goal:1473*/ for _, o := range overrides {
		/*line emit.goal:1474*/ if o.Skip {
			/*line emit.goal:1475*/ continue
		}
		/*line emit.goal:1477*/ e.p(outVar + "." + o.Name + " = " + e.exprText(o.Value) + "\n")
	}
	/*line emit.goal:1481*/ for _, f := range tgtFields {
		/*line emit.goal:1482*/ if overridden[f.Name] {
			/*line emit.goal:1483*/ continue
		}
		/*line emit.goal:1485*/ sf, found := findSemaField(srcFields, f.Name)
		/*line emit.goal:1486*/ if !found {
			/*line emit.goal:1487*/ if pos.IsValid() {
				/*line emit.goal:1488*/ e.fail("`...derive` at %s cannot fill field `%s` of `%s`: no same-named field on `%s` — add an explicit `%s: …`", pos, f.Name, tgtType, srcType, f.Name)
			} else {
				/*line emit.goal:1490*/ e.fail("derive %s: target field %q of %s is not sourced from %s (add an explicit `%s: …` or a `from func`)", name, f.Name, tgtType, srcType, f.Name)
			}
			/*line emit.goal:1492*/ return
		}
		/*line emit.goal:1496*/ v1, err1 := e.resolveField(outVar+"."+f.Name, srcName+"."+sf.Name, sf.Type, f.Type, fallible, errName, outVar)
		if err1 != nil {
			{
				/*line emit.goal:1503*/ if pos.IsValid() {
					/*line emit.goal:1504*/ e.fail("`...derive` at %s cannot fill field `%s`: %v", pos, f.Name, err1)
				} else {
					/*line emit.goal:1506*/ e.fail("derive %s, field %q: %v", name, f.Name, err1)
				}
				/*line emit.goal:1508*/ return
			}
		} else {
			{
				/*line emit.goal:1498*/ for _, s := range v1 {
					/*line emit.goal:1499*/ e.p(s + "\n")
				}
			}
		}
	}
	/*line emit.goal:1513*/ e.p(returnStmt + "\n")
}

//line emit.goal:1523
func (e *emitter) resolveField(dst, srcExpr, sf, tf string, fallibleOK bool, errName, outVar string) (ok1 []string, err1 error) {
	/*line emit.goal:1524*/ reg := e.info.FromRegistry
	/*line emit.goal:1525*/ sf, tf = strings.TrimSpace(sf), strings.TrimSpace(tf)
	/*line emit.goal:1526*/ if sf == tf {
		/*line emit.goal:1527*/ return []string{fmt.Sprintf("%s = %s", dst, srcExpr)}, nil
	}
	/*line emit.goal:1529*/ if entry, ok := reg[[2]string{sf, tf}]; ok {
		/*line emit.goal:1530*/ if !entry.Fallible {
			/*line emit.goal:1531*/ return []string{fmt.Sprintf("%s = %s(%s)", dst, entry.Name, srcExpr)}, nil
		}
		/*line emit.goal:1533*/ if !fallibleOK {
			/*line emit.goal:1534*/ return ok1, fmt.Errorf("conversion %s->%s is fallible; declare the derive func returning (T, error)", sf, tf)
		}
		/*line emit.goal:1536*/ v := e.gensym("v")
		/*line emit.goal:1537*/ return []string{fmt.Sprintf("%s, %s := %s(%s)", v, errName, entry.Name, srcExpr), fmt.Sprintf("if %s != nil {\nreturn %s, %s\n}", errName, outVar, errName), fmt.Sprintf("%s = %s", dst, v)}, nil
	}
	/*line emit.goal:1546*/ if si, ok := ptrInner(sf); ok {
		/*line emit.goal:1547*/ ti, ok := ptrInner(tf)
		/*line emit.goal:1548*/ if !ok {
			/*line emit.goal:1549*/ return ok1, fmt.Errorf("no conversion %s -> %s in scope", sf, tf)
		}
		/*line emit.goal:1551*/ elem, err1 := elemConv(si, ti, reg)
		if err1 != nil {
			return ok1, err1
		}
		/*line emit.goal:1552*/ v := e.gensym("p")
		/*line emit.goal:1553*/ return []string{fmt.Sprintf("if %s != nil {\n%s := %s\n%s = &%s\n}", srcExpr, v, elem("*"+srcExpr), dst, v)}, nil
	}
	/*line emit.goal:1558*/ if strings.HasPrefix(sf, "[]") && strings.HasPrefix(tf, "[]") {
		/*line emit.goal:1559*/ elem, err1 := elemConv(sf[2:], tf[2:], reg)
		if err1 != nil {
			return ok1, err1
		}
		/*line emit.goal:1560*/ i := e.gensym("i")
		/*line emit.goal:1561*/ return []string{fmt.Sprintf("%s = make(%s, len(%s))", dst, tf, srcExpr), fmt.Sprintf("for %s := range %s {\n%s = %s\n}", i, srcExpr, dst+"["+i+"]", elem(srcExpr+"["+i+"]"))}, nil
	}
	/*line emit.goal:1567*/ if sn, se, ok := arrElem(sf); ok {
		/*line emit.goal:1568*/ tn, te, ok := arrElem(tf)
		/*line emit.goal:1569*/ if !ok || sn != tn {
			/*line emit.goal:1570*/ return ok1, fmt.Errorf("no conversion %s -> %s in scope", sf, tf)
		}
		/*line emit.goal:1572*/ elem, err1 := elemConv(se, te, reg)
		if err1 != nil {
			return ok1, err1
		}
		/*line emit.goal:1573*/ i := e.gensym("i")
		/*line emit.goal:1574*/ return []string{fmt.Sprintf("for %s := range %s {\n%s = %s\n}", i, srcExpr, dst+"["+i+"]", elem(srcExpr+"["+i+"]"))}, nil
	}
	/*line emit.goal:1579*/ if sk, sv, ok := mapKV(sf); ok {
		/*line emit.goal:1580*/ tk, tv, ok := mapKV(tf)
		/*line emit.goal:1581*/ if !ok || sk != tk {
			/*line emit.goal:1582*/ return ok1, fmt.Errorf("no conversion %s -> %s in scope", sf, tf)
		}
		/*line emit.goal:1584*/ elem, err1 := elemConv(sv, tv, reg)
		if err1 != nil {
			return ok1, err1
		}
		/*line emit.goal:1585*/ k, v := e.gensym("k"), e.gensym("v")
		/*line emit.goal:1586*/ return []string{fmt.Sprintf("%s = make(%s, len(%s))", dst, tf, srcExpr), fmt.Sprintf("for %s, %s := range %s {\n%s[%s] = %s\n}", k, v, srcExpr, dst, k, elem(v))}, nil
	}
	/*line emit.goal:1593*/ if _, srcStruct := structFieldsOf(e.info, sf); srcStruct {
		/*line emit.goal:1594*/ if _, tgtStruct := structFieldsOf(e.info, tf); tgtStruct {
			/*line emit.goal:1595*/ v := e.gensym("s")
			/*line emit.goal:1596*/ stmts := []string{fmt.Sprintf("var %s %s", v, tf)}
			/*line emit.goal:1597*/ body, err1 := e.deriveBody(v, srcExpr, sf, tf, fallibleOK, errName, outVar)
			if err1 != nil {
				return ok1, err1
			}
			/*line emit.goal:1598*/ stmts = append(stmts, body...)
			/*line emit.goal:1599*/ return append(stmts, fmt.Sprintf("%s = %s", dst, v)), nil
		}
	}
	/*line emit.goal:1602*/ return ok1, fmt.Errorf("no conversion %s -> %s in scope", sf, tf)
}

//line emit.goal:1609
func (e *emitter) deriveBody(dstVar, srcExpr, srcType, tgtType string, fallible bool, errName, outVar string) (ok1 []string, err1 error) {
	/*line emit.goal:1610*/ tgtFields, ok := structFieldsOf(e.info, tgtType)
	/*line emit.goal:1611*/ if !ok {
		/*line emit.goal:1612*/ return ok1, fmt.Errorf("unknown target struct %q", tgtType)
	}
	/*line emit.goal:1614*/ srcFields, _ := structFieldsOf(e.info, srcType)
	/*line emit.goal:1615*/ var stmts []string

	/*line emit.goal:1616*/
	for _, f := range tgtFields {
		/*line emit.goal:1617*/ sf, found := findSemaField(srcFields, f.Name)
		/*line emit.goal:1618*/ if !found {
			/*line emit.goal:1619*/ return ok1, fmt.Errorf("nested field %q of %s is not sourced from %s", f.Name, tgtType, srcType)
		}
		/*line emit.goal:1623*/ v1, err2 := e.resolveField(dstVar+"."+f.Name, srcExpr+"."+sf.Name, sf.Type, f.Type, fallible, errName, outVar)
		if err2 != nil {
			{
				/*line emit.goal:1625*/ return ok1, fmt.Errorf("nested field %q: %w", f.Name, err2)
			}
		} else {
			{
				/*line emit.goal:1624*/ stmts = append(stmts, v1...)
			}
		}
	}
	/*line emit.goal:1628*/ return stmts, nil
}

//line emit.goal:1635
func (e *emitter) indexExpr(x *ast.IndexExpr) {
	/*line emit.goal:1636*/ if id, ok := x.X.(*ast.Ident); ok && id.Name == "Option" {
		/*line emit.goal:1637*/ e.p("*")
		/*line emit.goal:1638*/ e.expr(x.Index)
		/*line emit.goal:1639*/ return
	}
	/*line emit.goal:1641*/ e.expr(x.X)
	/*line emit.goal:1642*/ e.p("[")
	/*line emit.goal:1643*/ e.expr(x.Index)
	/*line emit.goal:1644*/ e.p("]")
}

//line emit.goal:1649
func (e *emitter) returnStmt(s *ast.ReturnStmt) {
	/*line emit.goal:1653*/ if cl, src, pos, fallible, ok := e.inlineDeriveReturn(s); ok {
		/*line emit.goal:1654*/ e.emitInlineDerive(cl, src, pos, fallible)
		/*line emit.goal:1655*/ return
	}
	/*line emit.goal:1657*/ if len(s.Results) == 1 {
		/*line emit.goal:1661*/ if m, ok := s.Results[0].(*ast.MatchExpr); ok {
			/*line emit.goal:1662*/ if isSealedMatch(m) {
				/*line emit.goal:1663*/ e.sealedMatch(m, posReturn, "")
				/*line emit.goal:1664*/ return
			}
			/*line emit.goal:1666*/ switch q := matchQualifier(m); {
			case q == "Result":
				e.resultMatch(m, posReturn, "")
				return
			case q == "Option":
				e.optionMatch(m, posReturn, "")
				return
			case enumOf(e.info, q) != nil:
				e.enumMatch(m, posReturn, "")
				return
			}
		}
		/*line emit.goal:1678*/ switch e.fnKind {
		case roResultOpen:
			if e.emitResultReturn(s.Results[0]) {
				/*line emit.goal:1681*/ return
			}
		case roOption:
			if e.emitOptionReturn(s.Results[0]) {
				/*line emit.goal:1685*/ return
			}
		case roResultClosed:
			if e.emitClosedResultReturn(s.Results[0]) {
				/*line emit.goal:1689*/ return
			}
		}
	}
	/*line emit.goal:1693*/ e.p("return")
	/*line emit.goal:1694*/ if len(s.Results) > 0 {
		/*line emit.goal:1695*/ e.p(" ")
		/*line emit.goal:1696*/ e.exprList(s.Results)
	}
}

//line emit.goal:1707
func (e *emitter) inlineDeriveReturn(s *ast.ReturnStmt) (*ast.CompositeLit, *ast.Ident, token.Pos, bool, bool) {
	/*line emit.goal:1708*/ if len(s.Results) == 1 {
		/*line emit.goal:1709*/ if cl, ok := s.Results[0].(*ast.CompositeLit); ok && cl.Type != nil {
			/*line emit.goal:1710*/ if src, pos, ok := deriveSpreadSrc(cl); ok {
				/*line emit.goal:1711*/ return cl, src, pos, false, true
			}
		}
	}
	/*line emit.goal:1715*/ if len(s.Results) == 2 {
		/*line emit.goal:1716*/ if cl, ok := s.Results[0].(*ast.CompositeLit); ok && cl.Type != nil && isNilIdent(s.Results[1]) {
			/*line emit.goal:1717*/ if src, pos, ok := deriveSpreadSrc(cl); ok {
				/*line emit.goal:1718*/ return cl, src, pos, true, true
			}
		}
	}
	/*line emit.goal:1722*/ return nil, nil, token.Pos{}, false, false
}

//line emit.goal:1727
func deriveSpreadSrc(cl *ast.CompositeLit) (*ast.Ident, token.Pos, bool) {
	/*line emit.goal:1728*/ for _, el := range cl.Elts {
		/*line emit.goal:1729*/ sp, ok := el.(*ast.SpreadElement)
		/*line emit.goal:1730*/ if !ok {
			/*line emit.goal:1731*/ continue
		}
		/*line emit.goal:1733*/ call, ok := sp.X.(*ast.CallExpr)
		/*line emit.goal:1734*/ if !ok {
			/*line emit.goal:1735*/ continue
		}
		/*line emit.goal:1737*/ fn, ok := call.Fun.(*ast.Ident)
		/*line emit.goal:1738*/ if !ok || fn.Name != "derive" || len(call.Args) != 1 {
			/*line emit.goal:1739*/ continue
		}
		/*line emit.goal:1741*/ if id, ok := call.Args[0].(*ast.Ident); ok {
			/*line emit.goal:1742*/ return id, sp.Pos(), true
		}
	}
	/*line emit.goal:1745*/ return nil, token.Pos{}, false
}

//line emit.goal:1749
func isNilIdent(e ast.Expr) bool {
	/*line emit.goal:1750*/ id, ok := e.(*ast.Ident)
	/*line emit.goal:1751*/ return ok && id.Name == "nil"
}

//line emit.goal:1756
func isDeriveSpread(sp *ast.SpreadElement) bool {
	/*line emit.goal:1757*/ call, ok := sp.X.(*ast.CallExpr)
	/*line emit.goal:1758*/ if !ok {
		/*line emit.goal:1759*/ return false
	}
	/*line emit.goal:1761*/ fn, ok := call.Fun.(*ast.Ident)
	/*line emit.goal:1762*/ return ok && fn.Name == "derive"
}

//line emit.goal:1770
func (e *emitter) emitInlineDerive(cl *ast.CompositeLit, src *ast.Ident, pos token.Pos, fallible bool) {
	/*line emit.goal:1771*/ tgtType := typeExprString(cl.Type)
	/*line emit.goal:1772*/ srcType, ok := e.paramType(src.Name)
	/*line emit.goal:1773*/ if !ok {
		/*line emit.goal:1774*/ e.fail("`...derive` at %s: source `%s` must be a parameter of the enclosing function", pos, src.Name)
		/*line emit.goal:1775*/ return
	}
	/*line emit.goal:1777*/ if _, ok := structFieldsOf(e.info, derefType(tgtType)); !ok {
		/*line emit.goal:1778*/ e.fail("`...derive` at %s: unknown target struct `%s` (no `type %s struct{…}` in this file)", pos, tgtType, derefType(tgtType))
		/*line emit.goal:1779*/ return
	}
	/*line emit.goal:1781*/ overrides := overridesFromLit(cl)
	/*line emit.goal:1782*/ e.p("{\n")
	/*line emit.goal:1783*/ e.emitConversionBody("", src.Name, srcType, tgtType, fallible, overrides, pos)
	/*line emit.goal:1784*/ e.p("}")
}

//line emit.goal:1792
func (e *emitter) tryVarMatch(d ast.Decl) bool {
	/*line emit.goal:1793*/ gd, ok := d.(*ast.GenDecl)
	/*line emit.goal:1794*/ if !ok || gd.Tok.String() != "var" || len(gd.Specs) != 1 {
		/*line emit.goal:1795*/ return false
	}
	/*line emit.goal:1797*/ vs, ok := gd.Specs[0].(*ast.ValueSpec)
	/*line emit.goal:1798*/ if !ok || len(vs.Names) != 1 || vs.Type == nil || len(vs.Values) != 1 {
		/*line emit.goal:1799*/ return false
	}
	/*line emit.goal:1801*/ m, ok := vs.Values[0].(*ast.MatchExpr)
	/*line emit.goal:1802*/ if !ok {
		/*line emit.goal:1803*/ return false
	}
	/*line emit.goal:1805*/ q := matchQualifier(m)
	/*line emit.goal:1806*/ if !isSealedMatch(m) && q != "Result" && q != "Option" && enumOf(e.info, q) == nil {
		/*line emit.goal:1807*/ return false
	}
	/*line emit.goal:1809*/ name := vs.Names[0].Name
	/*line emit.goal:1810*/ e.p("var " + name + " ")
	/*line emit.goal:1811*/ e.expr(vs.Type)
	/*line emit.goal:1812*/ e.p("\n")
	/*line emit.goal:1813*/ e.matchValue(m, q, posVar, name)
	/*line emit.goal:1814*/ return true
}

//line emit.goal:1820
func (e *emitter) matchValue(m *ast.MatchExpr, q string, pos matchPos, name string) {
	/*line emit.goal:1821*/ switch {
	case isSealedMatch(m):
		e.sealedMatch(m, pos, name)
	case q == "Result":
		e.resultMatch(m, pos, name)
	case q == "Option":
		e.optionMatch(m, pos, name)
	default:
		e.enumMatch(m, pos, name)
	}
}

//line emit.goal:1842
func (e *emitter) tryAssignMatch(s *ast.AssignStmt) bool {
	/*line emit.goal:1843*/ if len(s.Lhs) != 1 || len(s.Rhs) != 1 {
		/*line emit.goal:1844*/ return false
	}
	/*line emit.goal:1846*/ id, ok := s.Lhs[0].(*ast.Ident)
	/*line emit.goal:1847*/ if !ok {
		/*line emit.goal:1848*/ return false
	}
	/*line emit.goal:1850*/ m, ok := s.Rhs[0].(*ast.MatchExpr)
	/*line emit.goal:1851*/ if !ok {
		/*line emit.goal:1852*/ return false
	}
	/*line emit.goal:1854*/ q := matchQualifier(m)
	/*line emit.goal:1855*/ if !isSealedMatch(m) && q != "Result" && q != "Option" && enumOf(e.info, q) == nil {
		/*line emit.goal:1856*/ return false
	}
	/*line emit.goal:1858*/ typ, ok := e.inferMatchType(m)
	/*line emit.goal:1859*/ if !ok {
		/*line emit.goal:1860*/ e.fail("value-position `%s := match` needs an inferable result type (arms are not all one enum, string, or bool); annotate it as `var %s T = match ...` or use `return match ...`", id.Name, id.Name)
		/*line emit.goal:1861*/ return true
	}
	/*line emit.goal:1863*/ e.p("var " + id.Name + " " + typ + "\n")
	/*line emit.goal:1864*/ e.matchValue(m, q, posVar, id.Name)
	/*line emit.goal:1865*/ return true
}

//line emit.goal:1874
func (e *emitter) inferMatchType(m *ast.MatchExpr) (string, bool) {
	/*line emit.goal:1875*/ inferred := ""
	/*line emit.goal:1876*/ for _, arm := range m.Arms {
		/*line emit.goal:1877*/ kind, ok := e.armBodyType(arm.Body)
		/*line emit.goal:1878*/ if !ok {
			/*line emit.goal:1879*/ return "", false
		}
		/*line emit.goal:1881*/ switch {
		case inferred == "":
			inferred = kind
		case inferred != kind:
			return "", false
		}
	}
	/*line emit.goal:1888*/ return inferred, inferred != ""
}

//line emit.goal:1896
func (e *emitter) armBodyType(body ast.Node) (string, bool) {
	/*line emit.goal:1897*/ switch v1 := body.(type) {
	case *ast.BasicLit:
		{
			/*line emit.goal:1899*/ if v1.Kind == token.STRING {
				/*line emit.goal:1900*/ return "string", true
			}
		}
	case *ast.Ident:
		{
			/*line emit.goal:1904*/ if v1.Name == "true" || v1.Name == "false" {
				/*line emit.goal:1905*/ return "bool", true
			}
		}
	case *ast.SelectorExpr:
		{
			/*line emit.goal:1910*/ if key, ok := enumRef(v1.X); ok && v1.Sel != nil {
				/*line emit.goal:1911*/ if en := enumOf(e.info, key); en != nil && en.VSet[v1.Sel.Name] {
					/*line emit.goal:1912*/ return key, true
				}
			}
		}
	case *ast.VariantLit:
		{
			/*line emit.goal:1918*/ if key, ok := enumRef(v1.Enum); ok && enumOf(e.info, key) != nil {
				/*line emit.goal:1919*/ return key, true
			}
		}
	default:
		{
		}
	}
	/*line emit.goal:1924*/ return "", false
}

//line emit.goal:1930
func (e *emitter) emitResultReturn(x ast.Expr) bool {
	/*line emit.goal:1931*/ call, ok := x.(*ast.CallExpr)
	/*line emit.goal:1932*/ if !ok {
		/*line emit.goal:1933*/ return false
	}
	/*line emit.goal:1935*/ sel, ok := call.Fun.(*ast.SelectorExpr)
	/*line emit.goal:1936*/ if !ok || sel.Sel == nil {
		/*line emit.goal:1937*/ return false
	}
	/*line emit.goal:1939*/ if base, ok := sel.X.(*ast.Ident); !ok || base.Name != "Result" {
		/*line emit.goal:1940*/ return false
	}
	/*line emit.goal:1942*/ switch sel.Sel.Name {
	case "Ok":
		if len(call.Args) == 1 {
			/*line emit.goal:1947*/ if expr, ok := e.optionValueExpr(call.Args[0]); ok {
				/*line emit.goal:1948*/ e.p("return " + expr + ", nil")
				/*line emit.goal:1949*/ return true
			}
		}
		e.p("return ")
		e.exprList(call.Args)
		e.p(", nil")
		return true
	case "Err":
		e.p("return " + e.okName + ", ")
		e.exprList(call.Args)
		return true
	}
	/*line emit.goal:1961*/ return false
}

//line emit.goal:1973
func (e *emitter) optionValueExpr(x ast.Expr) (string, bool) {
	/*line emit.goal:1974*/ if sel, ok := x.(*ast.SelectorExpr); ok {
		/*line emit.goal:1975*/ if base, ok := sel.X.(*ast.Ident); ok && base.Name == "Option" && sel.Sel != nil && sel.Sel.Name == "None" {
			/*line emit.goal:1976*/ return "nil", true
		}
	}
	/*line emit.goal:1979*/ call, ok := x.(*ast.CallExpr)
	/*line emit.goal:1980*/ if !ok {
		/*line emit.goal:1981*/ return "", false
	}
	/*line emit.goal:1983*/ sel, ok := call.Fun.(*ast.SelectorExpr)
	/*line emit.goal:1984*/ if !ok || sel.Sel == nil || sel.Sel.Name != "Some" {
		/*line emit.goal:1985*/ return "", false
	}
	/*line emit.goal:1987*/ if base, ok := sel.X.(*ast.Ident); !ok || base.Name != "Option" {
		/*line emit.goal:1988*/ return "", false
	}
	/*line emit.goal:1990*/ if len(call.Args) != 1 {
		/*line emit.goal:1991*/ return "", false
	}
	/*line emit.goal:1993*/ some := e.gensym("some")
	/*line emit.goal:1994*/ e.p(some + " := ")
	/*line emit.goal:1995*/ e.expr(call.Args[0])
	/*line emit.goal:1996*/ e.p("\n")
	/*line emit.goal:1997*/ return "&" + some, true
}

//line emit.goal:2011
func (e *emitter) tryOptionValue(x ast.Expr) bool {
	/*line emit.goal:2012*/ kind, arg, ok := optionConstruction(x)
	/*line emit.goal:2013*/ if !ok {
		/*line emit.goal:2014*/ return false
	}
	/*line emit.goal:2016*/ switch kind {
	case "none":
		e.p("nil")
	default:
		e.usedOptionHelper = true
		e.p("goalSome(")
		e.expr(arg)
		e.p(")")
	}
	/*line emit.goal:2025*/ return true
}

//line emit.goal:2030
func (e *emitter) emitOptionReturn(x ast.Expr) bool {
	/*line emit.goal:2031*/ expr, ok := e.optionValueExpr(x)
	/*line emit.goal:2032*/ if !ok {
		/*line emit.goal:2033*/ return false
	}
	/*line emit.goal:2035*/ e.p("return " + expr)
	/*line emit.goal:2036*/ return true
}

//line emit.goal:2045
func (e *emitter) emitClosedResultReturn(x ast.Expr) bool {
	/*line emit.goal:2046*/ call, ok := x.(*ast.CallExpr)
	/*line emit.goal:2047*/ if !ok {
		/*line emit.goal:2048*/ return false
	}
	/*line emit.goal:2050*/ sel, ok := call.Fun.(*ast.SelectorExpr)
	/*line emit.goal:2051*/ if !ok || sel.Sel == nil {
		/*line emit.goal:2052*/ return false
	}
	/*line emit.goal:2054*/ if base, ok := sel.X.(*ast.Ident); !ok || base.Name != "Result" {
		/*line emit.goal:2055*/ return false
	}
	/*line emit.goal:2057*/ switch sel.Sel.Name {
	case "Ok":
		e.p(fmt.Sprintf("return Ok[%s, %s]{Value: ", e.closedT, e.closedE))
	case "Err":
		e.p(fmt.Sprintf("return Err[%s, %s]{Value: ", e.closedT, e.closedE))
	default:
		return false
	}
	/*line emit.goal:2065*/ e.exprList(call.Args)
	/*line emit.goal:2066*/ e.p("}")
	/*line emit.goal:2067*/ return true
}

//line emit.goal:2075
func (e *emitter) unwrap(name string, u *ast.UnwrapExpr, discard bool, tok string) {
	/*line emit.goal:2076*/ switch e.fnKind {
	case roResultOpen:
		e.unwrapResult(name, u, discard, tok)
	case roOption:
		e.unwrapOption(name, u, discard, tok)
	case roResultClosed:
		e.unwrapClosed(name, u, discard, tok)
	default:
		e.fail("`?` outside a Result- or Option-returning function")
	}
}

//line emit.goal:2093
func (e *emitter) unwrapClosed(name string, u *ast.UnwrapExpr, discard bool, tok string) {
	/*line emit.goal:2094*/ sig, ok := e.calleeSig(u.X)
	/*line emit.goal:2096*/ var isClosed bool
	switch sig.Mode.(type) {
	case sema.Mode_ModeResultClosed:
		isClosed = true
	default:
		isClosed = false
	}
	/*line emit.goal:2100*/ if !ok || !isClosed {
		/*line emit.goal:2101*/ e.fail("closed-E `?` needs a closed-E Result-returning callee")
		/*line emit.goal:2102*/ return
	}
	/*line emit.goal:2104*/ guard := e.gensym("r")
	/*line emit.goal:2105*/ errValue := guard + ".Value"
	/*line emit.goal:2106*/ if sig.E != e.closedE {
		/*line emit.goal:2107*/ conv, found := e.info.FromRegistry[[2]string{sig.E, e.closedE}]
		/*line emit.goal:2108*/ if !found {
			/*line emit.goal:2109*/ e.fail("no `from func` conversion declared for %s -> %s (required to `?` across closed error types)", sig.E, e.closedE)
			/*line emit.goal:2110*/ return
		}
		/*line emit.goal:2112*/ errValue = conv.Name + "(" + guard + ".Value)"
	}
	/*line emit.goal:2114*/ lhs := name
	/*line emit.goal:2115*/ if discard {
		/*line emit.goal:2116*/ lhs = "_"
	}
	/*line emit.goal:2121*/ if discard || tok != "=" {
		/*line emit.goal:2122*/ e.p("var " + lhs + " " + sig.T + "\n")
	}
	/*line emit.goal:2124*/ e.p("switch " + guard + " := ")
	/*line emit.goal:2125*/ e.expr(u.X)
	/*line emit.goal:2126*/ e.p(".(type) {\n")
	/*line emit.goal:2127*/ e.p(fmt.Sprintf("case Ok[%s, %s]:\n%s = %s.Value\n", sig.T, sig.E, lhs, guard))
	/*line emit.goal:2128*/ e.p(fmt.Sprintf("case Err[%s, %s]:\nreturn Err[%s, %s]{Value: %s}\n", sig.T, sig.E, e.closedT, e.closedE, errValue))
	/*line emit.goal:2129*/ e.p(fmt.Sprintf("default:\npanic(%q)\n}", fmt.Sprintf("unreachable: non-exhaustive Result[%s, %s] (compiler invariant violated)", sig.T, sig.E)))
}

//line emit.goal:2138
func (e *emitter) unwrapResult(name string, u *ast.UnwrapExpr, discard bool, tok string) {
	/*line emit.goal:2139*/ e.noteArityFallback(u)
	/*line emit.goal:2140*/ n := 2
	/*line emit.goal:2141*/ if sig, ok := e.calleeSig(u.X); ok && sig.EndsInError && sig.Arity >= 1 {
		/*line emit.goal:2142*/ n = sig.Arity
	}
	/*line emit.goal:2144*/ if discard {
		/*line emit.goal:2145*/ e.p("if " + strings.Repeat("_, ", n-1) + e.errName + " := ")
		/*line emit.goal:2146*/ e.expr(u.X)
		/*line emit.goal:2147*/ e.p("; " + e.errName + " != nil {\nreturn " + e.okName + ", " + e.errName + "\n}")
		/*line emit.goal:2148*/ return
	}
	/*line emit.goal:2150*/ if sig, ok := e.calleeSig(u.X); ok && sig.Arity != 2 {
		/*line emit.goal:2151*/ e.fail("`?` binds a value but the callee returns %d value(s); write a bare `…?` to propagate only the error", sig.Arity)
		/*line emit.goal:2152*/ return
	}
	/*line emit.goal:2154*/ e.p(name + ", " + e.errName + " " + tok + " ")
	/*line emit.goal:2155*/ e.expr(u.X)
	/*line emit.goal:2156*/ e.p("\nif " + e.errName + " != nil {\nreturn " + e.okName + ", " + e.errName + "\n}")
}

//line emit.goal:2165
func (e *emitter) noteArityFallback(u *ast.UnwrapExpr) {
	/*line emit.goal:2166*/ if e.arity == nil || u == nil {
		/*line emit.goal:2167*/ return
	}
	/*line emit.goal:2169*/ call, ok := u.X.(*ast.CallExpr)
	/*line emit.goal:2170*/ if !ok {
		/*line emit.goal:2171*/ return
	}
	/*line emit.goal:2173*/ sel, ok := call.Fun.(*ast.SelectorExpr)
	/*line emit.goal:2174*/ if !ok || sel.Sel == nil {
		/*line emit.goal:2175*/ return
	}
	/*line emit.goal:2177*/ pkg, ok := sel.X.(*ast.Ident)
	/*line emit.goal:2178*/ if !ok {
		/*line emit.goal:2179*/ return
	}
	/*line emit.goal:2183*/ if e.recvTypes != nil {
		/*line emit.goal:2184*/ if _, isRecv := e.recvTypes[pkg.Name]; isRecv {
			/*line emit.goal:2185*/ return
		}
	}
	/*line emit.goal:2188*/ path, ierr := e.arity.importErr(pkg.Name)
	/*line emit.goal:2189*/ if ierr == nil {
		/*line emit.goal:2190*/ return
	}
	/*line emit.goal:2192*/ fallback := "the two-value (T, error) default"
	/*line emit.goal:2193*/ if stdlibErrorOnly[pkg.Name+"."+sel.Sel.Name] {
		/*line emit.goal:2194*/ fallback = "the curated stdlib error-only table"
	}
	/*line emit.goal:2196*/ e.warns = append(e.warns, pipeline.Warning{File: e.srcFile, Line: u.Question.Line, Col: u.Question.Col, Code: "question-arity-fallback", Message: fmt.Sprintf("`?` arity for %s.%s could not be resolved: importing %q failed (%v); assumed %s", pkg.Name, sel.Sel.Name, path, ierr, fallback)})
}

//line emit.goal:2209
func (e *emitter) unwrapOption(name string, u *ast.UnwrapExpr, discard bool, tok string) {
	/*line emit.goal:2210*/ o := e.gensym("o")
	/*line emit.goal:2211*/ if discard {
		/*line emit.goal:2212*/ e.p("if " + o + " := ")
		/*line emit.goal:2213*/ e.expr(u.X)
		/*line emit.goal:2214*/ e.p("; " + o + " == nil {\nreturn nil\n}")
		/*line emit.goal:2215*/ return
	}
	/*line emit.goal:2217*/ e.p(o + " := ")
	/*line emit.goal:2218*/ e.expr(u.X)
	/*line emit.goal:2219*/ e.p("\nif " + o + " == nil {\nreturn nil\n}\n" + name + " " + tok + " *" + o)
}

//line emit.goal:2228
var stdlibErrorOnly = map[string]bool{"os.Mkdir": true, "os.MkdirAll": true, "os.Remove": true, "os.RemoveAll": true, "os.Rename": true, "os.Chmod": true, "os.Chown": true, "os.Chdir": true, "os.Chtimes": true, "os.Symlink": true, "os.Link": true, "os.Truncate": true, "os.Setenv": true, "os.Unsetenv": true, "os.WriteFile": true, "json.Unmarshal": true, "xml.Unmarshal": true, "binary.Read": true, "binary.Write": true}

//line emit.goal:2255
func (e *emitter) calleeSig(x ast.Expr) (sema.FuncSig, bool) {
	/*line emit.goal:2256*/ call, ok := x.(*ast.CallExpr)
	/*line emit.goal:2257*/ if !ok {
		/*line emit.goal:2258*/ return sema.FuncSig{}, false
	}
	/*line emit.goal:2260*/ switch v1 := call.Fun.(type) {
	case *ast.Ident:
		{
			/*line emit.goal:2262*/ if e.info == nil || e.info.FuncSignatures == nil {
				/*line emit.goal:2263*/ return sema.FuncSig{}, false
			}
			/*line emit.goal:2265*/ sig, ok := e.info.FuncSignatures[v1.Name]
			/*line emit.goal:2266*/ return sig, ok
		}
	case *ast.SelectorExpr:
		{
			/*line emit.goal:2269*/ pkg, ok := v1.X.(*ast.Ident)
			/*line emit.goal:2270*/ if !ok || v1.Sel == nil {
				/*line emit.goal:2271*/ return sema.FuncSig{}, false
			}
			/*line emit.goal:2277*/ if sig, ok := e.methodCalleeSig(pkg.Name, v1.Sel.Name); ok {
				/*line emit.goal:2278*/ return sig, true
			}
			/*line emit.goal:2282*/ if a := e.arity.lookup(pkg.Name, v1.Sel.Name); a.resolved && a.endsErr {
				/*line emit.goal:2283*/ return sema.FuncSig{Mode: sema.Mode(sema.Mode_ModeResult{}), Arity: a.results, EndsInError: true}, true
			}
			/*line emit.goal:2285*/ if stdlibErrorOnly[pkg.Name+"."+v1.Sel.Name] {
				/*line emit.goal:2286*/ return sema.FuncSig{Mode: sema.Mode(sema.Mode_ModeResult{}), Arity: 1, EndsInError: true}, true
			}
			/*line emit.goal:2288*/ return sema.FuncSig{}, false
		}
	default:
		{
		}
	}
	/*line emit.goal:2292*/ return sema.FuncSig{}, false
}

//line emit.goal:2302
func (e *emitter) methodCalleeSig(recv, method string) (sema.FuncSig, bool) {
	/*line emit.goal:2303*/ if e.info == nil || e.recvTypes == nil {
		/*line emit.goal:2304*/ return sema.FuncSig{}, false
	}
	/*line emit.goal:2306*/ typ, ok := e.recvTypes[recv]
	/*line emit.goal:2307*/ if !ok || typ == "" {
		/*line emit.goal:2308*/ return sema.FuncSig{}, false
	}
	/*line emit.goal:2310*/ for _, m := range e.info.Methods[typ] {
		/*line emit.goal:2311*/ if m.Name == method {
			/*line emit.goal:2312*/ return m.Return, true
		}
	}
	/*line emit.goal:2315*/ for _, m := range e.info.Interfaces[typ] {
		/*line emit.goal:2316*/ if m.Name == method {
			/*line emit.goal:2317*/ return m.Return, true
		}
	}
	/*line emit.goal:2320*/ return sema.FuncSig{}, false
}

//line emit.goal:2328
func (e *emitter) buildRecvTypes(d *ast.FuncDecl) map[string]string {
	/*line emit.goal:2329*/ out := map[string]string{}
	/*line emit.goal:2330*/ add := func(fl *ast.FieldList) {
		/*line emit.goal:2331*/ if fl == nil {
			/*line emit.goal:2332*/ return
		}
		/*line emit.goal:2334*/ for _, f := range fl.List {
			/*line emit.goal:2335*/ base := recvBaseType(f.Type)
			/*line emit.goal:2336*/ if base == "" {
				/*line emit.goal:2337*/ continue
			}
			/*line emit.goal:2339*/ for _, n := range f.Names {
				/*line emit.goal:2340*/ if n != nil && n.Name != "" && n.Name != "_" {
					/*line emit.goal:2341*/ out[n.Name] = base
				}
			}
		}
	}
	/*line emit.goal:2346*/ add(d.Recv)
	/*line emit.goal:2347*/ if d.Type != nil {
		/*line emit.goal:2348*/ add(d.Type.Params)
	}
	/*line emit.goal:2350*/ if len(out) == 0 {
		/*line emit.goal:2351*/ return nil
	}
	/*line emit.goal:2353*/ return out
}

//line emit.goal:2359
func buildCurParams(d *ast.FuncDecl) map[string]string {
	/*line emit.goal:2360*/ if d.Type == nil || d.Type.Params == nil {
		/*line emit.goal:2361*/ return nil
	}
	/*line emit.goal:2363*/ out := map[string]string{}
	/*line emit.goal:2364*/ for _, f := range d.Type.Params.List {
		/*line emit.goal:2365*/ ts := typeExprString(f.Type)
		/*line emit.goal:2366*/ for _, n := range f.Names {
			/*line emit.goal:2367*/ if n != nil && n.Name != "" && n.Name != "_" {
				/*line emit.goal:2368*/ out[n.Name] = ts
			}
		}
	}
	/*line emit.goal:2372*/ if len(out) == 0 {
		/*line emit.goal:2373*/ return nil
	}
	/*line emit.goal:2375*/ return out
}

//line emit.goal:2379
func (e *emitter) paramType(name string) (string, bool) {
	/*line emit.goal:2380*/ if e.curParams == nil {
		/*line emit.goal:2381*/ return "", false
	}
	/*line emit.goal:2383*/ t, ok := e.curParams[name]
	/*line emit.goal:2384*/ return t, ok
}

//line emit.goal:2391
func recvBaseType(x ast.Expr) string {
	/*line emit.goal:2392*/ switch v1 := x.(type) {
	case *ast.StarExpr:
		{
			/*line emit.goal:2394*/ return recvBaseType(v1.X)
		}
	case *ast.Ident:
		{
			/*line emit.goal:2397*/ return v1.Name
		}
	case *ast.IndexExpr:
		{
			/*line emit.goal:2400*/ return recvBaseType(v1.X)
		}
	case *ast.IndexListExpr:
		{
			/*line emit.goal:2403*/ return recvBaseType(v1.X)
		}
	default:
		{
			/*line emit.goal:2406*/ return ""
		}
	}
}

//line emit.goal:2414
func (e *emitter) matchStmt(m *ast.MatchExpr) {
	/*line emit.goal:2415*/ if isSealedMatch(m) {
		/*line emit.goal:2416*/ e.sealedMatch(m, posStmt, "")
		/*line emit.goal:2417*/ return
	}
	/*line emit.goal:2419*/ switch q := matchQualifier(m); q {
	case "Result":
		e.resultMatch(m, posStmt, "")
	case "Option":
		e.optionMatch(m, posStmt, "")
	default:
		if enumOf(e.info, q) != nil {
			/*line emit.goal:2426*/ e.enumMatch(m, posStmt, "")
			/*line emit.goal:2427*/ return
		}
		e.fail("unsupported statement-position match on %q (only Result/Option and enum match are lowered)", q)
	}
}

//line emit.goal:2436
type matchPos int

//line emit.go:2078
const (
	posStmt matchPos = iota
	posReturn
	posVar
)

//line emit.goal:2451
func (e *emitter) enumMatch(m *ast.MatchExpr, pos matchPos, name string) {
	/*line emit.goal:2452*/ enumName := matchQualifier(m)
	/*line emit.goal:2453*/ en := enumOf(e.info, enumName)
	/*line emit.goal:2455*/ usesBinding := false
	/*line emit.goal:2456*/ for _, arm := range m.Arms {
		/*line emit.goal:2457*/ if vp, ok := arm.Pattern.(*ast.VariantPattern); ok && vp.Binding != nil && usesIdent(arm.Body, vp.Binding.Name) {
			/*line emit.goal:2458*/ usesBinding = true
			/*line emit.goal:2459*/ break
		}
	}
	/*line emit.goal:2463*/ guard := ""
	/*line emit.goal:2464*/ e.p("switch ")
	/*line emit.goal:2465*/ if usesBinding {
		/*line emit.goal:2466*/ guard = e.gensym("v")
		/*line emit.goal:2467*/ e.p(guard + " := ")
	}
	/*line emit.goal:2469*/ e.expr(m.Subject)
	/*line emit.goal:2470*/ e.p(".(type) {\n")
	/*line emit.goal:2472*/ var restArm *ast.MatchArm

	/*line emit.goal:2473*/
	for _, arm := range m.Arms {
		/*line emit.goal:2474*/ vp, ok := arm.Pattern.(*ast.VariantPattern)
		/*line emit.goal:2475*/ if !ok {
			/*line emit.goal:2476*/ if _, isRest := arm.Pattern.(*ast.RestPattern); isRest {
				/*line emit.goal:2477*/ restArm = arm
			}
			/*line emit.goal:2479*/ continue
		}
		/*line emit.goal:2481*/ if vp.Variant == nil {
			/*line emit.goal:2482*/ e.fail("enum match arm has no variant tag")
			/*line emit.goal:2483*/ return
		}
		/*line emit.goal:2485*/ e.p("case " + enumName + "_" + vp.Variant.Name + ":\n")
		/*line emit.goal:2486*/ e.emitEnumArm(arm, vp, en, guard, pos, name)
		/*line emit.goal:2487*/ e.p("\n")
	}
	/*line emit.goal:2490*/ e.p("default:\n")
	/*line emit.goal:2491*/ if restArm != nil {
		/*line emit.goal:2492*/ e.emitEnumArm(restArm, nil, en, guard, pos, name)
	} else {
		/*line emit.goal:2494*/ e.p(fmt.Sprintf("panic(%q)", fmt.Sprintf("unreachable: non-exhaustive %s (compiler invariant violated)", enumName)))
	}
	/*line emit.goal:2496*/ e.p("\n}")
}

//line emit.goal:2502
func (e *emitter) emitEnumArm(arm *ast.MatchArm, vp *ast.VariantPattern, en *sema.Enum, guard string, pos matchPos, name string) {
	/*line emit.goal:2503*/ binding := ""
	/*line emit.goal:2504*/ if vp != nil && vp.Binding != nil {
		/*line emit.goal:2505*/ binding = vp.Binding.Name
	}
	/*line emit.goal:2507*/ if binding != "" {
		/*line emit.goal:2508*/ if e.renames == nil {
			/*line emit.goal:2509*/ e.renames = map[string]string{}
		}
		/*line emit.goal:2511*/ e.renames[binding] = guard
		/*line emit.goal:2512*/ prevBinding, prevFields := e.armBinding, e.armFields
		/*line emit.goal:2513*/ e.armBinding = binding
		/*line emit.goal:2514*/ if en != nil && vp.Variant != nil {
			/*line emit.goal:2515*/ e.armFields = en.FieldSet[vp.Variant.Name]
		} else {
			/*line emit.goal:2517*/ e.armFields = nil
		}
		/*line emit.goal:2519*/ defer func() {
			/*line emit.goal:2520*/ delete(e.renames, binding)
			/*line emit.goal:2521*/ e.armBinding, e.armFields = prevBinding, prevFields
		}()
	}
	/*line emit.goal:2524*/ e.armWrap(arm.Body, pos, name)
}

//line emit.goal:2531
func (e *emitter) armWrap(body ast.Node, pos matchPos, name string) {
	/*line emit.goal:2532*/ switch pos {
	case posReturn:
		e.p("return ")
		e.armBody(body)
	case posVar:
		e.p(name + " = ")
		e.armBody(body)
	default:
		e.armBody(body)
	}
}

//line emit.goal:2551
func (e *emitter) sealedMatch(m *ast.MatchExpr, pos matchPos, name string) {
	/*line emit.goal:2552*/ usesBinding := false
	/*line emit.goal:2553*/ for _, arm := range m.Arms {
		/*line emit.goal:2554*/ if tp, ok := arm.Pattern.(*ast.TypePattern); ok && tp.Binding != nil && usesIdent(arm.Body, tp.Binding.Name) {
			/*line emit.goal:2555*/ usesBinding = true
			/*line emit.goal:2556*/ break
		}
	}
	/*line emit.goal:2560*/ guard := ""
	/*line emit.goal:2561*/ e.p("switch ")
	/*line emit.goal:2562*/ if usesBinding {
		/*line emit.goal:2563*/ guard = e.gensym("v")
		/*line emit.goal:2564*/ e.p(guard + " := ")
	}
	/*line emit.goal:2566*/ e.expr(m.Subject)
	/*line emit.goal:2567*/ e.p(".(type) {\n")
	/*line emit.goal:2569*/ var restArm *ast.MatchArm

	/*line emit.goal:2570*/
	for _, arm := range m.Arms {
		/*line emit.goal:2571*/ tp, ok := arm.Pattern.(*ast.TypePattern)
		/*line emit.goal:2572*/ if !ok {
			/*line emit.goal:2573*/ if _, isRest := arm.Pattern.(*ast.RestPattern); isRest {
				/*line emit.goal:2574*/ restArm = arm
			}
			/*line emit.goal:2576*/ continue
		}
		/*line emit.goal:2578*/ if tp.Type == nil {
			/*line emit.goal:2579*/ e.fail("sealed match arm has no concrete type")
			/*line emit.goal:2580*/ return
		}
		/*line emit.goal:2582*/ e.p("case ")
		/*line emit.goal:2583*/ e.expr(tp.Type)
		/*line emit.goal:2584*/ e.p(":\n")
		/*line emit.goal:2585*/ e.emitSealedArm(arm, tp, guard, pos, name)
		/*line emit.goal:2586*/ e.p("\n")
	}
	/*line emit.goal:2589*/ e.p("default:\n")
	/*line emit.goal:2590*/ if restArm != nil {
		/*line emit.goal:2591*/ e.emitSealedArm(restArm, nil, guard, pos, name)
	} else {
		/*line emit.goal:2593*/ e.p(fmt.Sprintf("panic(%q)", "unreachable: non-exhaustive sealed match (compiler invariant violated)"))
	}
	/*line emit.goal:2595*/ e.p("\n}")
}

//line emit.goal:2603
func (e *emitter) emitSealedArm(arm *ast.MatchArm, tp *ast.TypePattern, guard string, pos matchPos, name string) {
	/*line emit.goal:2604*/ binding := ""
	/*line emit.goal:2605*/ if tp != nil && tp.Binding != nil {
		/*line emit.goal:2606*/ binding = tp.Binding.Name
	}
	/*line emit.goal:2608*/ if binding != "" {
		/*line emit.goal:2609*/ if e.renames == nil {
			/*line emit.goal:2610*/ e.renames = map[string]string{}
		}
		/*line emit.goal:2612*/ e.renames[binding] = guard
		/*line emit.goal:2613*/ defer delete(e.renames, binding)
	}
	/*line emit.goal:2615*/ e.armWrap(arm.Body, pos, name)
}

//line emit.goal:2626
func (e *emitter) resultMatch(m *ast.MatchExpr, pos matchPos, name string) {
	/*line emit.goal:2627*/ var subjectIsClosed bool
	switch e.calleeMode(m.Subject).(type) {
	case sema.Mode_ModeResultClosed:
		subjectIsClosed = true
	case sema.Mode_ModeResult:
		subjectIsClosed = false
	case sema.Mode_ModeOption:
		subjectIsClosed = false
	case sema.Mode_ModeNone:
		subjectIsClosed = false
	default:
		panic("unreachable: non-exhaustive sema.Mode (compiler invariant violated)")
	}
	/*line emit.goal:2633*/ if subjectIsClosed {
		/*line emit.goal:2634*/ e.closedResultMatch(m, pos, name)
		/*line emit.goal:2635*/ return
	}
	/*line emit.goal:2637*/ okArm, errArm := armByVariant(m, "Ok"), armByVariant(m, "Err")
	/*line emit.goal:2638*/ if okArm == nil || errArm == nil {
		/*line emit.goal:2639*/ e.fail("Result match must have both Result.Ok and Result.Err arms")
		/*line emit.goal:2640*/ return
	}
	/*line emit.goal:2642*/ val, errVar := e.gensym("v"), e.gensym("err")
	/*line emit.goal:2643*/ okBinding := bindingName(okArm.Pattern)
	/*line emit.goal:2644*/ okLHS := "_"
	/*line emit.goal:2645*/ if okBinding != "" && usesIdent(okArm.Body, okBinding) {
		/*line emit.goal:2646*/ okLHS = val
	}
	/*line emit.goal:2648*/ e.p(okLHS + ", " + errVar + " := ")
	/*line emit.goal:2649*/ e.expr(m.Subject)
	/*line emit.goal:2650*/ e.p("\nif " + errVar + " != nil {\n")
	/*line emit.goal:2651*/ e.armBodyRenamedWrap(errArm.Body, bindingName(errArm.Pattern), errVar, pos, name)
	/*line emit.goal:2652*/ e.p("\n} else {\n")
	/*line emit.goal:2653*/ e.armBodyRenamedWrap(okArm.Body, okBinding, val, pos, name)
	/*line emit.goal:2654*/ e.p("\n}")
}

//line emit.goal:2663
func (e *emitter) closedResultMatch(m *ast.MatchExpr, pos matchPos, name string) {
	/*line emit.goal:2664*/ sig, _ := e.calleeSig(m.Subject)
	/*line emit.goal:2665*/ okArm, errArm := armByVariant(m, "Ok"), armByVariant(m, "Err")
	/*line emit.goal:2666*/ if okArm == nil || errArm == nil {
		/*line emit.goal:2667*/ e.fail("Result match must have both Result.Ok and Result.Err arms")
		/*line emit.goal:2668*/ return
	}
	/*line emit.goal:2670*/ okBinding, errBinding := bindingName(okArm.Pattern), bindingName(errArm.Pattern)
	/*line emit.goal:2671*/ okUse := okBinding != "" && usesIdent(okArm.Body, okBinding)
	/*line emit.goal:2672*/ errUse := errBinding != "" && usesIdent(errArm.Body, errBinding)
	/*line emit.goal:2674*/ guard := ""
	/*line emit.goal:2675*/ e.p("switch ")
	/*line emit.goal:2676*/ if okUse || errUse {
		/*line emit.goal:2677*/ guard = e.gensym("r")
		/*line emit.goal:2678*/ e.p(guard + " := ")
	}
	/*line emit.goal:2680*/ e.expr(m.Subject)
	/*line emit.goal:2681*/ e.p(".(type) {\n")
	/*line emit.goal:2683*/ e.p(fmt.Sprintf("case Ok[%s, %s]:\n", sig.T, sig.E))
	/*line emit.goal:2684*/ if okUse {
		/*line emit.goal:2685*/ e.p(okBinding + " := " + guard + ".Value\n")
	}
	/*line emit.goal:2687*/ e.armWrap(okArm.Body, pos, name)
	/*line emit.goal:2688*/ e.p(fmt.Sprintf("\ncase Err[%s, %s]:\n", sig.T, sig.E))
	/*line emit.goal:2689*/ if errUse {
		/*line emit.goal:2690*/ e.p(errBinding + " := " + guard + ".Value\n")
	}
	/*line emit.goal:2692*/ e.armWrap(errArm.Body, pos, name)
	/*line emit.goal:2693*/ e.p(fmt.Sprintf("\ndefault:\npanic(%q)\n}", fmt.Sprintf("unreachable: non-exhaustive Result[%s, %s] (compiler invariant violated)", sig.T, sig.E)))
}

//line emit.goal:2699
func (e *emitter) optionMatch(m *ast.MatchExpr, pos matchPos, name string) {
	/*line emit.goal:2700*/ someArm, noneArm := armByVariant(m, "Some"), armByVariant(m, "None")
	/*line emit.goal:2701*/ if someArm == nil || noneArm == nil {
		/*line emit.goal:2702*/ e.fail("Option match must have both Option.Some and Option.None arms")
		/*line emit.goal:2703*/ return
	}
	/*line emit.goal:2705*/ o := e.gensym("o")
	/*line emit.goal:2706*/ e.p("if " + o + " := ")
	/*line emit.goal:2707*/ e.expr(m.Subject)
	/*line emit.goal:2708*/ e.p("; " + o + " != nil {\n")
	/*line emit.goal:2709*/ if b := bindingName(someArm.Pattern); b != "" && usesIdent(someArm.Body, b) {
		/*line emit.goal:2710*/ e.p(b + " := *" + o + "\n")
	}
	/*line emit.goal:2712*/ e.armWrap(someArm.Body, pos, name)
	/*line emit.goal:2713*/ e.p("\n} else {\n")
	/*line emit.goal:2714*/ e.armWrap(noneArm.Body, pos, name)
	/*line emit.goal:2715*/ e.p("\n}")
}

//line emit.goal:2719
func armByVariant(m *ast.MatchExpr, variant string) *ast.MatchArm {
	/*line emit.goal:2720*/ for _, arm := range m.Arms {
		/*line emit.goal:2721*/ if vp, ok := arm.Pattern.(*ast.VariantPattern); ok && vp.Variant != nil && vp.Variant.Name == variant {
			/*line emit.goal:2722*/ return arm
		}
	}
	/*line emit.goal:2725*/ return nil
}

//line emit.goal:2729
func bindingName(p ast.Expr) string {
	/*line emit.goal:2730*/ if vp, ok := p.(*ast.VariantPattern); ok && vp.Binding != nil {
		/*line emit.goal:2731*/ return vp.Binding.Name
	}
	/*line emit.goal:2733*/ return ""
}

//line emit.goal:2739
func (e *emitter) calleeMode(x ast.Expr) sema.Mode {
	/*line emit.goal:2740*/ call, ok := x.(*ast.CallExpr)
	/*line emit.goal:2741*/ if !ok {
		/*line emit.goal:2742*/ return sema.Mode(sema.Mode_ModeNone{})
	}
	/*line emit.goal:2744*/ id, ok := call.Fun.(*ast.Ident)
	/*line emit.goal:2745*/ if !ok || e.info == nil || e.info.FuncSignatures == nil {
		/*line emit.goal:2746*/ return sema.Mode(sema.Mode_ModeNone{})
	}
	/*line emit.goal:2750*/ sig, found := e.info.FuncSignatures[id.Name]
	/*line emit.goal:2751*/ if !found {
		/*line emit.goal:2752*/ return sema.Mode(sema.Mode_ModeNone{})
	}
	/*line emit.goal:2754*/ return sig.Mode
}

//line emit.goal:2759
func (e *emitter) armBodyRenamed(body ast.Node, binding, target string) {
	/*line emit.goal:2760*/ if binding != "" {
		/*line emit.goal:2761*/ if e.renames == nil {
			/*line emit.goal:2762*/ e.renames = map[string]string{}
		}
		/*line emit.goal:2764*/ e.renames[binding] = target
		/*line emit.goal:2765*/ defer delete(e.renames, binding)
	}
	/*line emit.goal:2767*/ e.armBody(body)
}

//line emit.goal:2774
func (e *emitter) armBodyRenamedWrap(body ast.Node, binding, target string, pos matchPos, name string) {
	/*line emit.goal:2775*/ if binding != "" {
		/*line emit.goal:2776*/ if e.renames == nil {
			/*line emit.goal:2777*/ e.renames = map[string]string{}
		}
		/*line emit.goal:2779*/ e.renames[binding] = target
		/*line emit.goal:2780*/ defer delete(e.renames, binding)
	}
	/*line emit.goal:2782*/ e.armWrap(body, pos, name)
}

//line emit.goal:2795
func (e *emitter) armBody(n ast.Node) {
	/*line emit.goal:2796*/ switch b := n.(type) {
	case nil:
	case ast.Stmt:
		e.stmt(b)
	case ast.Expr:
		e.expr(b)
	default:
		e.fail("unsupported match arm body %T", n)
	}
}

//line emit.goal:2808
func (e *emitter) sliceExpr(x *ast.SliceExpr) {
	/*line emit.goal:2809*/ e.expr(x.X)
	/*line emit.goal:2810*/ e.p("[")
	/*line emit.goal:2811*/ if x.Low != nil {
		/*line emit.goal:2812*/ e.expr(x.Low)
	}
	/*line emit.goal:2814*/ e.p(":")
	/*line emit.goal:2815*/ if x.High != nil {
		/*line emit.goal:2816*/ e.expr(x.High)
	}
	/*line emit.goal:2818*/ if x.Max != nil {
		/*line emit.goal:2819*/ e.p(":")
		/*line emit.goal:2820*/ e.expr(x.Max)
	}
	/*line emit.goal:2822*/ e.p("]")
}

//line emit.goal:2825
func (e *emitter) chanType(x *ast.ChanType) {
	/*line emit.goal:2826*/ switch x.Dir.(type) {
	case ast.ChanDir_RecvOnly:
		e.p("<-chan ")
	case ast.ChanDir_SendOnly:
		e.p("chan<- ")
	case ast.ChanDir_SendRecv:
		e.p("chan ")
	default:
		panic("unreachable: non-exhaustive ast.ChanDir (compiler invariant violated)")
	}
	/*line emit.goal:2831*/ e.expr(x.Value)
}

//line emit.goal:2834
func (e *emitter) identList(ids []*ast.Ident) {
	/*line emit.goal:2835*/ for i, id := range ids {
		/*line emit.goal:2836*/ if i > 0 {
			/*line emit.goal:2837*/ e.p(", ")
		}
		/*line emit.goal:2839*/ e.p(id.Name)
	}
}

//line emit.goal:2843
func (e *emitter) exprList(xs []ast.Expr) {
	/*line emit.goal:2844*/ for i, x := range xs {
		/*line emit.goal:2845*/ if i > 0 {
			/*line emit.goal:2846*/ e.p(", ")
		}
		/*line emit.goal:2848*/ e.expr(x)
	}
}
