// Code generated by "task generate" from goal source; DO NOT EDIT.

package backend

//line matchprobe.go:4
import (
	goast "go/ast"
	"go/importer"
	"go/parser"
	"go/token"
	"go/types"
	"goal/internal/pipeline"
	"strings"
)

//line matchprobe.goal:30
func resolveMatchProbes(pkgName string, goFiles []pipeline.GoFile, unresolved []matchProbe) map[string]string {
	/*line matchprobe.goal:31*/ fset := token.NewFileSet()
	/*line matchprobe.goal:32*/ var files []*goast.File

	/*line matchprobe.goal:33*/
	for _, gf := range goFiles {
		/*line matchprobe.goal:34*/ f, err := parser.ParseFile(fset, gf.Name, gf.Go, parser.SkipObjectResolution)
		/*line matchprobe.goal:35*/ if err != nil {
			/*line matchprobe.goal:36*/ return map[string]string{}
		}
		/*line matchprobe.goal:38*/ files = append(files, f)
	}
	/*line matchprobe.goal:41*/ info := &types.Info{Defs: map[*goast.Ident]types.Object{}}
	/*line matchprobe.goal:42*/ conf := types.Config{Importer: importer.ForCompiler(fset, "source", nil), Error: func(err error) {
	}}
	/*line matchprobe.goal:48*/ typesPkg, _ := conf.Check(pkgName, fset, files, info)
	/*line matchprobe.goal:50*/ capTypes := captureVarTypes(info, typesPkg)
	/*line matchprobe.goal:51*/ resolved := map[string]string{}
	/*line matchprobe.goal:52*/ for _, mp := range unresolved {
		/*line matchprobe.goal:53*/ if t, ok := agreedCaptureType(capTypes, mp.prefix); ok {
			/*line matchprobe.goal:54*/ resolved[mp.prefix] = t
		}
	}
	/*line matchprobe.goal:57*/ return resolved
}

//line matchprobe.goal:63
func captureVarTypes(info *types.Info, typesPkg *types.Package) map[string]string {
	/*line matchprobe.goal:64*/ qualifier := types.Qualifier(nil)
	/*line matchprobe.goal:65*/ if typesPkg != nil {
		/*line matchprobe.goal:66*/ qualifier = types.RelativeTo(typesPkg)
	}
	/*line matchprobe.goal:68*/ out := map[string]string{}
	/*line matchprobe.goal:69*/ for id, obj := range info.Defs {
		/*line matchprobe.goal:70*/ if obj == nil || !strings.HasPrefix(id.Name, "__goalmatch_") {
			/*line matchprobe.goal:71*/ continue
		}
		/*line matchprobe.goal:73*/ if v, ok := obj.(*types.Var); ok {
			/*line matchprobe.goal:74*/ out[id.Name] = types.TypeString(v.Type(), qualifier)
		}
	}
	/*line matchprobe.goal:77*/ return out
}

//line matchprobe.goal:83
func agreedCaptureType(capTypes map[string]string, prefix string) (string, bool) {
	/*line matchprobe.goal:84*/ agreed := ""
	/*line matchprobe.goal:85*/ found := false
	/*line matchprobe.goal:86*/ for name, typ := range capTypes {
		/*line matchprobe.goal:87*/ if !strings.HasPrefix(name, prefix) {
			/*line matchprobe.goal:88*/ continue
		}
		/*line matchprobe.goal:90*/ if typ == "" {
			/*line matchprobe.goal:91*/ return "", false
		}
		/*line matchprobe.goal:93*/ if !found {
			/*line matchprobe.goal:94*/ agreed, found = typ, true
		} else if agreed != typ {
			/*line matchprobe.goal:96*/ return "", false
		}
	}
	/*line matchprobe.goal:99*/ return agreed, found
}
