// Code generated by goal; DO NOT EDIT.
// generator: goal vdev

package typecheck

//line gotypes.go:4
import (
	"go/types"
	"goal/internal/sema"
	"strings"
)

//line gotypes.goal:31
func goTypeDiags(p *Package) []Diagnostic {
	/*line gotypes.goal:32*/ var diags []Diagnostic

	/*line gotypes.goal:33*/
	for _, e := range p.Errors {
		/*line gotypes.goal:34*/ te, ok := e.(types.Error)
		/*line gotypes.goal:35*/ if !ok {
			/*line gotypes.goal:36*/ continue
		}
		/*line gotypes.goal:38*/ if te.Soft {
			/*line gotypes.goal:39*/ continue
		}
		/*line gotypes.goal:41*/ if strings.HasPrefix(te.Msg, "could not import") {
			/*line gotypes.goal:42*/ continue
		}
		/*line gotypes.goal:44*/ pos := te.Fset.Position(te.Pos)
		/*line gotypes.goal:45*/ if !strings.HasSuffix(pos.Filename, ".goal") {
			/*line gotypes.goal:46*/ continue
		}
		/*line gotypes.goal:48*/ diags = append(diags, Diagnostic{Pos: pos, Severity: sema.Severity(sema.Severity_Error{}), Feature: "go-types", Code: "go-type-error", Message: te.Msg})
	}
	/*line gotypes.goal:56*/ return diags
}
